#+Title: Tyler Burns Website
#+Author: Tyler Burns
#+Date: May 22, 2026
#+Purpose: tasks and lab notebook

* Tasks
** DONE expand the talismans to be every personal article (so that there are a lot of talismans)
CLOSED: [2026-05-24 Sun 21:43]
** DONE fix the post-gremlin transport bug
CLOSED: [2026-05-24 Sun 15:41]
The gremlins don't do anything after the initial random transport.
** IN-PROGRESS add game mode as a state button
** TODO figure out what to do about "short" LI posts
** IN-PROGRESS make LI post of game mode
SCHEDULED: <2026-05-26 Tue>
** TODO consider little mini-game challenges
Platformers, "insert" and so forth.
** TODO find the little path bugs and patch them
** CANCELLED address the Safari "skips around" issue
CLOSED: [2026-05-25 Mon 18:29]
** TODO add the talisman system to the regular game mode
* Log
** 2026
*** May
**** May 23
Added game mode to the site as of today. Hidden link in the about section at a period.
**** May 24
***** LI post for game mode
Who said that scrolling was best? Here I'm building out a "game mode" for my website, that gives you a Mario World style map you can use to navigate my content.

This map is divided into specific biomes that track to categories of work I share on my site (bioinformatics, philosophy, etc). Watch out for the gremlins! If one gets you, you'll get transported to a random piece of content.

The point is, there are way more ways to explore the internet than merely browsing through bottomless walls of media. What if social media had a mode like this?
***** LI post, claude edits
Who said that scrolling was best? I built a "game mode" for my website. A Mario World style overworld map you can use to navigate my content. Tap anywhere to move the cat. Each biome is a category of my work (bioinformatics, philosophy, etc).

Watch out for the green gremlins wandering the map. If one catches you, you get teleported to a random piece of content. Hopefully a good one.

Link is in the comments below.

The point: there are more ways to explore the web than bottomless feeds. The web is supposed to be a network of places, not a single river of media. What if every website gave you a map like this?
***** general idea: AR mode
One general idea that would be cool is to geocache each article and have to go to a place to get access to it or a collections of articles. I think you would need a legit mobile app but can a website get your GPS location? That sounds sketch. Let's check real quick.

Check reveals that this is indeed possible with a static html page. Good.
***** where to put game mode
Option 1, as a hidden link.
Option 2, as a direct link on the website.

We should eventually hit option 2.
***** secret room
We need a place to put my secret Marcus Aurelius Chapter 1 post. We'll have to sit with this one for a minute.
***** more elaborate game mode
We made the game map much bigger and added a talisman system that unlocks personal essays (because personal is valuable). We can expand this but the concept is there and fine as is.
***** back to the smaller map
We are thinking that the better user experience is the smaller map, though we are open to ideas. We can add the talisman system to the smaller map and it might be a bit more manageable. It depends on whether the user wants a handle on my stuff or wants to get lost in a map. Either way, I think we are done for the day. This was a good session, if only to get a feel for the different possibilities here.
