#+Title: Love the un-word, fear the un-word
#+Author: Tyler Burns
#+Date: November 11, 2023 - November 11, 2023

* Draft 1
I.

I was baptized a Catholic, and while we didn't go to Church every Sunday, I was raised with Christian values under the idea that there was a God who would reward the good and punish the bad. A lot of this came from my grandma, who my sister and I would stay with every Sunday. There, we learned about the Bible stories and the basics of what it meant to be a Christian. And it was good.

Later, in my teenage years, my scientific mind took over. I wasn't steadfast atheist, but I considered myself agnostic. The Hubble Space Telescope didn't find a bearded man floating around between galaxies creating stuff, but I was open to the idea that maybe we'd find something down the line.

I think one of the key things here that shaped my thinking for decades to come was when I asked my mom why the Bible didn't talk about dinosaurs and planets and electrons and the like. My mom's answer was that she believed the Bible was meant to be interpreted symbolically, as stories you could use to help you live your life. I was fine with that answer, and this stuck with me for a long time; but I didn't fully appreciate that answer until later in life, when I was smack in the middle of the real world.

I grew up in the US in the 90s. When we look back at the 90s now, we see a world where (at least in the US) there was a lot of crime. When people talk about how crime is going up right now (2023), there is always an obligatory "yes but it's nowhere near to what it was in the 90s." Fair...that's a topic for another time. My point is during the 90s, the Soviet Union had collapsed, the US was the single dominant power, and we had an extremely optimistic vision of a future full of science and technology and flying cars and robots. Something like [[https://en.wikipedia.org/wiki/The_Jetsons][The Jetsons]]. History, with all of its wars and plagues and famines, was behind us. Do what you love, and the money will follow, as my mom would say. Perhaps she only told me this because she knew I liked math and science.

Anyway, we're now living in a world where this optimism isn't exactly there anymore. We've learned that we're not immune to [[https://en.wikipedia.org/wiki/COVID-19_pandemic][pandemics]], and [[https://en.wikipedia.org/wiki/Russian_invasion_of_Ukraine][major]] [[https://en.wikipedia.org/wiki/2023_Israel%E2%80%93Hamas_war][wars]] are still a thing, to name a few recent things. Rapid development of new tech has made things a lot less stable, and some think that, for example, AI is going to [[https://www.youtube.com/watch?v=gA1sNLL6yg4&t=25s][kill us all]].

In short, I realized that science and technology isn't the answer to all of our problems. That a science and technology centered world bereft of religion has its failure modes as well, just as the religion-centered world of yesteryear had. Now I have a PhD in Cancer Biology, and I stand by science as a critical aspect of living in a peaceful society and growing as a species. But this is just me saying that science isn't the end of it.

II.

I realized at some point that there were things that were simply hard to pin down sufficient to do scientific studies on. I lost my father during that phase of my life where I considered my father to basically be superman. Before the phase where you see the imperfections. Thus, he is this permanent superman image in my head that I oriented toward until I became older than him a few years ago. It wasn't until recently I learned that there's a word for that: [[https://en.wikipedia.org/wiki/Jungian_archetypes][Jungian Archetype]]. Something coined by psychologist Carl Jung, that is something to the effect of a humanized manifestation of an ideal or virtue. When you think about "wisdom," you probably picture a calm, bearded old man. That's an example of a Jungian archetype that your brain manifested over the years (perhaps thanks to Hollywood). But the point here is that it's very difficult to do a neuroscientific study on Jungian archetypes. Or to really pin down a proper defintion so we can even start to think scientifically about it. But I know its there. When I think of my father to this day, I think of this idealized Clark Kent walking around, something I will never become but must strive to become.

This moves us into the direction of words and concepts that are difficult to scientifically pin down, but are still important to look at because they are central to our experience in life. This isn't me saying that the Jungian archetype is impossible to study under the scientific lens, but it is much harder to get at than, say, short-term memory or olfaction. But there are things that are hard to pin down that you should still nonetheless think about. I didn't dismiss this idealized image of my father I carried around just because I didn't know where in the brain that image sat and how it interacted with the images of the virtues and vices.

While we're lingering on the brain, I'll give you another one that I keep coming back to: the hard problem of consciousness. In other words, we are conscious...we see the world through our eyes and no someone else's...um...what's up with that? The hard problem of consciousness is a fun example here because the solution is not something you can just do a neuroscience PhD project on and be done with it, and the problem itself is hard to put into words as well. I'm looking at my hands and moving them around. Now I stopped moving them around. Now I'm moving them again. What the heck? This moves us into a similar domain of free will and all the people who spend their whole lives arguing that it exists or it [[https://www.youtube.com/watch?v=xhobcj2K9v4][doesn't exist]]. Or the question of whether my internal perception of the color green matches yours? Perhaps what you see as green, I see as orange? How would you know? But again, these things are very hard to get at scientifically (though we should try as much as we can).

Now we're moving in the direction of questions and things that are hard to even put into words. Again, the hard problem of consciousness can best be expressed by someone looking at their fingers and wiggling them with a half-astonished half-horrified expression on their face. Those who don't think free will exists can best state their position by taking you through [[https://www.youtube.com/watch?v=SYq724zHUTw][particular exercises]] (meditate for 10 minutes, then ask yourself where the next thought is coming from and where does it go). Those who think free will exists can best state their position by saying "I'm going to move my hand" and then moving their hand. But as you can see, we're getting into muddy territory here. Solutions we cannot get at, and problems we can't really put into words, that are nonetheless central to the core of our being.

III.

One day, I came across the Tao Te Ching. It's a small book. You can read it in a few hours (though it may take a lifetime to understand it). The first stanza is:

/The tao that can be told/
/is not the eternal Tao/
/The name that can be named/
/is not the eternal Name./

I've written about this before numerous times, as this is central to the way I look at the world, but let's look at it through the lens of everything I've written here. We just started wading into the murky waters where it becomes much harder to solve something through my scientific upbringing. And this takes us all the way to the limit. That there are things that cannot be put into words at all. Or even thought about. Or named. Tao represents all that which, upon trying to put it into words, it's not that. Ian McGilchrist calls this an un-word. A word that points to the realm of the ineffible: that which you cannot effing put into words.

And this brings us back to Christianity, my upbringing at Grandma's house on Sundays. The Eastern Orthodox tradition often uses what is called /via negativa/ to describe what [[https://orthodoxwiki.org/Apophatic_theology][God is]]. In other words, they focus on what God is not. This is also known as Apophatic Theology, and it is by no means limited to Orthodix Christianity, though this was the first example where I came to know about it. So for at least some branches of Christianity, God is an un-word, just as Tao is. It's about that which is beyond anything you can word of define.

Does this mean we should give up in talking about the divine, or talking about things that can't be talked about? To say yes is to do the same thing you do in science where you focus on that which can be gotten at by hypothesis and experimentation. You miss a whole lot of the richness of life that way. But my main point here is we can go back and start to re-interpret the religious doctrines in terms of simply the recognition of the existance of things that are beyond our words, that perhaps feelings and art and prayer and meditation could perhaps give us a vague sense of from time to time.

IV.

Let's start with belief in God, something that is a rather senstive topic for those who think unbelievers will go to hell and that kind of thing. Let's ask if I belive in the un-word? Do I believe that there are things that are far beyond words? Do I believe in the ineffible? Do I believe in the infinity of thoughts I will never think, realizations I will never realize, and feelings I will never feel? Of course I do. This [[https://www.ribbonfarm.com/2023/10/23/vastness/][vastness]] is the spice of life. When people talk about belief in God getting you entry to Heaven, there is an interesting metaphor here. My awareness (or belief) in the un-word, this infinite vastness, enriches life to the point where you might say that it stears you toward Heaven and away from the dark meaningless void of Hell that you get when the world is reduced to rational utility functions or whatever.

Ok, what about those who say things like "God is love." Well, let's think about the un-word. All the times I have ever had a glancing blow with the ineffible vastness, which for me is usually spontaneous and leads me to feel like I'm part of something bigger than myself and all of that. Or things like when the day my newphew was born, or the day my grandmother (the same one I talked about earlier) passed away, where I am reminded of what is important in life, which, surprise surprise, cannot really be put into words. Arguably, these things can be pointed to with an un-word, and metaphor. In Christian terms, you might call that "when you feel the presence of God." And in this context, when you start to put that into a Jungian archetype, what you get is a warm, loving individual who is very much not of this Earth. I feel this in my bones, as I held my father in my head as Jungian archetype for so many years, and the Christians like to think of God as "the father." So in this regard, the un-word is love. And from there, it is easy to talk about and express the "love of God."

But what about the fear of God, under this interpretation? A friend of mine once told me a story about a guy who was super into fitness, just like me. He ran marathons, ate right, did all the things the doctor says you should do. And one day in his 40s he dropped dead of a heart attack. Another example: I knew a professor, Jon Ohlfest, at the University of Minnesota who I was considering doing my PhD thesis under. He lost his grandma to the same type of cancer I lost my father to, and we both wanted to wipe that cancer from the face of the Earth. This man worked day and night. Slept with his pipettes and grant proposals. The face of academic virtue and resolve. You want to know what happened to him? He got pancreatic cancer and died young. These stories, all in a sense related to the [[https://en.wikipedia.org/wiki/Book_of_Job][Book of Job]], involve terrible things happening to people who do everything right. There is a feeling that you get when you see these kinds of things happening that is very hard to put into words. It is a sort of un-word that any older person can definitely point to. And this un-word leads to a healthy sense of fear. It could happen to me or a loved one next. It could happen tomorrow. This radically changes how one lives their life. It brings you square in the moment. This fear of the un-word is what the Christians call fear of God. And you know what King Solomon says: "fear of God is the beginning of wisdom."

V.

I am not a churchgoer out here and neither is my wife. But we do have a shelf of books from the major religions, and I consider myself to be religion-literate. Back to my mom's belief in the symbolic interpretation of the Bible, thinking of God as an un-word that points to the ineffible is a great way to start to interpret some of these old texts. But I didn't write this beacause I want people to become symbolically religous and cross out God and write un-word everywhere. That's not the point of this.

The point of this article is the idea that there is a deep and wide vastness beyond our words. And another one beyond our pictures. And another one beyond our thoughts, and beyond the thoughts of any human brain. This vastness, that we get little glimpses of here and there, called many things ranging from Tao to God, can only really be pointed to by the use of the un-word. This vastness is to be loved, this vastness is to be feared. A lot of the bigger questions in life, from Jungian archetypes to free will to consciousness, require us to tap into this vastness pointed to by an un-word. A lot of our instincts and intuitions are within the realm of this un-word. If we put it into words, it recedes from us. But if we acknowledge that it's there, and try to live in accordance with it, it enriches our lives in ways that are, well, kinda hard to put into words.
* Draft 2
There was an episode of Dr. Who I was watching a few years ago, that involved some sort of parallel universe time travel thing. Dr. Who of course had invented a way to do that. His companion ask how does it work. The following dialogue happens (I'm paraphrasing):

/Companion: How does it work?/\\
/Dr. Who: So you know how time slows down when you get near a black hole due to gravity?/\\
/Companion: Yes./\\
/Dr. Who: Ok, well it's NOTHING like that. At all. But that will have to do for now./\\

I remember awaiting some sort of fun sci-fi [[https://gwern.net/doc/philosophy/epistemology/2012-sistery-tryingtoseethrough.html][insight]] from Dr. Who about gravity and black holes and quantum mechanics, only to have that dashed because how it works is light years beyond anything that humans of our era can comprehend. Which itself was an insight.

This is a special instance of a concept called [[https://en.wikipedia.org/wiki/Apophatic_theology][via negativa]] that we see in religion, that comes after one stops thinking of God as a bearded man in the clouds. It goes something like this:

/Is God a bearded man?/\\
/No./\\
/Is God a spirit?/\\
/No./\\
/Is God love?/\\
/No./\\
/Is God...like...I dunno...some sort of cosmic consciousness thing?/\\
/No./\\

And so on. It's by no means randomly generated questions. It only works if you get more and more sophisticated with each one. You do that long enough and it moves you into a sort of aporia where you're now thinking of all that which is beyond anything you've thought and felt before. And that's still not God, but you're on the right track.

I touched upon this kind of thing a story of my intellectual journey as a biologist, where I realized at every new step that "[[https://tjburns08.github.io/its_more_complicated_than_that.html][it's more complicated than that]]." Same idea. You come across a new thing or new insight in the direction of trying to understand a thing. You realized that it's more complicated than that. That one answer leads to 10 other questions. And so on forever. But that doesn't lead to nihilism. Quite the opposite. It's addictive. You can study the same thing for your entire career and still feel like you've just gotten started.

Ok, so one way to compress all of this is through what author [[https://en.wikipedia.org/wiki/The_Matter_with_Things][Ian McGilchrist]] calls an un-word. It's literally a word that points to a thing that cannot be put into words. The most direct example of this is Tao, something I have written about [[https://tjburns08.github.io/pursuit_of_health.html][before]]. The first line of the Tao Te Ching goes:

/The Tao that can be told is not the eternal Tao./
/The name that can be named is not the eternal name./

The rest of the book talks about how to align yourself with Tao, and points in the direction of things that Tao is and what it does (eg. analogies to water), but cautions against the idea that you'll wake up one day and finally know what Tao is. Because whatever it is, Tao is beyond that.

For those who approach God in the same light also use God as an un-word. Same thing. If you're Christian, you can look at Jesus as a human form that point you in the direction of how to conduct yourself to live a good life (the standard question "what would Jesus do"), but there is this father, son, holy spirit trinity thing that is way more vast and complicated that any human brain would ever be able to comprehend.

The main point here is that I often have to remind myself that there is way more to whatever it is I'm looking at or thinking about than I can possibly imagine. It's easy to get complacent and think that I know a thing. It's particuarly dangerous when it's something outside my field, where the [[https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect][Dunning-Krüger effect]] will make me think I know it better than I actually do. The PhD in biology beat that out of me...in biology. But it's still a struggle to remember that whatever it is that I think I know, I'll feel like it's a complete mystery after 5 years of 60+ hours a week of study.

Now if we interpret the religious texts in the light of the un-word, things get interesting. I grew up Christian so we'll use that simply because that's where I'm more literate, but you can do this with any religious/spiritual text.

One of the big concepts in Christianity is the fear of God. King Solomon (prominent sage in the Bible) says that "fear of God is the beginning of wisdom." So what does it mean when fear of the un-word is the beginning of wisdom? I think it has something to do with all the forces beyond me that can lead to all kinds of bad stuff at any given moment, regardless of whether I'm a good or a bad person. I know a professor named Jon Ohlfest from University of Minnesota who did brain cancer research. I was considering working with him for my PhD thesis, and I interviewed with him accordingly. We both had lost loved ones to glioblastoma multiforme early on: I lost my father and he lost his grandmother. He had dedicated his entire life to brain cancer research. "Just as the Samurai sleeps with his sword" he told me. He was expecting me to do the same if I joined his lab, which I was willing to do, to avenge the death of my father. This was a big part of my identity. You know what happened to him? Shortly after I started my PhD thesis over at Stanford in cancer biology, he got diagnosed with cancer and died. What the hell am I supposed to make of that?

This is not the only story I know of that features terrible things happening to good people. It seems to be a common trope, and perhaps why the Book of Job is so popular. For those of you who are not Bible-literate, the Book of Job is about terrible things happening to the world's most faithful servant of God. It's a long story, but you can get a [[https://www.youtube.com/watch?v=xQwnH8th_fs][video summary here]]. Long story short, God ends up testing his faith by making all kinds of bad things happen to him. The death of family members and livestock, the burning of his property, and sickness that leaves the otherwise healthy strong handsome man hunched over, emaciated, and covered in boils. Job demands to speak to God, accusing him of being incompetent at running the universe. God shows up. He takes Job on a cosmic tour (or gives him a cosmic lecture, however you want to interpret it) where he gets a glancing blow of the ineffible vastness that is God and the universe. Job realizes that in short, it's more complicated than that. Job returns. He gets it.

So along with the idea that "it's more complicated than that," the book of Job has a twist being that the complexity that we do not comprehend could lead to all kinds of suffering to us and our loved ones. That the un-word can lead to pleasure, but it can also lead to pain. That's kindof a scary thing. That keeps me up at night, as well as jolts me out of bed in the morning. Because I know that both in the widest stretches of the cosmos and the tiniest corners of my world, even the corners that have been most observed, lies depth, complexity and vastness that can lead to all kinds of things.

[[https://www.meaningcrisis.co/ep-34-awakening-from-the-meaning-crisis-sacredness-horror-music-and-the-symbol/][John Vervaeke]] likes to talk about how awe and horror are different sides of the same coin. And the fear of the un-word is basically this: a sense of awe mixed in with a sense of horror. Because they are one and the same. And to admit ignorance, which allows you to really feel this in your bones...perhaps that is the beginning of wisdom.
