#+TITLE: Marketing is being a good friend
#+DATE: July 8 - July 8

[[./index.org][Home]]

Actually, it's MUCH more than that. Marketing itself is a career path for a reason. It's really complicated.

But.

I run a company, and I have to do marketing to get clients. It's a lot of work. This being said, my first three clients came from good friends of mine who simply knew someone who needed my skillset. There was very little if any "screening," white board coding interviews, or any of that. There appeared to be trust right at the start. My friend trusted me, so my client trusted me. This got my business off the ground, giving me enough momentum through re-signs and referrals to keep going. Want to get your business off the ground? Be a good friend. 


If we rewind to 2009, I was a certified personal trainer. A lot of my clients there became my friends. If you want someone to achieve their health and fitness goals, you really have to get to know them, which often led to me really liking and respecting them as a person. Accordingly, a lot of my clients from back then are still my friends to this day. When your clients are your friends, they're going to re-sign with you after the sessions they bought are used up. Want your clients to re-sign with you? Be a good friend. 
