#+Title: Zelda, enchantment, and the hero instinct
#+Author: Tyler Burns
#+Date: June 19, 2023

[[./index.html][Home]]

In the past few days, I have been watching a full playthrough of the classic game Zelda: A Link to the Past on SNES. It is a game that for many reasons I never played as a kid (I went the Sega and PS1 route), but I know is packed with nostalgia for others. As a result of having no nostalgia upon watching the gameplay, I can do an unbiased analysis of the game itself. What I like about analyzing old (8 or 16 bit era) games is that the first principles of the game are laid bare, as there is no reliance on being bamboozled with amazing life-like graphics and physics to make the game "good."

The game starts off with an immediate quest to rescue the princess, who has been captured. So with a start, you get out of the house, run to the dungeon through rain and thunder, and find the princess. So the standard hero trope. But then, you find yourself on a much large quest, to rescue not one, but seven damsels in distress from dungeons guarded by evil dungeon masters, in a parallel "dark world" similar to the one in Stranger Things. Of course, you, Link, are the only hope.

On top of this, it's open world gameplay, something that is more common today. There is the main quest and side quests. There are people you can talk to, who have meaningful tidbits of information that can allow you to do meaningful things and find meaningful secrets. There are secret rooms, caves, and passageways that make you feel good when you find, similar to the secret doors in Wolfenstein 3D. Often, you have to transport between the real world and the dark world to get the next thing done. It's easy to get totally absorbed in the game, both as a player, and a viewer. It's easy to get into the flow state.

One way to think of this game or this type of game is that in comparison to real life, everything is meaningful. The conversations matter, the surroundings matter (gotta find those secret passageways), the side quests matter, the main quest matters, and within the main quest, you are the hero. You are the only hope. On top of that, everything is enchanting. New dungeons, new creatures, new biomes, two parallel worlds, books that translate ancient languages, a wise man descended from seven great wise men guiding you, magic exists, and there is an evil wizard using a lot of it.

So not only do you have challenging gameplay that requires exploration, and developing skills to navigate, fight, and solve interesting puzzles (in the dungeons, for the next door to open, for example), but you also have these layers of meaning and enchantment serving as a backbone. The former is what triggers a classic flow state, and oftentimes that by itself is sufficient to make a great game (think Tetris), but the latter grounds that flow state so it always feels like you're flowing to a particular destination. It's what the Christians might call "sense of purpose." So we might simplify this game in terms of fun, challenging activities grounded in a strong sense of purpose and enchanting things yet to be discovered.

What does this sound like to you? Well for me, it sounds very much like childhood in general. You play a lot more than you work. There is a lot of fun to be had. There is a strong sense of purpose: to grow bigger and stronger and smarter and to do good things (at least this is how I was raised). And everything is enchanting. There are all kinds of weird, crazy, fascinating, exciting new things every day. Not that I felt like a hero rescuing damsels in distress from evil doers, but it sure felt like a palpable future. I'll note here that the original Zelda game for NES was motivated by the outdoor adventures one of the creators went on as a kid on the outskirts of Kyoto, one of which included actually finding and exploring a cave, a common trope in these games.

Ok, now lets jump to adult life and compare it to Zelda. Is there exploration? Somewhat. We get to travel sometimes, but most things are mapped out and we can figure out where we are and what's around with our smartphone. What about enchantment? Not so much. Especially for a guy who has a PhD in biology. It's there, but I have to [[https://en.wikipedia.org/wiki/Sponge_spicule][look harder]] and [[https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_biology][ask better questions]]. But even then, it's not always the same level of intense fascination. What about quests to rescue damsels in distress? Not really. I am married, but my wife is very tough and I don't find myself rescuing her all the time. My family in general is pretty self sufficient. The modern world makes it so. While I do help my family when I can, they would not be severely crippled if I died. The fate of the world does not depend on my heroic existence. A lot of people get PhDs in biosciences because they think they're going to cure cancer or whatever else. Turns out that curing any disease is very complicated and requires more than just one person. Just look at COVID. Did one hero emerge and save us all? No. There was a worldwide group effort to develop vaccines that some say were good and some say were evil.

At the psychological level, why is Zelda such a good game? Somehow, its triggering a bunch of aspects of the brain that we evolved over millions of years. At some level, it must have been advantageous to find "vignettes" in our life where we could be the hero and explore the world and defeat the villain, and be enchanted by novelty (rather than terrified). I would guess that this is a pre-dunbar (back when we were hunter-gatherer tribes of 200 or so) evolution that stays with us today as neural legacy code. In the hunter-gatherer world, we knew a lot less. Of course, I don't have a time machine that can take me back, but from what it seems from what we know about present-day hunter-gatherers, we can say a few things. We were guided a lot more by mythology, which was enchanting stories mixed in with wisdom from our revered tribe elders (they had their place, in comparison with our fascination with Rogaine and Botox). There was indeed evil in the world: lions and tigers and bears, and of course, whatever tribe we were warring with. Survival was a lot harder. And there were heros that probably emerged from all of this.

One place you see the emergence of heros today: war. I listen to podcasts where people who fought in Iraq and Afghanistan, talk about their time there. They emphasize that it was somewhere between not fun and terrifying, but they have lots of acts of heroism that happened that are, by my standards, epic. Similar stories emerge from those retelling what their grandparents went thorugh in the two World Wars and Vietnam (something you can find on discussion forums like Reddit). Another example: during the Fukushima reactor meltdown, there were old people at the end of their life who sacrificed themselves to go into the reactor unprotected to do things to prevent the meltdown from getting much worse. These people went in to the reactor, did what they had to do, and died upon their return. Heroes. Note of course the key difference between Zelda and this: for real-world heroes, you often end up dead, crippled, or with PTSD, only to come home and be treated badly. But I digress.

We might think of our fascination with heroes as a computer program that evolved in our brain, that we feel as a hero instinct. If we didn't have this, then it would be a lot harder for ordinary people to take the reins during hard times and do extraordinary things that benefit the group. The group that has the hero instinct will make it through hard times in comparison to a group that does not have the hero instinct. Thus, I would guess that this is a group selection event. Playing games like Zelda can be thought of as triggering this hero instinct.

So then what does this mean for the modern world, where every major problem (eg. climate change) requires a massive group effort rather than an individual hero? Where enchantment is much harder to come by? Where exploration is not the same, given that we have satellite images and street-view images of most places? Where we can watch travel vlogs on YouTube to see what its like wherever. Where globalism has killed a lot of the cultural differences in the world? Or perhaps put differently, what kinds of instincts would we have evolved if we were an interconnected, global-supply-chain superorganism that we are now, but for millions of years? Would there be more of a "massive global teamwork" instinct? It's not as sexy as the hero instinct that Zelda exemplifies. Because we appear to have evolved the latter, not the former.

I have found that the hero instinct sometimes gets in the way now. I watch Marvel movies (which is like 50% of all movies that come out these days), and then feel empty inside because my adult life is not nearly as enchanting and heroic as these stories. When COVID showed up, it became clear that there was not going to be a lone hero. The hero instinct died pretty quickly. And of course, one man's hero is another man's villain. That's politics in a nutshell.

The Taoists like to talk about water and the wisdom it carries. In the case of being part of a quest or side-quest or whatever else, I think of my time in grad school where I used to go surfing on the weekends. When you're on the board, you're in the ocean waiting for the next set of waves to come. On a bad day, either you wipe out all the time or no good waves come. On a good day, you catch a good handful. You position yourself where you're most likely to catch the wave, and you let nature do its thing. But importantly, you can spend hours out there waiting, and seconds actually on a wave. So maybe Zelda is the epitome of what its like to be on a wave in life, and a lot of adult life is just spent on your board, bobbing up and down in the ocean, just trying to position yourself properly, and letting things happen from there.

What this means is we have to get over the fact that we're not always going to be on a wave. In fact, it will be little tidbits here and there, if that. So we have to be cool with and enjoy the time we spend bobbing up and down in the water, on the surfboard, enjoying the scenery. Some of my best memories from when I used to surf were the things that happened when I wasn't on a wave. I saw a handful of dolphins, sea otters popping up near me, beautiful sunsets, among many other things, while on that board. In those moments, I wasn't pining for that next wave to come. Some of the Eastern traditions (Taoism, Buddhism) put a lot of emphasis on this: enjoying the moment whether or not you're doing something cool, or whether you're in hard times. That's what focusing on the breath does. One quote I heard from a Zen master was something like "If you can't enjoy your cup of coffee in the morning, then I have nothing to teach you."

Sam Harris (something of a rational mystic) talks about boredom in terms of not paying enough attention. When you're playing Zelda, you don't have to pay very much attention. It's more like attention pays you, and you just sit there as you ride the layers of meaning and enchantment the game experience has. When I meditate (and I'm not talking about the Lotus position and Om, I'm talking about focusing on the breath whether I'm sitting or walking or whatever else), normal stimuli start to become enhanced. I can in fact enjoy my morning cup of coffee without scrolling through social media at the same time. In short, I think the layers of meaning and enchantment and exploration that makes Zelda such a great game can be found in your morning cup of coffee, and I think the opportunity to be a hero (even for something small, for a brief moment) can be found in the humdrum activities of adult life, if you know where and how to look.
