#+Title: April 2023
#+Author: Tyler Burns

[[./index.html][Home]]

The current subjective state for the month of April, 2023. My second newsletter, or time capsule. Whatever you want to call it. Let's get started.

-----

I came across an interesting idea from Venkat Rao, who happens to generate a lot of interesting ideas. He said to consider thinking of the world as protocol first rather than people first. Yes, we have agency, but at every interface with a human or a machine, there are protocols, from handshakes to rituals on the human side, to http on the computer side. It's an interesting shift, where once you see it, it's hard to unsee. He's hosting a [[https://efdn.notion.site/Summer-of-Protocols-3d7983d922184c4eb72749e9cb60d076][Summer of Protocols]] program to get more people to look into this. I missed the deadline to sign up, though I might do my own independent research accordingly.

-----

I learned about an interesting phrase: [[https://en.wikipedia.org/wiki/System_D][System D]]. This is basically when you have to innovate and improvise in the most extreme circumstances. Anthony Bourdain has written about this. Specifically, from a [[https://www.denverpost.com/2006/05/26/the-nasty-bits-by-anthony-bourdain/][Denver Post review of his book The Nasty Bits]]:

"It’s when the orders are pouring in and the supplies are running low and the tempers are growing thin that one sees System D practiced at its highest level. Hot water heater explodes? No sweat. Just push the rillettes over and start boiling water, carnale. Run out of those nice square dinner plates for the lobster spring rolls? No problem. Dummy up a new presentation and serve on the round plates. We know what to do. Meat grinder broken? It’s steak tartare cut by hand, papi. Few things are more beautiful to me than a bunch of thuggish, heavily-tattooed line cooks moving around each other like ballerinas on a busy Saturday night. Seeing two guys who’d just as soon cut each other’s throats in their off hours moving in unison with grace and ease can be as uplifting as any chemical stimulant or organized religion."

-----

As a former academic researcher, who still does research, I was happy to learn that AI researcher Janus, whose output consists of blogs and tweets, has been cited in academic literature, in this [[https://arxiv.org/abs/2302.00805][Arxiv paper]], which also cites many other bloggers.

-----

I am a fan of first principles, and thus I am a fan of [[https://colab.research.google.com/drive/1SiF0KZJp75rUeetKOWqpsA8clmHP6jMg?usp=sharing][Andrej Karpathy's "baby GPT."]] Its tokens are 0 or 1 with a context window of 3. It is trained on binary strings. It then outputs 3-bit binary strings. With all the work on ChatGPT-related tools right now (and there are plenty of other newsletters covering this), I think it's important to take a step back and get some fundamental insight from programming the simplest version of whatever it is that is trending.

-----

I am a fan of [[http://www.catb.org/~esr/faqs/hacker-howto.html][hacking]], in the sense of clever re-purposing of tools and/or problem solving. This is expressed often in terms of computers, but it is by no means limited to them. In particular, a good hack involves something that I have never thought of, where my mental model of some corner of the world completely falls out from under me.

So I was immediately fascinated by [[https://en.wikipedia.org/wiki/Dishwasher_salmon][dishwasher salmon]]. The idea is that you can actually take raw salmon, wrap it in foil, place it into the dishwasher for a standard wash and dry cycle, and you have cooked salmon. There is a caveat here, explained in the article, that not every dishwasher heats its dishes at the same temperature and duration. So you would really have to test it with a meat thermometer to see if the salmon do indeed cook fully given the initial conditions. If it does, then you have a cooking process that is apparently odorless (as you can probably tell, I have yet to try this). What's more: apparently, you can wash dishes alongside your salmon if you package it tightly enough.

-----

We have been talking about post-truth for a while, especially in the context of AI, where it is often referred to as "deep fakes." Here is a pretty good expression of that, where scammers [[https://nypost.com/2023/04/12/ai-clones-teen-girls-voice-in-1m-kidnapping-scam/][cloned the voice of a teen girl]], and then tried to convince her mom that she had been kidnapped. They demanded a ransom of $1 million. One of the FBI agents on the case recommended asking a bunch of questions that voice cloners would not know. While this advice might seem obvious, it is still good to keep that as part of a checklist for all of your loved ones, as things like this may become more common as the AIs get better at what they do.
