#+Title: May 2023
#+Author: Tyler Burns

[[./index.html][Home]]

What came into my life in the month of May 2023, that is worth re-hashing, so I don't forget, and so others can benefit.

-----

My mom's side of the family comes from Guyana. It's rare that Guyana makes the news, but it did recently due to an [[https://apnews.com/article/guyana-oil-discovery-money-14c23a72c6d7c13675493ede42ed1000][oil boom]] in the country that could potentially tranform the economy. Obviously, I am hoping for the best.

-----

I learned of a new brilliant word in the tech world: enshittification. In other words, the decline of quality of a particular product, due to business decisions, until it is complete shit. Want to see an example? Have a look at [[https://digg.com/][digg]], which used to be just like [[https://old.reddit.com/][reddit]]. Now it's just clickbaitey junk. And how about [[https://myspace.com/discover/featured][myspace]]? It was a music-oriented rival to facebook, and now it has the same format as modern digg. It's as if enshittification has a formula to it. [[https://pluralistic.net/2023/01/21/potemkin-ai/][This article]] talks about the enshittification of TikTok.

I'll just quote the first paragraph that sums up the mental model:

"Here is how platforms die: first, they are good to their users; then they abuse their users to make things better for their business customers; finally, they abuse those business customers to claw back all the value for themselves. Then, they die."

-----

Another interesting phrase I learned, when it comes to measures of cognition: cognitive endurance. This is the ability to sustain cognitive effort for long periods of time. An example of this might be how many math problems (at your level) you can do before you fatigue and start to see declines in performance. We all have needed feats of cognitive endurance, for example when we had to take standardized tests in high school and college to get to the next thing.

This [[https://marginalrevolution.com/marginalrevolution/2023/05/the-importance-of-cognitive-endurance.html?utm_source=rss&utm_medium=rss&utm_campaign=the-importance-of-cognitive-endurance][blog post]] suggests that cognitive endurance is one of the core attributes that we acquire in school, provided that the quality of the school in question is high enough.

-----

I value ingenuity very highly. This is often known in my circles as "hack value." I found an example that takes the cake. [[https://github.com/mmulet][Michael Mulet]] created a [[https://www.coderelay.io/fontemon.html][pokemon-like game]], entirely within a font. No extra code. Just a single [[https://en.wikipedia.org/wiki/OpenType][.otf]] (font) file. This is something I would have never thought to do, and I can't imagine just how much work went into re-purposing a font file to run a game.

-----

A lecture in a CS class at Stanford turned into a relationship advice session (business partners, friends, romance, the rest of it). Professor John Ousterhout said [[https://gist.github.com/gtallen1187/27a585fcf36d6e657db2][here]] (written on GitHub gists of all places) that relationships die because of scar tissue. Little resentments here and there that build up over time.

To quote him:

"You have to ask yourself, "Are you really, completely, 100% over this? You're giving in? No animosity? You're not secretly hoping that maybe they'll do something for you in return or a little behavior change here or there?" Because if there's anything at all when you're giving in that you can feel bad about later, you're nuking the relationship - you're creating scar tissue with yourself, and that will build up to the point where you wreck the relationship"

I never thought of it like that, but it makes sense. Glad I learned this now and not later.

-----

A sci-fi level biological finding, that I came across recently was a paper where a dish of biological neurons [[https://www.cell.com/neuron/fulltext/S0896-6273(22)00806-6][learned how to play pong]].

I am putting this here because one of my potential grad school rotation projects back in 2011 that I was really excited about was assaying dishes of neurons like these, which started to synchronize and form their own networks. It's nice to see a decade later that these dishes of neurons can in fact learn to do interesting things.

-----

I am a jazz bassist by training, so I like to think I know a thing or two about music. This said, I came across a concept in music that I've overlooked over the years: shifting the beat juuuust a little bit. There are two instances of this that I found last month.

The first is from a [[https://metalintheory.com/metallica-master-of-puppets/][critical analysis]] of [[https://www.youtube.com/watch?v=E0ozmU9cJDg][Master of Puppets]] by Metallica, in which the 5/8 measure of the verse has eighth notes 2 and 3 that are slightly slower combined (by 0.05 seconds) than eighth notes 4 and 5. If you want to know what I'm talking about, go to 0:55-0:56 in the YouTube video I link. That part. It gives the song a slightly different feel, that makes the tabs to the song seem like they're missing something, which is what prompted the analysis in the first place.

The second is a [[https://pudding.cool/2023/06/groove/][piece]] from a visual essay publication called The Pudding, which explores grooves that "break the rules." Scroll down to "shift" and shift the snare. The snare drum comes in slightly before the start of each measure rather than directly on the beat. It gives the snare a sound that I've heard before many times, but didn't appreciate what was going on.
