#+Title: Replace the word "value" with "beauty"
#+Author: Tyler Burns
#+Date: April 23, 2023 - April 23, 2023

[[./index.html][Home]]

-----
/Add to the beauty of existence. Picking up trash, creating art, complementing someone, alleviating poverty, inventing technology that improves life, expanding the field of what we know about reality, raising children lovingly, planting trees, sharing things of value we have learned…are all ways to add to the beauty of existence. This is inherently meaningful. The beauty of reality evolved through your action./

Daniel Schmachtenberger, /[[https://civilizationemerging.com/how-to-live-a-meaningful-life/][How to Live a Meaningful Life]]/
-----

There is a huge side of me that is strictly rational. I intellectualize things, I make models, I make predictions, I think in probabilities, I read rational blogs like LessWrong, I look at the world through the lens of economics and computer science, and so on. But on the other hand, there has always been a component that transcends that. When I saw Conway's Game of Life for the first time when I was sixteen, I wasn't thinking in terms of value added or any of that. Or for a more relatable one, the first time I met my baby nephew, there was a deep component that could not be put into words. There something much deeper to these things than pure rationality. Something sacred. Something beautiful. As I get older, there are more and more of these things that can't exactly be intellectualized, but you know it when you see it.

-----
/The Tao that is knowable is not the eternal Tao./

Lao Tzu, /Tao Te Ching/
-----

These sides of me were always separate. Two hats that I would wear, with the rational side often out-gunning this other side (leading to feelings of emptiness).For the sake of brevity, we will call that other side of me the spiritual side. Things changed when I heard a podcast between [[https://www.youtube.com/watch?v=hGRNUw559SE][Lex Fridman and philosopher Daniel Schmachtenberger]]. The latter, when talking about meaning in life, talked about "adding beauty" to the world, the way I might talk about adding value. That moment set forth a collision course between the rational side and the spiritual side of me, leading to a fascinating framework that is worth writing down.

I have been self employed for half a decade now, and for the sake of survival, I must always think about what my value is. What my value proposition is. How can I add value, especially as I change and as the world changes. So let's get rid of the word "value" and replace it with "beauty." When I say beauty, I'm not talking about shallow things, like physical attractiveness. I'm talking about everything that is difficult to put into words. Special. Sacred. Quality (if you're read Zen and the Art of Motorcycle Maintenance). Inner beauty. Tao. Oneness. God. Whatever it is for you. You know it when you see it.

So now we can start to think rationally about that. Let's start with my professional life. Where is the beauty in my work? Is it in getting data analyzed so some company can increase their profits? No. How about inspiring others to take the plunge into self employment? Yes, that checks. How about mentorship? Yes. How about developing new [[https://fs.blog/mental-models/][frameworks]] with which to make sense of the messy world? Yes, that counts. How about, as my former PI Garry Nolan used to say, getting people to see their success through you? Yes, that checks. Each of these things are correlated with "value" in that they can lead to food getting put onto the table. But think this is a much better utility function than thinking about value, which can lead to all kinds of perverse incentives and parasitic activities.

What can this way of thinking [[https://www.lesswrong.com/posts/a7n8GdKiAZRX86T5A/making-beliefs-pay-rent-in-anticipated-experiences][predict about the future]] rather than rationalize about the past (a very important question if you have a new model or framework of the world)? Well, let's look at simple questions like how much of a social media presence I should have? Right now, I post regularly to LinkedIn, staying away from other places. Now if I increased my Twitter presence, I could potentially reach more people. Added value. But this comes at the expense of my [[./scrolling_problem.html][mental health]] (I speak both from experience and from observing others who are very active on Twitter). If my mental health drops, I might still be able to add value in the sense of gaining profit by helping companies increase profit, but I won't be able to add as much beauty to the world because the "uglier" sides of me will be shining, both on and off social media. If you've seen influential people on Twitter getting outraged and posting angry things every 5 minutes, you know what I'm talking about. So this is a rational calculation incorporating the spiritual side of me as well.

What about my personal life? If we're thinking only in terms of value added, then the idea of forsaking all things family and only working to make as much money as I can, to dump into a huge savings account for the next generation, checks out. Or forsaking all things family and the huge savings account to donate everything to cancer research at the end of life. Or to simply live alone, doing nothing but cancer research 18 hours a day, sleeping in the lab, [[https://en.wikipedia.org/wiki/Karoshi][dying at my desk]]. These all sound kinda cringe, in ways that are hard to put into words, given that you can rationalize them with value-add calculations. But they are easier to think about in terms of beauty-add calculations. All the time I could spend with my family, or simply being kind for strangers, volunteering, etc, adds beauty but doesn't necessarily add value. But I don't cringe when I think about these things. They feel more "right." They don't feel "off path."

So to conclude, I have talked in previous articles about [[./purpose_driven_vs_purposeless.html][Tao]], which loosely defined means "the way." Some of that for me involves making enough money to put food on the table, and do the things that I want to do. But some of that also involves things that are non-quantifiable, like flying over the ocean to visit my mom and my sister, despite money lost, time I could otherwise spend working, etc. If we want to think in terms of [[https://en.wikipedia.org/wiki/OODA_loop][OODA loops]], "beauty" is a signal I orient toward to keep me on the right path. We need to think deeply to make sure we understand beauty when we see it (there are plenty of things that [[./the_beauty_is_truth_delusion.html][pretend to be beauty]]). But when you see it, you have to orient toward it. Now I'm combining this with the rational lens that makes up my business life, and it is serving me very well as a framework for how to move forward and what to do next. So try it in your life. Taboo the word "value" and replace it with "beauty" and see what it does for you. 

