#+Title: The most boring man in the world
#+Author: Tyler Burns
#+Date: January 3, 2025 - January 8, 2025

[[./index.html][Home]]

-----
/First rule. To be interesting you have to be interested. In life./\\

/Second rule. Interest isn't enough. You have to experience the incredible parade that's passing you by./\\

/Not as an onlooker. As a participant. Jump in./\\

Jonathan Goldsmith, actor who played "The Most Interesting Man In The World," [[https://www.reddit.com/r/IAmA/comments/50o0mx/we_meet_again_reddit_for_years_i_portrayed_the/][Reddit AMA]].
-----

At the time of writing [2025-01-03 Fri] my facebook and instagram profile pic is me with a beard posing with a Dos Equis beer like the [[https://en.wikipedia.org/wiki/The_Most_Interesting_Man_in_the_World][Most Interesting Man In The World]], an ad campaign that ran through my 20s. An example commercial is [[https://www.youtube.com/watch?v=fYdwe3ArFWA][here]]. I liked this character back then because he was a male archetype that was not centered on violence (eg. like Chuck Norris). He was centered more on a long life of competence and experience (from one of the commercials: "his beard has more experience than a lesser man's entire body"). I had a beard for a while back then, and it may or may not have been in part due to these commercials.

For a solid decade, I thought long and hard about what it meant to be interesting. Importantly, I came across a reddit [[https://www.reddit.com/r/IAmA/comments/50o0mx/we_meet_again_reddit_for_years_i_portrayed_the/][AMA]] where actor Jonathan Goldsmith, who played the role of this character in the ads (a very interesting person in real life) answered questions. In it, he says to be interesting, you have to be /interested/ in life, in a way where you truly experience it actively. There was definitely [[https://tjburns08.github.io/signal_there.html][signal]] in those words. It was not about the outputs (people thinking I'm interesting), but rather the inputs. My level of interest in life and me going out into the world and experiencing things (good or bad) is something that I can control. What people think of that is something I cannot control. So I can focus on the former.

In that spirit, I moved to Berlin after I graduated. I got married to a local. I started my own company. In essence, I started living life.

I was becoming more "experienced," something that academia can delay, but competence was another piece to the puzzle. The Most Interesting Man In The World is a fictional character who is good at pretty much everything: ice sculptures, dog sledding, surgery, rescuing a pet goldfish from a burning building, going to space, big wave surfing, to name a few things from the commercials. A quote from one of the commercials gives you the gist of it: "he once parallel parked a train".

I was always particularly interested in the competence side of being interesting. I didn't have to climb Everest or sail across the Atantic or any of that. I mainly wanted and still want to generally be skilled, and ultimately useful. My father-in-law is a good example of this. He's well-read, tends a garden, built the garage at his house himself as a teenager (before smartphones and internet), has a day job as a plumber (and is good enough that neighbors come to his door asking for help), tinkers with his old Mercedes on the weekends, can get around Berlin without GPS (it's not a simple grid like American cities), and so forth. His day-to-day is pretty routine, but he's one of the most interesting men I know.

Coming out of [[https://tjburns08.github.io/how_to_solve_problems.html][grad school]], I was a specialist in a narrow aspect of biology that was really hot at the time. But when I started my company, I realized that I had to become a bit more of a generalist, dealing with other subfields and methods within biology, international law, personal and corporate finance, marketing, sales, leadership, networking, scaling, data of various kinds, philosophy and rationality (to immunize myself against all the online business "gurus") and new technology that develops, like Generative AI, and how it changes the game. Not to mention the things specific to moving to Germany, like having to learn the [[https://tjburns08.github.io/limbic_language_learning.html][German language]] and how to [[https://tjburns08.github.io/stick_shift_mindset.html][drive stick]]. In short, I had to become much more competent than I was.

Learning all these new skills has been a long slog. I've been self employed full time since 2018 and part time since 2016. If anything, most of it has been boring and hard. There was the German lessons, the social settings where I totally get a word wrong and create an awkward situation, the failed sales calls, an entire failed business endeavor that cost me most of 2023, my first LinkedIn posts (where I post stuff relevant to my company) that were met with apathy, slogging through the US and EU finance and tax regulations (which is an absolute [[https://www.bogleheads.org/wiki/US_tax_pitfalls_for_a_US_person_living_abroad][nightmare]]), and so forth. I could go on, but you get the picture.

And this made me remember something from my work in the [[https://tjburns08.github.io/how_to_get_fit_long_term.html][fitness industry]] circa 2010, when I was a personal trainer. There was always some sort of new fad diet, or new "lose 30 pounds in 30 days" thing making the rounds. The heuristic I developed back then (and I like to think most fitness professionals have) is this: if it is boring, slow, and requires hard work and dedication, then it is probably the right path. If it is exciting, fast, extreme, and promises results with very little work, it is probably not the right path. I have noticed that this heuristic extends into my life now in many domains. The results I enjoy now have been due to a long slog of boring repetitions, of hard work and dedication.

I am good at bioinformatics because I did project after project, evenings and weekends, for years. The aforementioned business skills that keep me afloat have come from hard work and fast learning under high pressure (they say you either work 40 hours a week for someone else or 80 hours a week for yourself) [1]. I am physically fit in my late 30s only because I've been lifting consistently and eating right for 25 years, which consists of boring repetitions at the gym and a [[https://tjburns08.github.io/boring_diet.html][boring diet]].

It's a similar story for everything that I'm good at now, and I'm guessing it will be a similar story for whatever I get good at down the line (unless we get some brain helmet that downloads skills like in The Matrix). The aspects of my life that others deem interesting now (and that I myself am proud of) have come out of years of doing the boring work [2].

In short, I have realized that one of the key pieces to the puzzle of how to become interesting, particulary in the competence direction, is that you have to be willing to be boring. Yes, I travel and do fun things that I share on social media or whatever, like anyone else, but most of my day-to-day life is boring. At any given time, I am generally doing some boring slog, grinding out the "reps" in pursuit of some long-term goal, or in pursuit of playing an [[https://en.wikipedia.org/wiki/Finite_and_Infinite_Games][infinite game]] (eg. stay in shape, stay married, stay in business).

So if you want to become more interesting, take Jonathan Goldsmith's advice: be interested in life and try to experience every moment in the fullest. But also know that a lot of the "interesting" that is rooted in competence requires one to be boring. It requires one to do the long, tedious slog, and continue after others have quit (and perhaps are having more fun in the moment than you are). And that's ok.

The process is boring, and the outcome is interesting.

-----
[1] Luck and my network has played a role here too. But I also note that the luck has been rooted in hard work. The opportunities don't come to me because I exist. They come to me because I have produced and posted content that many deem valuable, on a consistent basis, for several years. And the network has come from me nurturing and developing it for well over a decade, which also has been hard work.

[2] Readers may recall that I have written a lot about the flow state, which is something that is far from boring for me. The flow state is indeed something that happens quite often with me. And it is of course something that I leverage when I'm trying to get better at something. For bioinformatics, the repetitions are at the level of the project, where some of the work is tedious and some of it is flow. In other words, the repetitions at the project level have boring and less boring components. It's not a 100% boring slog, by any means. When I used to play soccer, we would spend some amount of time doing drills (reps) and another chunk doing scrimmage (flow). When I was in jazz bands and combos earlier in life (I played electric and upright bass), there was a similar thing, where there would be a reps component (going up and down scales, etc), and then a flow component ("Ok, from the top! One, two..."). But in essence, the "boring work" is something that I have to remind myself to do. If I optimize only for the flow state, I have fun but I do not necessarily progress. So I force myself to do the boring work, and the flow state is a reward that happens from time to time.
