#+Title: If the doomers are right, then be a giver
#+Author: Tyler Burns
#+Date: August 23, 2025 - August 23, 2025

[[./index.html][Home]]

-----

/Of the six men who never reached the ship, he thinks two perished of pure fright in that accursed instant./

H.P. Lovecraft, /The Call of Cthulhu/

-----

* The doomers have a point
Since the middle of 2023, I have been doing a bit of biosecurity consulting. The way this works is I spend time looking into existential risks that involve the life sciences. This can range from pandemics to biowarfare. Of course, AI is part of this too. A lot of this can be pretty depressing if not horrifying. You can see it take a toll on people, too. When Eliezer Yudkowsky, the face of AI-we're-gonna-die-ism, was asked on Lex Fridman what his advice was for young people (careers, etc), he said something to the effect of "enjoy your life while you still can."

Furthermore, my intern told me of a futurism class she took as part of her humanities requirement where the professor basically convinced the class that they are screwed and there is nothing they can do about it. Keep in mind these were bright young Stanford students, being told to not even bother with the problems facing us. I see this as a disservice to humanity.

But on the other hand, if you look at the more doomery arguments out there, you do see quite a lot of very big concerns. Pandemics, fragility in being globally interconnected (remember COVID?), AI leading to mass unemployment among many other things, rising housing prices while wages remain the same, civil unrest, authoritarianism, war (the nukes have not gone away), and so forth. Not to mention the [[https://en.wikipedia.org/wiki/Polycrisis][combinatorics of it all]]. So...things could get pretty dicey down the line.

But does that mean that we should just give up and spend the rest of our lives scrolling, drinking, and whatever our vices are? Should I tell my intern to give up and get some 9-5 somewhere rather than pursuing a PhD? (scroll to the end for the answer).

In short, what seems to be lacking in all these doomer conversations is what to do if the doomers are correct. If I actually knew with 100% chance that there was going to be a decline and collapse of the entire world in the next 5-10 years, what would I do with myself? What would I tell my intern to do?

* Make eudaimonia great again
This is a very hard question, but I think a lot of it can boil down to a very old word that is not exactly in the English lexicon: [[https://en.wikipedia.org/wiki/Eudaimonia][eudaimonia]]. Aristotle talks about this in his book /Nicomachean Ethics/. Eudaimonia is not pleasure. It is flourishing. But not just of the self, but also the flourishing of the community around you. The flourishing takes place by everyone doing virtuous and meaningful activity, which allows everyone to flourish together.

I run a company, and I have been going by the saying "produce more than you consume." The idea is that production of things that help people, that others can consume to be helped is a good thing, and I will be compensated for it. This is perfectly fine, but I have recently looked at some critiques of modernism and the so-called "cult of the self" which has led me to re-evaluate this idea.

It is not wrong by any means, but in light of Aristotle and eudaimonia, I have refined it recently to be: "give more than you take." This is subtle, but it takes production and qualifies it as a subset of giving: if what you produce allows you to give, then do it. But there is more to giving than just production. I help my intern every day. I hold office hours for the single-cell community to give them [[./die_with_zero.html][free advice]]. That is giving. I don't necessarily "produce" to help them out.

If and when I do produce, I produce content and code that helps people out. On the contrary, I could also produce low-quality [[./we_choose_to_think.html][ChatGPT generated LinkedIn posts]], but that would not help people.

Giving is a hallmark of eudaimonia. It is related to Aristotle's virtue of liberality: giving the right amount to the right people at the right times for the right reasons, and finding the proper balance between that and taking (it's often a mean between extremes in Aristotelian ethics). Furthermore, giving in a nontransactional manner is necessary for the highest and rarest form of friendship, the friendship of virtue, something Aristotle values very highly for living a eudaimonaic life. Giving is not nearly all of what eudaimonia is (and I would encourage everyone to read at least some of /Nicomachean Ethics/ so you can get into Aristotle's head a bit), but for the sake of this article, this is what we will focus on.

It's not about producing and then allocating as much capital as possible. Rather, it's about putting giving front and center at all times. If down the line I do well and sell a company for a large exit, my plan is to take that money and use at least some of it to build a research institute or something related to that. Not because I'll get ROI, but because "give more than you take" is a core value.

How do I know that this matters? Aside from hearing it a lot of places, and Aristotle writing an entire book about it, I also [[./signal_there.html][feel it in my bones]]. When I look at everything I've done since I started graduate school, the things I am most proud of are the times when I was able to teach, mentor, or give any other kind of help. Donating is nice too, but for whatever reason, I like being there on the ground and actually helping in real time. Of course, learning and developing skills help me help more.

Running a company and allocating capital allows me to take on more interns and employees, which allows me to help more. The subtle shift is from profit-first to giving-first (while keeping profit in mind). So just as the Zen Koans use words to point to the [[./fear_the_unword.html][unwordable]], and just as Socrates used questions to point to the [[./its_more_complicated_than_that.html][unknowable]], here we can use capitalism to point to and pay homage to the uncapitalisable.

And I think herein lies the answer at least for my life. If 5-10 years from now (time of writing is [2025-08-23 Sat]) we are in complete chaos, between AI killer drones, mass unemployment, civil war, foreign wars, and whatever else, the only thing we can really do is try to give as much as we can to the people who matter in our life, and the broader community if that is still possible.

In a world like that, it might be that we simply protect our family best we can (which could be as simple as giving your dog a good life). And that might be enough. So if I take the doomer frame for a minute and someone asks me advice for young people, I have my answer.
* Advice for young people
The advice here, which captures the heart of what I'm trying to say, is the same advice I give my intern. She wants to get a PhD. Should she pursue a PhD, or stop now because everything is going to garbage? The answer, assuming funding is taken care of: pursue a PhD if you are doing it for you (and not just for the status or whatever), and if you think you can use it to help others down the line. Even if AI renders it worthless by 2030, you'll learn how to think critically and exhaustively for yourself, build a number of skills, and you'll develop a robust network of scientists and doctors, all of which you can use to help people down the line. All of which will give you tools for eudaimonia.

Whatever it is you're looking to do, if it allows you to pursue eudaimonia, then do it. And do it as well as you can. Because if we're all going to die, then we might as well die flourishing together.
