#+Title: Enjoyment arbitrage
#+Author: Tyler Burns
#+Date: May 23, 2023 - May 23, 2023

-----
/When people see some things as beautiful,/\\
/other things become ugly./\\
/When people see some things as good,/\\
/other things become bad./\\

Lao Tzu, /[[https://www.organism.earth/library/document/tao-te-ching][Tao Te Ching]]/
-----

** Code-philic and code-phobic

After I got my PhD in 2017, I worked half time as a bioinformatician and half time as a bioinformatics consultant. At the time, I was thinking of my value to the work place in terms of my specialized skills and knowledge. Yes, this is a huge piece of it, but there is something else going on here too.

Pretty early on, I started teaching the biologists in the lab and adjacent labs (where I met my wife) how to do what I do. The idea was simple: if people can do what I do now, then I can focus on harder and more interesting problems, as opposed to solving the same problems over and over. I realized very quickly that most biologists are fully capable of learning how to do what I do. It is hard work, but not impossible if they committed themselves for a few years. But the key thing I realized was that there are simply a lot of people who /don't want to do what I do./

I was on a data analysis discussion panel at a local conference in 2018 along with bioinformatics heavyweight Yvan Saeys, and he defined three categories in terms of the spectrum of willingness to do bioinformatics:

There are people who really enjoy doing bioinformatics analysis and the relevant software engineering, and would love to do it full time and go really deep into it. For shorthand, we'll call these people code-philic. They have to develop a new tool because it's a new type of data and there are no libraries for whatever it is? Great. They see an error message that leads to a de-bugging rabbit hole? Awesome. These people exist. I know this because I am one of them.

Then there are people who are code-tolerant. They are willing to run the high-level commands and scripts in R or python, relevant to whatever they need to do, for the sake of getting the analysis done, but that is where there interest ends. Generally, these are biologists who simply want their data in an analyzed format so they can deeply contemplate the biology of it all, design the next experiment, read relevant papers, and so on. My wife is like this. She's perfectly competent and comfortable at this level, but she cares about the biology first and foremost, so as soon as there is an error message or a clear need for something beyond the given tools, she finds me.

Then there are people who are completely code-phobic. They don't want a thing to do with a single line with code, use of the command line, and anything that is not clicky user interfaces, like Prism and Excel. I know a guy from my thesis lab, who went through great lengths to hack together a complex heatmap without using a single line of code. It took him several hours. He was very proud of it. I was impressed by the sheer ingenuity that went into it. But again, it would have been a few lines of code max to get the same result. The point is these people exist, and they are very common.

** Actually do what you love

All of this said, I want to revitalize the adage "do what you love" in a new light. Of course, we learn at an early age that what you love won't necessarily put food on the table. Dreams of playing professional trombone turn into law school or whatever else. But what I'm trying to point to here is the idea that there are things that people enjoy doing and things that people don't enjoy doing, and one person's heaven is another person's hell.

So I'm going to call this enjoyment arbitrage. The idea is you leave your bubble, where people enjoy the thing you do, go to a world of people who really don't enjoy that thing, and offer to do that thing. My bioinformatics client base are typically groups of people who are code tolerant or code phobic, in a workplace where there are a lack of code-philic people. This is in contrast to my nerdy circles of people just like me.

I am going to guess that the enjoyment arbitrage landscape is going to be in constant flux, and needs to be closely monitored. Coding in general has gotten easier and more accessable, leading to the possibility of more people enjoying it. My aunt likes to talk about how her computer science class in college was using [[https://en.wikipedia.org/wiki/Computer_programming_in_the_punched_card_era][punched cards]], where errors were much harder to find, and you couldn't just rapidly try a bunch of things. Even after that, there was a time when Stack Overflow didn't exist, and you couldn't just type your error messages into Google and figure out if others have experienced the same thing. And now I'm going to be able to rant about how in my day, we couldn't just get a large language model to generate code for us, or clearly explain error messages, and that kind of thing.

Furthermore, there is an enjoyment arbitrage landscape within code-philic circles too. I was on a project once in 2019 or so, where I was turning some scripts into a software package. My colleagues were fully capable of doing this many times over, but through a combination of them not having time and me actually being more interested in this particular software development space than them, I ended up being a good fit for the job.

So regardless of what happens, there are going to be things that I enjoy doing that others don't. As the work landscape changes, and as I change, aside from the standard arbitrage that we think about (skills, information, etc), I'm going to always have enjoyment arbitrage in mind too. I'm constantly going to be looking for things that I enjoy that others don't and simply focusing there.

Do what you love (and others detest), and the money will follow.
