#+Title: Fear of the un-word is the beginning of wisdom
#+Author: Tyler Burns
#+Date: November 11, 2023 - January 20, 2024

[[./index.html][Home]]

-----

/Auugh!!!...[gasp]...[heavy breathing sounds]...[dramatic music]/\\

Neo, when he [[https://www.youtube.com/watch?v=gCZBY7a8kqE][wakes up out of the Matrix]].

-----

** The un-word for things you can't put into words

There was an episode of Dr. Who I was watching a few years ago, that involved some sort of parallel universe time travel thing. Dr. Who of course had invented a way to do that. His companion wants to know how it works. The following dialogue happens (I'm paraphrasing):

/Companion: How does it work?/\\
/Dr. Who: So you know how time slows down when you get near a black hole due to gravity?/\\
/Companion: Yes./\\
/Dr. Who: Ok, well it's NOTHING like that. At all. But that will have to do for now./\\

I remember awaiting some sort of fun sci-fi [[https://gwern.net/doc/philosophy/epistemology/2012-sistery-tryingtoseethrough.html][insight]] from Dr. Who about gravity and black holes and quantum mechanics, only to have that dashed because how it works is light years beyond anything that humans of our era can comprehend. Which itself was an insight.

This is a special instance of a concept called [[https://en.wikipedia.org/wiki/Apophatic_theology][via negativa]] that we see in religion, that comes after one stops thinking of God as a bearded man in the clouds. It goes something like this:

/Is God a bearded man?/\\
/No./\\

/Is God a spirit?/\\
/No./\\

/Is God love?/\\
/No./\\

/Is God...like...I dunno...some sort of cosmic consciousness thing?/\\
/No./\\

And so on. It's by no means randomly generated questions. It only works if you get more and more sophisticated with each one. You do that long enough and it moves you into a sort of aporia where you're now thinking of all that which is beyond anything you've thought and felt before. And that's still not God, but you're on the right track. In other words, you're trying to understand what something is by understanding what it is not, and along the way realizing that it is far beyond the many things that it is not.

I touched upon this kind of thing a story of my intellectual journey as a biologist, where I realized at every new step that "[[https://tjburns08.github.io/its_more_complicated_than_that.html][it's more complicated than that]]." Same idea. You come across a new thing or new insight in the direction of trying to understand a thing. You realized that it's more complicated than that. That one answer leads to 10 other questions. And so on forever. But that doesn't lead to nihilism. Quite the opposite. It's addictive. You can study the same thing for your entire career and still feel like you've just gotten started.

Ok, so one way to compress all of this is through what author [[https://en.wikipedia.org/wiki/The_Matter_with_Things][Iain McGilchrist]] calls an un-word. It's literally a word that points to a thing that cannot be put into words. The most direct example of this is Tao, something I have written about [[https://tjburns08.github.io/pursuit_of_health.html][before]]. The first line of the Tao Te Ching goes:

/The Tao that can be told is not the eternal Tao./
/The name that can be named is not the eternal name./

The rest of the book talks about how to align yourself with Tao, and points in the direction of things that Tao is and what it does (eg. analogies to water), but cautions against the idea that you'll wake up one day and finally know what Tao is. Because whatever it is, Tao is beyond that.

For those who approach God in the same light also use God as an un-word. Same thing. If you're Christian, you can look at Jesus as a human form that point you in the direction of how to conduct yourself to live a good life (the standard question "what would Jesus do"), but there is this father, son, holy spirit trinity thing that is way more vast and complicated that any human brain would ever be able to comprehend.

The main point here is that I often have to remind myself that there is way more to whatever it is I'm looking at or thinking about than I can possibly imagine. It's easy to get complacent and think that I know a thing. It's particuarly dangerous when it's something outside my field, where the [[https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect][Dunning-Krüger effect]] will make me think I know it better than I actually do. The PhD in biology beat that out of me...in biology. But it's still a struggle to remember that whatever it is that I think I know, I'll feel like it's a complete mystery after 5 years of 60+ hours a week of study.

** The religious texts in the light of the un-word

Now if we interpret the religious texts in the light of the un-word, things get interesting. I grew up Christian so we'll use that simply because that's where I'm more literate, but you can do this with any religious/spiritual text.

One of the big concepts in Christianity is the fear of God. King Solomon (prominent sage in the Bible) says that "fear of God is the beginning of wisdom." So what does it mean when fear of the un-word is the beginning of wisdom? I think it has something to do with all the forces beyond me that can lead to all kinds of bad stuff at any given moment, regardless of whether I'm a good or a bad person.

I know a professor named John Ohlfest from University of Minnesota who did brain cancer research. I was considering working with him for my PhD thesis, and I got the honor of interviewing with him accordingly. We both had lost loved ones to glioblastoma multiforme early on: I lost my father and he lost his grandmother. He had dedicated his entire life to brain cancer research. "Just as the Samurai sleeps with his sword" he told me. He was expecting me to do the same if I joined his lab, which I was willing to do, to avenge the death of my father. This was a big part of my identity. You know what happened to him? Shortly after I started my PhD thesis over at Stanford in cancer biology, he got diagnosed with cancer and [[https://med.umn.edu/news/renowned-brain-tumor-pioneer-john-ohlfest-phd-dies-after-his-own-battle-cancer][died]]. He was 35. What the hell am I supposed to make of that?

This is not the only story I know of that features terrible things happening to good people. It seems to be a common trope, and perhaps why the Book of Job is so popular. For those of you who are not Bible-literate, the Book of Job is about terrible things happening to the world's most faithful servant of God. It's a long story, but you can get a [[https://www.youtube.com/watch?v=xQwnH8th_fs][video summary here]]. Long story short, God ends up testing his faith by making all kinds of bad things happen to him. The death of family members and livestock, the burning of his property, and sickness that leaves the otherwise healthy strong handsome man hunched over, emaciated, and covered in boils. Job demands to speak to God, accusing him of being incompetent at running the universe. God shows up. He takes Job on a [[https://biblehub.com/niv/job/38.htm][cosmic tour]] (or gives him a cosmic lecture, however you want to interpret it) where he gets a glancing blow of the ineffible vastness that is God and the universe. Job realizes that in short, it's more complicated than that. Job returns. He gets it.

So along with the idea that "it's more complicated than that," the book of Job has a twist being that the complexity that we do not comprehend could lead to all kinds of suffering to us and our loved ones. That the un-word can lead to pleasure, but it can also lead to pain. That's kindof a scary thing. That keeps me up at night, as well as jolts me out of bed in the morning. Because I know that both in the widest stretches of the cosmos and the tiniest corners of my world, even the corners that have been most observed, lies depth, complexity and vastness that can lead to all kinds of things.

[[https://www.meaningcrisis.co/ep-34-awakening-from-the-meaning-crisis-sacredness-horror-music-and-the-symbol/][John Vervaeke]] likes to talk about how awe and horror are two sides of the same coin. And the fear of the un-word is basically this: a sense of awe mixed in with a sense of horror. Because they are one and the same. To admit ignorance and embrace the unknown, which allows you to really feel this in your bones...perhaps that is the beginning of wisdom.
