#+Title: How to get fit in 20 years
#+Author: Tyler J Burns, PhD
#+Date: March 5, 2023 - March 5, 2023

[[./index.html][Home]]

-----
/First, take the positive approach, and tell him how much you love him and want him to be around. Don't try the negative approach and tell him he eats junk and needs to fix it./\\

/Just remind your dad that there is nothing more important than his health. Everything comes from health. Work, money, family, whatever he enjoys. He can't have any of that without his health./\\

/The only time to go negative: if he says there isn't enough time, tell him that's just terrible math. Any minutes or hours he subtracts from his day right now for health and fitness is multiplied in the months and years he would add to his life. That's fitness math./\\

/Tell your dad the first step might seem impossible, but like Mandela said, "It always seems impossible... until it's done." And once he starts, a body that is in motion tends to stay in motion./\\

Arnold Schwarzenegger, [[https://www.reddit.com/r/Fitness/comments/1brg0z/im_back_ama_about_fitness/][Reddit AMA]], giving motivational advice on behalf of the asker's overweight and hypertensive father.
-----

* Losing too many pounds in too few days
I remember some time around 2010 when I was working as a personal trainer, I came across a few home workout videos that promised results (some number of pounds lost, etc) on the scale of 1-2 months. One of my clients let me borrow the video series she had so I could see what this was all about. I'm purposely not telling you what video series it was because perhaps it has evolved over the years into something different. But what I saw was essentially going from zero to a pretty difficult workout system, especially for someone who is not an avid gym-goer.

We all have seen this or experienced this stereotype by now. A very difficult weight loss or fitness goal, or promise (lose 30 pounds in 60 days, etc) is set. If the goal is attained, the weight comes right back as soon as the workouts and strict dieting ends, and the desire to do any sort of workout turns into burnout.

The purpose of this article is to articulate the opposite perspective, as it has worked for me over the past two decades. I've talked about this to many people when being asked about my health and fitness habits, so I figured it's time to write it down. To understand my perspective, ask yourself how you would approach your fitness related goals (eg. the combined set of lose 20 pounds, run a marathon, win a Jiu-Jitsu match) if you had to pace it to 20 years.
* Slow-tracking your fitness goals
I started lifting weights on February 22, 1999. I was in middle school. This doesn't mean I was doing an hour of deadlifts with as much weight as possible. It was actually the opposite of that. My uncle John (very much a father figure at the time) brought over some dumbbells and taught me some basic exercises and principles, emphasizing that I should not overdo it.

What was my first workout?
dumbbell curl: 1 set, 5lb, 5 reps.
push-ups: 5, 4, 3, 2, 1.
overhead dumbbell tricep extension: 1 set, 5lb, 5 reps.

The whole thing took maybe 5 minutes. What was my second workout two days later?
dumbbell curl: 1 set, 5lb, 6 reps.
push-ups: 6, 5, 4, 3, 2, 1.
overhead dumbbell tricep extension: 1 set, 5lb, 6 reps.

You get the picture. Every other day. When I got to 10 reps, I'd go up 5 pounds and go back to 5 reps. Obviously I hit plateaus after a while, and there are ways around that. Obviously I added exercises as my form got better and my habits solidified. 5 minutes became 10 minutes. 10 minutes became 20 minutes. And so on.

At some point, I got a home gym set from a local sporting goods store that allowed me to do leg curls, leg extension, bench press, and squats in the garage. At some point, Uncle John helped me set up a pull-up bar and a dip station.

In the summers, I would get a gym membership at the local gym (CalFit). In the school year, I took PE XL when I could, which was the weight training PE class for high school, which allowed me to do my workouts at school so I could start studying immediately after coming home.

Through college, I had my routine set up and solidified, and it was just a matter of riding the momentum. I ended up doing my work-study job as a weight room manager at the school gym. Through this, I joined a school-specific personal training certification class and got a job as a personal trainer at that school gym. This transitioned to a full-time personal trainer job at 24 Hour Fitness, which put food on the table during the 2008 recession that I graduated into.

The key point here is that this was a really really slow build. The other aspects of health and wellness, like nutrition, also developed at the same pace. Glancing here and there at the nutrition facts of things I was eating and drinking, to reading up on nutrition here and there, to studying basic nutrition for the personal training certification exam. None of this ever felt like I was burning myself out.
* Optimizing for a healthy and active lifestyle
The gym is not everyone's jam. Same for working out alone. Perhaps you like ballet. Perhaps you like hiking. Perhaps you like martial arts. That's fine. Then do that.

What I used to tell my clients was that they get an hour with me, but then they have to manage the other 23 hours. One hour of a very intense workout means nothing if the other 23 hours are spent eating unhealthy food, or if that very intense workout is going to lead to burnout in the long term.

How do you get fit in 20 years? One huge piece of the puzzle is to have a healthy and active lifestyle. What does that look like? Develop some physical hobbies if you don't have them already. Try new sports and outdoor activities. Join meetup groups for these things. Bike to and from work if you can. Take the stairs instead of the elevator. If you have to drive, park your car father away. Go for hikes with friends rather than sitting down for drinks. Get a standing desk (I am standing as I type this). Learn some new healthy recipes. The key thing here, and I have to remind myself of this all the time: *you don't have to go hard for any of these*. You don't have to train to become a competitive kickboxer just because you're doing a kickboxing class. Again, you're slow-tracking over 20 years, and you're doing this for your health. 

* Recommendations and conclusions
I am aware that there are plenty of other perspectives here. Plenty of other people who have become healthy with much more intense goals with much more rigid timelines. Plenty of other people who train much harder than me. The main data point I can share about this very gradual way of approaching health and wellness is that I've never needed any external prodding to get me to go to the gym or eat right. I've never needed to make commitments to friends, have a schedule to meet a friend at the gym at 8am sharp, or anything else like that. My hypothesis is that a gradual approach leads to more self motivation, less internal resistance, and better habit formation than a zero-to-maximum-intensity approach. You're slowly building a system that works for you.

So how do you get fit in 20 years?
- If you have fitness goals, slow track them. Lose 10 pounds or bench press your bodyweight in a year, rather than a month. 
- Develop physical (non-sedentary) hobbies, slowly. Try new things. Ease into them. Make physically active friends in the process.
- Get help. My uncle got me started, and I've had personal trainers and physical therapists guide me on and off over the years. As independent and experienced as I am, I still can't go it alone. 
- Relax. You're not doing this for a team. Or for social media. Or for helicopter parents. You're doing this for an older version of yourself. 

It is said that we overestimate what we can do in a day and underestimate what we can do in a year. If you're doing this right, none of it will feel like much. You'll leave the gym with the thought that you could probably stay and do more. You'll feel like you could probably do 6 practices of a new sport a week rather than 2. To that I say that the first mile of a marathon doesn't feel like much. You run slower than you could to save energy for mile 20. Pace yourself. Your future self will thank you. 




