#+Title: How I curate content
#+Author: Tyler J Burns
#+Date: March 30, 2023 - March 30, 2023


* We should all be content curators
I haven written extensively about the problem of [[./scrolling_problem.html][infinite scrolling]] as a means of getting our information. At the time of writing [2023-03-30 Thu] there is a gaping hole in active discussion around content curation. You can find [[https://news.ycombinator.com/item?id=8806950][discussion threads]] and [[https://gwern.net/about][articles]] about how individuals do it. You can also find bloggers who post their [[https://astralcodexten.substack.com/p/links-for-march-2023][favorite links]], over some time interval, for example on a monthly basis. There is also no shortage of systems that allow you to curate content, some of which you have to buy, and some of which come built into the source of the [[https://help.twitter.com/en/using-twitter/twitter-lists][feed]].

All of this said, I think these discussions should be much more front and center than they currently are. Most people in my circles have to keep up with the news, a handful of social media accounts, and specific to my circles, the scientific literature, conferences, and talks. We need a much bigger discussion about how to curate content as our relationship with the internet evolves (which seems to result in more content in more channels). What I'll do here is share how I curate my feeds, in hopes that it at least sparks some ideas and discussion to get the ball rolling elsewhere.

* First pass
** Personal journal
I write what's on my mind in a typed personal journal that I have kept since the late 2000s. This is typically messy and unstructured, but it serves as a data dump for whatever is on my mind. This does a good job at putting my internal subjective state into words, which is increasingly valuable to my future self as I get older. 

My journal is in Emacs org mode, after being in Microsoft Word for over a decade. There were enough words that I had written, that it became too overwhelming for Word to even load efficiently, and for me to look through for that matter. Org mode is plain text that allows for collapsible bullet points. Accordingly, I can have the year, month, and day as collapsible bullet points that allow me to jump to any entry from any time point on the scale of decades.

However, looking back at old stuff I've done, what is particularly interesting is diagrams and pictures that I have drawn, especially the rough, free-hand ones (see next sections). As I've hinted, what is currently missing is merging this with my free-hand journaling. Luckily, org mode is like a bucket of legos, in that it takes a while to build up what you want, but then it is infinitely extensible. So there is a solution waiting to be built.
** Paper notebooks
I have always been a prolific pen-and-paper note taker. In the late 2000s, I had a [[https://en.wikipedia.org/wiki/PalmPilot][palm pilot]] that had a little stylus. It was just big enough that I could use it as a tiny notebook to scribble things on. Then the iPhone, and smartphones in general, took over the world. It's a big shame that the stylus didn't remain a thing. It would have been great to have my iPhone simply be a palm pilot with expanded functionality.

So I keep a thin pen paper notebook wherever I go to scribble things down. I typically use graph paper (grids). If I try to get notebook sets and have different notebooks for different things, I find that I've over-engineered the setup and it doesn't adapt to my changing needs. Also, over time, it gets difficult to search these notebooks, so I use them mainly as a first pass.
** iPad note taking
Finally, the iPad was able to get a stylus, becoming a larger version of the palm pilot that I was using. I use GoodNotes to take notes, but I'm not attached. It just gets the job done. I have very broad categories of notebooks, and I mainly just scribble into one called "scratch." It's very productive for me to always have the iPad by my side whatever I'm doing so I can scribble ideas (especially pictures, diagrams, and mind maps). The more I do this, the more I can be in the moment when I'm away from the computer, because whatever is in my head is out on paper.
** RSS for news, blogs, pre-prints
I recently discovered RSS feeds after spending some time [[https://medium.com/@tjburns_72591/using-and-mining-pre-prints-to-stay-ahead-of-your-field-with-the-help-of-twitter-50d5bdc528de][pulling twitter content into tables]] to store and organize it, and make the infinite feeds finite. I realized that I was essentially reinventing the [[https://en.wikipedia.org/wiki/RSS][RSS feed]], an older way of curating content that got pushed out by social media in the early 2010s, with the death of Google Reader being a huge blow to the RSS community.

There are many feed reader options, but I use NetNewsWire (which I'm not attached to) in order to go through my feeds, which include news sites, blogs, and pre-prints. I note that things are moving so fast across the domains I'm interested in that I increasingly rely on blogs and pre-prints to stay ahead. Once a scientific finding is actually peer-reviewed and published, it's already old news in my domain.
** Twitter for AI news
I don't like Twitter very much, but given that I can pull content off of Twitter into excel as I please, I can now utilize it without getting sucked in. I'll note that this is by no means perfect, but I have much more control over Twitter than I used to.

What do I use Twitter for? Similar to RSS feeds, you can get your news (AP, New York Times, Hacker News etc all tweet articles as they come out) and [[https://tjburns08.github.io/biorxiv_medrxiv_history.html][pre-prints]] (BiorXiv and MedrXiv both tweet every pre-print that gets uploaded to the servers). The cool thing here is if you pull the tweets into tables, you can sort by "likes" or "re-tweets" to get a feel for what tweets are deemed more significant. 

But most importantly these days [2023-03-30 Thu] I use Twitter to keep up with the field of AI. There are a good handful of users who are spending their time tinkering and [[http://www.catb.org/~esr/faqs/hacker-howto.html][hacking]] with the latest tools (image generation, text generation, etc), and posting their findings to Twitter. Things like realizing that Bing Chat can grok chess. The major news media outlets don't help me (except [[https://news.ycombinator.com/news][Hacker News]], but that's more of a tech content aggregator). YouTube has good content, but it's usually a few weeks behind (which in the case of AI is years of content in any other domain). So I am forced to use Twitter regularly, and forced to be very specific on how to do it, so I don't get stuck in the infinite scrolling loop.
* Second pass
** Evernote
I've used Evernote on and off through the years (back to 2008 or so). I ran into the problem where I would make my set of notebooks and over-engineer the setup, get frustrated, and stop using it. Recently, I started using it again because I finally came up with a strategy that works for me.

I make heavy use of tags. I take content from my RSS or Twitter mainly, but anything interesting I have come across, and place excerpts, links, and pictures into a simple note. I then tag the note with things like AI, art, or economics. I can look up the tags later. I can search Evernote for things I know are in there but have forgotten where. Importantly, I don't have to worry about what folder has what notebook that has what note.

Evernote is accessible by phone and I can make notes accordingly, but I resist the urge to use my phone for this purpose, because I am trying to be more in the moment when I am away from my computer. Call me old-school, but I want to separate my digital world from my physical world.
** Org mode
Aside from my journal entries, I use org mode mainly to handle projects I'm working on, track my goals, track my values, handle things like reading lists and my book reviews, and handle various other aspects of my life. 

Think of it as a high-level interface to everything I'm up to at any given time. I'm going to write a more in-depth article about this at some point, but until then, go [[https://orgmode.org/worg/][here]] so you can get a feel for the level of obsession that the org mode community has over this one tool. Again, it's a bucket of legos. Over time, people have built some amazing things with it. It's specifically for people who like to tinker. If you want the org mode experience but don't like to tinker and you want something that works out of the box, or you run an organization that requires everyone to sync up very fast all the time, then I would suggest that you use something like Notion.

But if Notion is a car with automatic transmission and parallel park assist, org mode is a manual without hill start assist. And as the world becomes automatic everything, I'm going to cling to the Zen of [[https://tjburns08.github.io/stick_shift_mindset.html][driving stick]] as long as I possibly can.
* Third pass: public
** My website
As my journal started to approach one million words, I realized that perhaps I should refine some of my writings and make them public. Also, being self employed requires me to be a bit louder on the internet. My aunt told me to "[[https://tjburns08.github.io/just_paint.html][just paint]]" and that kicked off the website. As the website grows and I grow, I revise my content. Sometimes I realize I was wrong about something. When thinking about explainable AI for example, I realized that I was anthropomorphizing large language models a bit too much, especially after ChatGPT was rolled out. I updated my [[./xai_and_us.html][article]] with this new information in mind. If all my content was exclusively being posted to external platforms (eg. Medium), then it would be much harder to "grow" the articles.

Content from the first and the second passes of my content curation strategy ultimately turn into articles, markdowns, and anything else for my website. The website itself is built in org mode, which makes it both adaptable and long-term, as it is simple, static, and doesn't depend on things like WordPress. If I get sick of typing at some point and I'd rather have my articles be full of free-hand sketches, diagrams, and mind maps, then I can easily extend org mode to handle that.
** Social media
The content I post is usually related to the articles I write on my website or the projects that I'm working on. In sum, because I am not stuck in the "publish or perish" paradigm anymore, I build and research in public. Any new findings I have for any of my projects immediately become [[https://www.linkedin.com/posts/tylerjburns_run-t-sne-and-umap-on-cytof-data-100-times-activity-7029143066804420609-UsDZ?utm_source=share&utm_medium=member_desktop][social media posts]]. This in turn helps let people know what I do, which allows me to find new clients and collaborators.

I typically post to LinkedIn over Twitter. This is both for the sake of my mental health and because my work is typically B2B, and my potential clients are on LinkedIn more than they are on Twitter (which seems to have more of an academic bent relative to my domain).

I am interested in posting some of my stuff to places like Reddit, HackerNews, and LessWrong, but I don't think I would have the time to engage with these communities and build a following as much as I'd want to. So for now I'm just focusing on building as much of a following as I can on LinkedIn.
* Conclusion
My content curation strategy is growing and adapting to the times. As large language models become more prominent, and a larger chunk of the internet becomes machine generated, I know that my content curation strategy is going to change. We all know what can happen if we don't have control of our feeds. This was very well explained in [[https://en.wikipedia.org/wiki/The_Social_Dilemma][The Social Dilemma]]. Perhaps if we were actively discussing how to curate content as social media started to replace RSS in the early 2010s, then some of the effects observed in the later 2010s would have been mitigated. Perhaps we wouldn't be so politically divided right now. So my hope is we actively discuss content and content curation moving forward, so we can perhaps do a better job both with controlling our feeds and anticipating techno-social problems that will emerge as the landscape of the internet and the digital world changes. 
