#+Title: I saw the northern lights
#+Author: Tyler Burns
#+Date: May 24, 2024 - May 24, 2024

[[./index.html][Home]]

-----
/Syrio Forel: My eyes shouted the truth. You were not seeing./\\
/Arya Stark: I was so. I watched, but you.../\\
/Syrio Forel: Watching is not seeing, dead girl. The seeing, the true seeing, that is the heart of swordplay./\\

[[https://en.wikipedia.org/wiki/Game_of_Thrones][Game of Thrones]], Season 1 Episode 8 "The Pointy End." Transcript [[https://genius.com/Game-of-thrones-the-pointy-end-annotated][here]].
-----

At the time of writing [2024-05-24 Fri] people are talking about the northern lights a bit more than usual due to a geomagnetic storm that took place recently, on May 10, 2024. It was the strongest at least since one that hit in 2003, where I remember seeing a reddish glow near the northern horizon one evening, but it was difficult to tell whether that was it, or the city lights. So I never counted that is having legit seen the northern lights.

During the recent storm, I actually didn't see them. I remember looking up at the sky coming back from a barbecue late in the evening, but if they were visible from Berlin (which they were), the light pollution was a bit too much for us to see them clearly. So this isn't an article about seeing the northern lights during the recent geomagnetic storm. It's actually about seeing them in 2019 in Iceland.

My wife and I wanted to see the northern lights, so we booked a trip to Reykjavik, a four hour flight from Berlin. At the time there was an airline called WOW Air that offered really good service for its price (which is perhaps one reason why they went bankrupt). Anyway, we were advised that if we really wanted to see the aurora, we should get outside of town. Even tiny little Reykjavik had light pollution. So we booked a "northern lights shuttle" that took us way outside of town into the hills, to a particularly dark spot where we would see what we see. I used to think that the auroras  would always be there, visible from anywhere in the Arctic, every night. It turns out that they're very hit or miss. We got lucky in that when we got on that shuttle, they "turned on" and were already visible from the windows, something that the tour guides said rarely happens. So we were in for a treat.

We got out of the shuttle and looked up. I'll never forget what I saw. What the pictures don't fully capture is just how dynamic they are. A patch of aurora will just show up out of the blue, in a few seconds. Then it will move around and change shape. Sometimes it's a little independent patch. Sometimes it's a big long band. Mainly they are green. Sometimes they are other colors. We saw a little bit of red here and there. They are not as dramatic as the long exposure images show, but they are still pretty gosh darn dramatic compared to looking at the darkness of a normal night sky, especially from a major city like Berlin. We had the northern lights and a gajillion stars behind it that I otherwise would never see. So yes, I saw the northern lights. But that's not the point of this article.

The point of this article is everybody else. The northern lights shuttle had about 50 people in it. My wife and I spent the evening staring at the northern lights. Sometimes they were sparse. Sometimes they would be all over the place. During the transitions from sparse to all-over-the-place, we would look up, say "whoaaa," talk about deep stuff...you know, the usual. But during these transition moments you'd hear something else. The loud sound of rustling, metal hitting metal, adjusting, and so forth. The remaining people all had expensive cameras and tripods and all of that. And they were there to take photos and pose with the aurora in the background. They were all looking through their cameras, posing in different places, adjusting their camers, things of that nature, and then would take a break soon as the northern lights dimmed.

In essense, my wife and I actually saw the northern lights that night. Nobody else did. Everyone else saw them enhanced through their cameras. We enjoyed the aurora dancing above us. Everyone else was working like it was their job. We stared at the dancing pathches of charged particles as they changed shape, moved around, appeared and disappeared. Everyone else stared at their cameras. I can still see the images in my head. We were able to deeply contemplate what was before us. We took the whole scene in. The sight to behold. The freezing arctic cold biting through my Berlin winter clothes. The mountanous landscape around us dimly illuminated by the lights. Sharing that moment with my wife. None of this can be captured in a photo.

So no...I don't have a social media photo of me and my wife with the northern lights behind us. I don't have a timelapse video of the whole thing. But I can talk with my wife about it for days. Because we took the whole thing in without any sort of end goal of having likes on social media or whatever. And I have zero regrets. Because unlike everyone else who came with us, we saw the northern lights.
