#+TITLE: Tyler Burns's Website
#+HTML: <div id="top"></div>
#+TOC: headlines 1

* About me
[[./meditations_chapter_one.html][I]] am an American CEO and computational biologist who lives in Berlin, Germany. I am best known for my work on knowledge graphs, the limits of dimension reduction algorithms, and single-cell analysis with respect to the many applications of K-Nearest Neighbors. 

I run a company called [[https://burnslsc.com/][Burns Life Sciences Consulting, GmbH]], which allows me to practice open science, work on diverse projects with many organizations, and develop and sell products. The problem is most of my work is behind NDAs so I can't talk about it. There is another large amount of my work that is unpublished, simply because being a CEO has a lot of demands that don't give me the time.

This website is a place where I can openly share my ideas and non-client work, regardless of how "finished" it is. I have uploaded written work, code, posters and powerpoint slides of various projects I have driven or contributed to. I intend for a lot of my work here to be "long content" slowly evolving over years if not decades. What matters most is that my thoughts and the work I do that I find meaningful is uploaded here, so when I die (hopefully way down the line) others can easily build off of any worthwhile groundwork I have laid out. 

If you have quesitons or comments, or you're interested in working or collaborating with me, just send me a message (see contact info below). I'm always happy to help. 
* New
#+HTML: <a href="#top">Back to top</a>
** [[./fight_complexity_with_complexity.html][Fight complexity with complexity]]
Article.\\

A new paradigm that seems to be emerging from the bottom up, linking my work on dimensionality reduction interpretation with GPT-based interpretations of the human brain and cancer immunotherapy. We use something complex to understand or fight something complex. This is opposed to the older ideal of having perfect mechanistic understanding of what we're doing.

** [[./burns_tedx_caricature.pdf][TEDx Basel: caricature of my talk]]
Work of art.\\

While I was giving my TED talk, unbeknownst to me an artist in the audience was drawing it out in real time, complete with pen and watercolor. He did this for each of the speakers. I was extremely impressed with what he was able to do given the very limited time. My talk is not yet on YouTube, but if you want the gist of it, have a look at this picture.
** [[https://rseng.github.io/devstories/2023/tyler-burns-part-1/][Developer Stories Podcast: Heavenly light emanating from line 37]]
Guest on a podcast.\\

I talk with software developer Vanessa Sochat about my time in graduate school. I started out as a wet-lab biologist. But after taking an intro CS class for fun, I realized that I really enjoyed the dry-lab side of things, and my career trajectory changed accordingly. Have a listen for more details. This is part 1 of 2. 
** [[./life_and_love_during_coronazeit.pdf][Life and love in Berlin during the Coronazeit]]
Feature.\\

An article I wrote in 2020 for the annual Krupp Internship e-newsletter. It was written just after the first wave of the COVID-19 pandemic. It serves as a time capsule for that period, in which many of our basic assumptions about the stability and the future of the modern world were upended. I enjoy looking at it again now and then, as it captures a very unique state of mind. It also captures my wedding, which took place the day before the first lockdown, and included toilet paper as a wedding present.

** [[./tyler_alumni_im_portrait.pdf][Tyler Alumni Im Portrait]]
Feature.\\

"Im" is short for "in dem" in German. Not a typo. An article I did for the Stanford Krupp Internship Program, which had huge impact on my life and career trajectory. In a nutshell, I was pre-med prior to my medical internship at the Charite Hospital in Berlin in 2007. Through the internship, I realized that I wanted to do research rather than clinical work. I got my PhD and came back to Berlin to work on the Charite Hospital campus once again, this time as a researcher! I will be forever grateful for the Krupp Internship program and Stanford's Bing Overseas Study Program.
** [[./speech_memorization_helper.html][Speech memorization helper]]
Web page.\\

Take the text you want to memorize and paste it into the box. The text will be split up into individual sentences. The first sentence will be displayed. Recite as much of the subsequent sentences as you can from memory. Buttons will allow you to move to the next sentence or the previous sentence all the way to the end of the text.

** [[./finite_infinite_life_games.html][Finite and infinite-life games]]
Article.\\

I make a comparison between the older 2-D platforming games from the 16-bit era and a newer game called Celeste. The key difference is that in Celeste, the gameplay is incredibly difficult, but you have infinite lives. I argue that this type of gameplay is an efficient route to flow state. I describe how this type of gameplay mirrors a lot of problem solving in my professional life. I end by saying that Celeste gameplay is an empowering mental model for doing things outside your competence and comfort zone.
* Single-cell analysis
#+HTML: <a href="#top">Back to top</a>
** [[./julia_cytof_pipeline_one_file.html][CyTOF UMAP with Julia: an experiment]]
Markdown.\\

Here, we compare the UMAP implementation from R with the UMAP implementation from Julia. The Julia programming language is a much faster programming language, so I expected that we might be able to speed UMAP up. Accordingly, it did. Here, I show you how to import your data into R, move in into Julia, run UMAP, get it back into R, and plot it. All in a single R markdown.
** [[./run_cytof_with_seurat.html][Run CyTOF analysis with Seurat]]
Markdown.\\

Seurat is an R package that runs single-cell sequencing and related data. Here, I trick Seurat into thinking my CyTOF PBMC data is single-cell sequencing data. I find out that the effective dimensionality of my CyTOF data appears to be much less than the surface markers I am using (15). This is a counter-intuitive result because our features are carefully curated before the experiment is done.
** [[./anatomy_of_fcs_file.html][Anatomy of a fcs file]]
Markdown.\\

You can parse a fcs file from scratch without flowCore. I read in a fcs file line by line, rather than using the standard read.FCS from flowCore. We can't read the data directly this way, but we can read in the header and the text. For the data, we read in the bytes, convert them into decimal, and then build the expression matrix.
** [[https://www.biorxiv.org/content/10.1101/337485v1][Continuous Visualization of Multiple Biological Conditions In Single-Cell Data]]
First author publication.\\

Abstract: In high-dimensional single cell data, comparing changes in functional markers between conditions is typically done across manual or algorithm-derived partitions based on population-defining markers. Visualizations of these partitions is commonly done on low-dimensional embeddings (eg. t-SNE), colored by per-partition changes. Here, we provide an analysis and visualization tool that performs these comparisons across overlapping k-nearest neighbor (KNN) groupings. This allows one to color low-dimensional embeddings by marker changes without hard boundaries imposed by partitioning. We devised an objective optimization of k based on minimizing functional marker KNN imputation error. Proof-of-concept work visualized the exact location of an IL-7 responsive subset in a B cell developmental trajectory on a t-SNE map independent of clustering. Per-condition cell frequency analysis revealed that KNN is sensitive to detecting artifacts due to marker shift, and therefore can also be valuable in a quality control pipeline. Overall, we found that KNN groupings lead to useful multiple condition visualizations and efficiently extract a large amount of information from mass cytometry data. Our software is publicly available through the Bioconductor package Sconify.
 
** [[https://pubmed.ncbi.nlm.nih.gov/28094900/][High Throughput Precision Measurement of Subcellular Localization in Single Cells]]
First author publication.\\

Abstract: To quantify visual and spatial information in single cells with a throughput of thousands of cells per second, we developed Subcellular Localization Assay (SLA). This adaptation of Proximity Ligation Assay expands the capabilities of flow cytometry to include data relating to localization of proteins to and within organelles. We used SLA to detect the nuclear import of transcription factors across cell subsets in complex samples. We further measured intranuclear re-localization of target proteins across the cell cycle and upon DNA damage induction. SLA combines multiple single-cell methods to bring about a new dimension of inquiry and analysis in complex cell populations. © 2017 International Society for Advancement of Cytometry.

My summer students are co-authors on this paper! Undergrads and high school students. They worked very hard and learned a lot. I am proud of each and every one of them. 
** [[./Burns.Dissertation.Final.pdf][Expanding the Capabilities of Mass Cytometry Data Acquisition and Analysis]]
PhD Thesis.\\

My PhD thesis dissertation, from the laboratory of Garry P. Nolan at Stanford University School of Medicine. 

In sum: I started by developing a method to enable flow and mass cytometry to detect and quantify nuclear localization, called Subcellular Localization Assay (SLA), which came out of a collaboration with the lab of Ola Soederberg at University of Uppsala, Sweden.

In parallel, I was taking computer science classes as a side hobby. I reached a point where I was trying to compare two t-SNE maps between unstimulated and simulated data, and I realized that there was a K-Nearest Neighbors based solution that I could implement with my newfoud computer science competencies. I therefore developed Sconify, a now BioConductor package that allows for these visualizations. There were many use cases, and I spent the remainder of my thesis developing this method further and doing various collaborations with it.
** [[./tjb_dimr_talk.pdf][A visual interrogation of dimension reduction tools for single-cell analysis]]
Slide deck.\\

German CyTOF User Forum; Berlin, Germany; January 2020.
In this talk, I measured the accurracy of dimension reduction tools (PCA, t-SNE, and UMAP) in terms of their nearest neighbor overlap. This is the k-nearest neighbors of a given cell in the original high dimension space, in comparison to the k-nearest neighbors of a given cell in the embedding. I show that the overlap here is much lower than my audience expected. I've given this talk many times since then, for my clients.
** [[./visual_capabilities_of_som.pdf][Neighborhood-based analysis of self-organizing maps]]
Slide deck.\\

[[https://vib.be/labs/saeys-lab][Laboratory of Yvan Saeys]], VIB Ghent, Belgium. June 2018.
This slide deck summarizes some work I did with Sofie Van Gassen, developer of [[https://bioconductor.org/packages/release/bioc/html/FlowSOM.html][FlowSOM]] and all-around awesome person. We were looking at what is called the U-Matrix, a way to visualize the self organizing maps that FlowSOM produces. The question was what insights could we derive from using the U-Matrix to visualize the output of very large FlowSOM clusterings (eg. a 100 x 100 grid rather than the default 10 x 10). So far as I know, this is not explored in any major CyTOF publication, so any CyTOF users who use FlowSOM (most people at the time of writing) should have a look at this. There are visualizations in here that are useful but remain unpublished.
** [[./mass.cytometry.analysis.history.pdf][A history of mass cytometry data analysis, and where the field is going]]
Slide deck.\\

[[https://www.drfz.de/en/aktuelles/veranstaltungen/cytof-forum-2020/][German Rheumatism Research Center]]; Berlin, Germany; March 2019.
I talk about how CyTOF data analysis developed from its inception at the beginning of 2010 to now. In doing so, I provide a template for proper CyTOF data analysis in terms of how we got there. In doing so, I test various assumptions: I show visualizations of data transformations other than asinh(x/5), and I show what a SPADE tree looks like with completely random inputs. I like to show these slides to people new to CyTOF data analysis to properly orient them. 
** [[./drfz_tsne_interrogation_talk_final.pdf][A comprehensive interrogation of the t-SNE algorithm for mass cytometry analysis]]
Slide deck.\\

German Rheumatism Research Center; Berlin, Germany; May 2018.
This talk was a response to a member of the research institue who was simply not convinced that t-SNE was providing the accurracy that the avearge CyTOF user thought. In this talk, I show that he was right. This being said, I provide recommendations for how to properly use t-SNE for CyTOF analysis.
** [[./burns_cytof_user_forum_talk_for_pdf.pdf][Nearest neighborhood comparisons across biological conditions in single cell data]]
Slide deck.\\

Invited Speaker, German CyTOF User Forum; Berlin, Germany; February 2018.
This is the talk version of my 2018 Sconify paper, that ended up being the final chapter of my PhD thesis. There are two aspects to this talk. The first is making visual comparisons of unstimulated and stimulated CyTOF data when looking at measurements of phosphoproteins. This was easily done on SPADE trees, but not t-SNE maps, until I started making k-nearest neighbor based comparisons. The second aspect of this talk is using the same nearest neighbor based comparisons to investigate batch effects in CyTOF data. I note that batch effects were only heavily discussed among CyTOF users starting near 2020 (in my circles), and this work goes back to 2016.
** [[./final_distance.project.poster.pdf][Determining which distance metrics are ideal within a mass cytometry data analysis pipeline]]
Poster.\\

CYTO Conference; Prague, Czech Republic; May 2018.
Abstract: Due to the rise of high-dimensional single cell technologies in the past few years, there has been an increasing number of both computational methods and workflows to analyze the new wealth of data. However, non-intuitive properties of high-dimensional space can give rise to analysis artifacts, collectively known of as the “curse of dimensionality.” Increasing dimensions differentially affect the performance of distance metrics, and there is no clear consensus about which distance metrics to use for which analysis strategies. While the influence of many tool-specific parameters has been evaluated, we study here the impact of commonly used distance metrics on the outcome of dimensionality reduction and clustering.

** [[./0117TylerCytobankBlog.pdf][Fine-Tune viSNE to Get the Most of Your Single-Cell Data Analysis]]
Guest blog post.\\

This is a guest blog post I wrote for Cytobank. The formatting of the post has since been messed up (image links are broken) since Beckman acquired Cytobank and moved all the web content over. Until it gets fixed, I'm linking you to the original PDF. At the time of writing, there was still a lot of work to be done in terms of really understanding dimension reduction for CyTOF data. As such, I spent a lot of time adjusting inputs (eg. number of cells) and parameters (eg. perplexity) to understand how that affects the resulting map. 
** [[https://github.com/tjburns08/dimension_reduction_add_noise][Dimension reduction add noise]]
Software.\\

If you have one or two bad markers in your panel (noise), does it completely ruin your t-SNE/UMAP visualizations? According to my analysis so far, no. I take whole blood CyTOF data (22 dimensions) and add extra dimensions of random normal distributions, running t-SNE after each new column has been added (I've done UMAP too). What I have found:
1. A few dimensions of noise do not catastrophically affect the map. Lots of noise dimensions do.
2. The embedding space shrinks with increased number of dimensions. You have to hold the xy ranges constant to see this.
3. When you have many dimensions of noise, the map starts to look trajectory-like (look at the end of the gif), which could affect biological interpretation.
** [[https://github.com/tjburns08/dimension_reduction_island_placement][Dimension reduction island placement]]
Software.\\

This project asks the following question: if you run t-SNE or UMAP over and over for 100 times or more, how different does each map look from each other map? Is each map radically different? Is each map similar? Are there pockets of stability?

The spoiler alert is that the island placement of UMAP appears to be more stable than that of t-SNE, but t-SNE does display pockets of stability. This can be more easily seen by ordering the t-SNE runs by similarity.
** [[https://github.com/tjburns08/knn_sleepwalk][Knn sleepwalk]]
Software.\\

A wrapper I wrote around the [[https://anders-biostat.github.io/sleepwalk/][sleepwalk]] R package. Hover the cursor over any cell in your embedding, and it will show you the cell's k-nearest neighbors computed from the original feature space (as opposed to the embedding space). This allows you to test your assumptions around how exact a low-dimensional embedding (eg. t-SNE, UMAP) is. 
** [[https://www.bioconductor.org/packages/release/bioc/html/Sconify.html][Bioconductor package Sconify]]
Software.\\

Official description: This package does k-nearest neighbor based statistics and visualizations with flow and mass cytometery data. This gives tSNE maps"fold change" functionality and provides a data quality metric by assessing manifold overlap between fcs files expected to be the same. Other applications using this package include imputation, marker redundancy, and testing the relative information loss of lower dimension embeddings compared to the original manifold.
** CyTOF analysis pipeline
Markdowns.\\

CyTOF analysis has come a long way. Along with single-cell sequencing analysis, a lot of it is high-level functions that do what needs to be done. I prefer a guts-level analysis, where I can see the low-level the details of how my data are being manipulated. This is important for understanding and innovation. 
*** [[./cytof_pipeline_one_file.html][One fcs file]]
Keeping it to one fcs file, we can focus on what happens when a fcs file is read into R, how it is transformed, and what the best practices of clustering, dimension reduction, and visualization are. These foundations can be built upon when looking at multiple fcs files to determine where there are differences in your control versus experiment group. 
*** [[./cytof_pipeline_many_files.html][Multiple fcs files]]
This markdown uses the [[https://www.bioconductor.org/packages/release/bioc/html/diffcyt.html][diffcyt]] package to help us do statistics between groups, though I show you how to do per-cluster statistics yourself. We make box plots group-level comparisons for clusters we care about. We also color our dimension reduction maps by the p-value information. This pipeline requires a sample metadata file, as well as a marker file. I show you what these look like directly in the pipeline.
** KNN sleepwalk examples
Software.\\

Some examples of output for my [[https://github.com/tjburns08/knn_sleepwalk][KNN sleepwalk tool]]. These are interactive, and are here to give the user intuition around the nature of dimension reduction maps. From the README: "My wrapper allows for the visualization of a given cell's K-nearest (and K-farthest) neighbors. In other words, the cursor is on a given cell, and the cells on the map that change color correspond to a pre-specified number of nearest neighbors in the original high-dimensional space." See notebooks in my repo to see the data and code. What to do with the visuals below:
- K-nearest neighbors (KNN) will give you intuition around how exact the embedding is.
- K-farthest neighbors (KFN) will give you intuition around how well the embedding preserves global structure. 
*** CyTOF PBMCs
The dataset is internal, from the German Rheumatism Research Center in Berlin. These take a bit to load after you click on them, but its worth the wait. 
**** [[./knn_sleepwalk_cytof.html][KNN from original marker space]]
**** [[./kfn_sleepwalk_cytof.html][KFN from original marker space]]
*** single-cell RNA sequencing PBMCs
The dataset is from [[https://satijalab.org/seurat/articles/pbmc3k_tutorial.html][this vignette]]. The dimension reduction was done on the top 10 principal components of the top 2000 most variable genes.
**** [[./knn_sleepwalk_scrna_seq_pca.html][KNN from PCA space]]
**** [[./kfn_sleepwalk_scrna_seq_pca.html][KFN from PCA space]]
**** [[./knn_sleepwalk_scrna_seq_var_genes.html][KNN from variable genes space]]
**** [[./kfn_sleepwalk_scrna_seq_var_genes.html][KFN from variable genes space]]

** [[./distance_matrix_correlation.html][Distance matrix metric correlations]]
Markdown.\\

Which distance metrics are right for your data analysis. While I've created a poster on this [[https://tjburns08.github.io/final_distance.project.poster.pdf][here]], this is a stab at it from a different direction. I make synthetic CyTOF-like data, varying the dimensionality from 2 to 1000. I make a distance matrix for each distance metric used, and then correlate each one to that of the Euclidean distance matrix, which is often a default. The results are counter-intuitive.
** [[./asinh_mean_vs_mean_asinh.html][asinh(mean(x)) vs mean(asinh(x))]]
Markdown.\\

If you want the means of your markers per cluster, be careful how you export the data. If you export the means of the raw values per cluster, and take the asinh(x/5) transform of that, the values will be different than if you take the means of the asinh(x/5) transformed data per cluster. The latter is the right way to do it. But don't take my word for it. Look at the markdown yourself. 
** [[./cytof_data_transformations.html][Data transformations for CyTOF]]
Markdown.\\

CyTOF data are transformed using the inverse hyperbolic sine (asinh) of the data divided by 5 (aka scale argument of 5). But does it have to be like that? What happens if we use a scale argument of 1? 500? What if we do a log transform? How does t-SNE look on untransformed CyTOF data?

* Natural language processing
#+HTML: <a href="#top">Back to top</a>
** [[./cnn_fox_ap_map.html][CNN, FoxNews, and AP: a News Space study]]
Markdown.\\

In this study, we take news articles that correspond to CNN, FoxNews, and AP, from their Twitter handles, and their BERT embeddings, and produce a map of news space. We figure out what areas of news space are heavy in one news source or the other (perhaps corresponding to political bias). We find that Fox News in general reports heavily on the topic of politics in comparison to CNN and AP, and that while AP is supposed to be neutral, there are still regions of news space that are heavy in AP content. Interactive maps are included for the user to explore.
** [[./how_i_curate_content.html][How I curate content]]
Article.\\

We should all be active content curators. We should all be actively discussing how we curate our feeds. We should not rely on social media's recommendation algorithms to do this for us. Accordingly, here is how I curate my content. I hope this gives you some ideas, and I hope this encourages you to share your content curation strategies.
** [[./scrolling_problem.org][The Scrolling Problem]]
Article.\\

We spend a large fraction of our lives endlessly scrolling through our feeds, with no control over what hypernormal, outrage-inducing content will appear next. I call this the scrolling problem. I define it, and I have a crack at it by viewing my news feed as map with the help of an AI language model based on BERT. 
** [[./gpt3_student.org][GPT-3 simulating students]]
Article.\\

This is a report I wrote for my uncle, who is a professor at the University of Michigan Ross School of Business. The concern was that generative language models would be able to simulate student's responses to essay questions good enough that tech-savvy students would simply offload their homework to GPT-3. I explore this option using my early access to GPT-3, with a conclusion heavily inspired by an article by [[https://www.gwern.net/GPT-3#weaknesses][Gwern]]. You pretty much have to at this point. 
** [[./context_problem_bfx.html][The Context Problem in Bioinformatics]]
Article.\\

In the age of big data, my bioinformatics analyses often lead to output that is still too much for a human to extract insight from. My use case here, common in my work: what GWAS traits do two or more genes have in common? I produce a context map of GWAS traits using an AI language model based on BERT. I then subset the map by traits associated with the genes the user inputs, coloring the points accordingly. One can quickly know what contexts, rather than traits, the genes share. 
** [[./ask_marcus_writeup.html][What would Marcus Aurelius say?]]
Article.\\

I turn the Meditations by Marcus Aurelius into a semantic search based language model, where I ask a question and it returns the most relevant passages in the book as answers. This helps me with the study of stoic philosophy, but this approach can be used in any sort of book that is structured as aphorisms. 
** [[https://medium.com/@tjburns_72591/how-to-utilize-scientific-literature-trends-to-gain-intuition-about-a-topic-b5c554e3d280][How to utilize scientific literature trends to gain intuition around a topic]]
Medium post.\\

The scientific literature is overwhelming, and knowing how to utilize text mining and analytic tools can help you efficiently get what you want out of a literature search. Here, I utilize the PubMed API to find publication rates for particular topics. I show that among other things, single-cell sequencing began out-pacing mass cytometry in 2016. Insight like this helps you see how crowded a field is and especially identify trends.
** [[https://medium.com/coinmonks/how-to-identify-thought-leaders-and-visualize-their-influence-c01aa218090e][How to identify thought leaders and visualize their influence]]
Medium post.\\

Understanding how authors of a given field are connected can help you identify key individuals to pay attention to. Here is how I utilize the PubMed API to build co-author networks, which lead me to identify thought leaders in a given domain. In this article, focusing on mass cytometry, I identify two types of thought leaders: one exclusive to a particular sub-domain, and one who spans across multiple sub-domains. It is important to know both types when approaching a new topic.
** [[https://medium.com/@tjburns_72591/using-and-mining-pre-prints-to-stay-ahead-of-your-field-with-the-help-of-twitter-50d5bdc528de][Using and mining pre-prints to stay ahead of your field, with the help of Twitter]]
Medium post.\\

I explain why pre-prints are important to staying ahead of the technology and general paradigms in your field, with single-cell analysis as an example. I then show how I utilize the Twitter API to harvest and rank tweets from automated pre-print linking bots from bioRxiv to determine what pre-print articles are being talked about (and therefore what you should probably pay attention to).
** [[https://github.com/tjburns08/rss_map][RSS map]]
Software.\\

Associated with [[https://tjburns08.github.io/scrolling_problem.html][The Scrolling Problem]]. An app that converts an RSS feed into a semantic map where articles that are similar to each other in context are near each other on the map.
** (temporarily suspended) [[https://gwasmap.herokuapp.com/][Gwasmap]]
Software.\\

Associated with my article [[https://tjburns08.github.io/context_problem_bfx.html][The Context Problem in Bioinformatics]]. Given one of more genes, what are the GWAS associations? These are placed onto a semantic map where associations that are similar to each other are grouped near each other on the map. Thus, if gene 1 is associated with Alzheimer's disease and gene 2 is associated with age-related cognitive decline (different but related disease) the associations for each gene (colored accordingly) will show up near each other.
** [[https://huggingface.co/spaces/tjburns/ask_marcus_aurelius][Ask Marcus Aurelius]]
Software.\\

Associated with [[https://tjburns08.github.io/ask_marcus_writeup.html][What Would Marcus Aurelius Say]]. This project turned the Meditaitons by Marcus Aurelius into a semantic map that can be queried, such that the user can ask a question, and the software will return the most relevant passages in the Meditations.
** [[https://huggingface.co/spaces/tjburns/find_your_biases][Find your biases]]
Software.\\

Write your thoughts into the text box, and the app will give you a list of cognitive biases that match the thoughts. The app does this using an AI embedding model to embed both your input and Wikipedia's [[https://en.wikipedia.org/wiki/List_of_cognitive_biases][list of cognitive biases]], and then perform a nearest neighbor search. 
** Twitter archive and embed
Software.\\

This is one of the main tools that I wrote and use to address the [[./scrolling_problem.html][scrolling problem]].

A pipeline that takes as input a list of twitter user names that you supply. First, it scrapes the entire twitter history for the given names. Second, it uses BERT to make a topic-based high-dimensional embedding of every tweet per user name. If these two steps had already been done for a given user, it will update with the new tweets. Then, the user selects a subset of users to visualize. For these users, the BERT embeddings are converted into a UMAP, which is then clustered and annotated with extracted keywords per cluster. Finally, the results are visualized in an interactive user interface.
** [[https://huggingface.co/spaces/tjburns/duckduckgo_2d_search][DuckDuckGo 2-D Search]]
Software.\\

For web searches of broad topics, where you need the first hundred results rather than the first page. Type in your search term of interest, and it will give you an interactive context map of search results and a results table with clickable links. 
** [[./biorxiv_medrxiv_history.html][Preprint server archive]]
Software.\\

A searchable and sortable table of every biorxiv and medrxiv pre-print to date ([2022-11-17 Thu 13:43]). Specifically, every time a paper is uploaded to one of these pre-print servers, it is automatically tweeted out from the respective twitter handle. As such, the table contains the paper title along with various tweet metadata (eg. likes) to allow users to understand which papers are potentialy important.
** Likes vs retweets
Markdown.\\

*** [[./single cell sequencing OR single-cell sequencing.csv_likes_vs_retweets.html][Search term: single cell sequencing OR single-cell sequencing]]
We find three regions:
- High retweets/likes: open academic student and postdoc positions
- Medium retweets/likes: papers, projects, data (the stuff you're probably looking for)
- Low retweets/likes: memes, status updates, fun stuff
** [[./question_graph_writeup.html][Question graph]]
Markdown.\\

You are only as good as the questions you ask yourself and others. My uncle told me that many years ago when I was getting started with my career and it stuck. This has been relevant to me in terms of having and maintaining good friendships, being a good husband, being a good family member, being a good businessman, and when I was in graduate school, being a good scientist, and simply being an interesting person. I have a very large list of questions now that is very overwhelming. So I turned them into an embedding using the BERT language model, turned that into a nearest neighbor graph, and then derived insight from looking at the questions in terms of "communities." 
* Philosophy and rationality
#+HTML: <a href="#top">Back to top</a>
** [[./add_beauty.html][Replace the word "value" with "beauty"]]
Article.\\

A dialectic between my rational and my emotional/spiritual side that took a while to build up. In my professional life, I think in terms of value (value-add, ROI, etc). But if we get rid of the word "value" in all my rational calculations and replace it with "beauty," it solves a much larger swath of problems and helps me make decisions that allow for, well, a beautiful life lived.
** [[./virtue_of_depth.html][The virtue of depth]]
Article.\\

It starts as a lament. In the real world I'm pulled many more directions than in graduate school. As such, I cannot always go deep with respect to whatever I'm doing. In my longing for depth, I can describe what depth is to me. The way the modern world is set up, I think a lot of us are missing depth in our lives. In this regard, I argue that depth should be a virtue that we strive for.
** [[./occams_razor.html][But what is Occam's razor really?]]
Article.\\

Occam's razor states that for a given phenomenon, the simplest explanation is the most likely explanation. I explore this with a fun example from my life. I then look at a computational formalization of this, which I use today for sensemaking.
** [[./how_to_solve_problems.html][What I learned about problem solving from my thesis lab]]
Article.\\

A collection of stories from my time in graduate school. The people in my thesis lab had one perplexing thing in common. They would come in as biologists and then literally invent new hardware and software, without any prior relevant background. They would just figure it out as they went. I learned the ways of the lab and learned several themes around how to solve problems, some of which fly in the face of traditional mainstream advice. So I figured I'd write them down.
** [[./on_hacking.html][Hacking: examples of seeing through and unseeing in my life]]
Article.\\

A lot of hacking is seeing through and unseeing the everyday abstractions we pretend to be true. Hacking is sometimes malicious (the Hollywood stereotype), and sometimes it is productive (known as innovation or ingenuity). It is not limited to computers, and it is definitely not limited to coding. Here, I lay out my favorite framework for what hacking is, and I provide examples that range from business to sports to computing.
** [[./coding_as_philosophical_project.html][If Plato lived today, he'd be coding]]
Article.\\

Plato and the Greek philosophers valued learning geometry as a means to understand and think about the world, despite not using it for practical purposes (like engineering). I see computer science as geometry for modern philosophy. This matters because I think one should still learn the basics of how to code even if AI automates all of it in the future. Even the first few months of computer science drastically helped me improve my thinking.
** [[./its_more_complicated_than_that.html][It's more complicated than that]]
Article.\\

This is the observation I run into with just about every line of scientific inquiry. This is despite a revolution of new technologies that allow us to look at much more data, and new algorithms to make sense of these huge datasets. I repeat this phrase every time I start to feel like I've figured it all out.
** [[./purpose_driven_vs_purposeless.html][The way is the way]]
Article.\\

I spent a large portion of my life being goal-driven. I have realized more recently that being focused on the process rather than the goal is more beneficial in many respects. This essay is about my journey to that realization.
** [[./dialectic.html][Making sense of the (messy) real world]]
Article.\\

Finding truth in the real world is much different than finding truth in grad school. Grad school had me working on non-controversial, dry topics that few people in the world worked on. The real world is a lot messier. I talk about the idea of collecting opposing perspectives, steelmanning them, and putting them in dielectic to find higher truth. It's simple in theory, but hard in practice.
** [[./tao_of_problem_solving.html][The Tao of problem solving]]
Article.\\

One of the key components to my method of solving problems is to get into the flow state. When I'm there, some or all of the problem at hand solves itself. And it feels great. I show examples of me doing this. I talk about Taoism as an ancient philosophy built around flow state, but at the macro level rather than the "within-game" level. This is the ideal of being in a perpetual flow state that lasts one's entire lifetime. 

** [[./the_beauty_is_truth_delusion.html][The beauty is truth delusion]]
Article.\\

This is the idea that data visualizations that look prettier than others don't necessarily convey more truth. I use SPADE and t-SNE as examples that can produce this delusion. This article serves as a call to action for the bioinformatics community to help users distinguish between truth and beauty as data visualization tools come out and become widely used. 
** [[./stick_shift_mindset.html][Zen and the art of driving stick]]
Article.\\

I find that if I'm driving stick rather than automatic, I'm much more connected to what I'm doing, much more satisfied in the moment, and I'm objectively a better driver as a result.This concept generalizes. Pick an endeavor. Complete the analogy: automatic transmission is to your endeavor as manual transmission is to X. If you know how to do X, do it when you can. If you don't know how to do X, then learn it. I give several examples of this in my life, and I conclude by encouraging others to embody this way of doing things.
** [[./minimize_and_sustain.html][Sustainability for value]]
Article.\\

My current plan for coming economic uncertainty we face in the near term due to the recession, and for uncertainty that wil persist beyond the recession (eg. AI disruption). I talk about re-framing my goals as minimizing rather than maximizing something, and about the systems thinking and sustainability based mindset that one sees in subjects like permaculture. This is helping me be more effective, and figure out unique new ways I can add value to the world. 
* Computing
#+HTML: <a href="#top">Back to top</a>
** [[./mathematician_and_hacker.html][The mathematician and the hacker]]
Fiction.\\

A conversation between a hacker and a mathematician that explores the contrast between these worldviews. The mathematicxian wants to create elegant theories and abstractions that the world fits into. The hacker is more interested in finding and leaning into the things that don't add up. The whitespace.

** [[./ca_rule_space.html][Elementary cellular automata rule space]]
Markdown.\\

I lay out the rule space of elementary cellular automata as an eight dimensional dataset. I perform UMAP on rule space and color by complexity measures, the most interesting being the labeled Wolfram class of each rule. Class 3, the most chaotic behavior, shows up as little pockets in rule space. Class 4, where things like Turing completeness happen, shows up at or near these pockets, surrounded by Class 2 (repetitive, orderly). This supports the idea of Class 4 being "at the edge of chaos."
** [[./xai_and_us.org][Explainable AI and understanding ourselves]]
Article.\\

I make the connection between understanding a black box AI algorithm (a hot topic) and understanding ourselves. I make the argument that accordingly, we as humans are prepared to take on this task. I discuss natural language explanations, which is what happens when you attach a language model to an AI system. Ideally, you can ask it why it did what it did.  
** [[./logic_gates.html][Logic gates]]
Markdown.\\

What are the fundamental units of a computer? Logic gates. I show what these are. I then show that they can be created with combinations of a single type of logic gate: NAND (Not AND). In other words, you can make a general-purpose computer if you had enough NAND gates and wires. In the spirit of this, I combine NAND gates to create a calculator that can add large numbers. One of the key points in this exercise is that it does not take much to get from NAND gates to complex computations.
** [[./1d_ca.html][1-D Cellular Automata]]
Markdown.\\

Here, I write some code to produce each of the 256 Wolfram cellular automata rules, and visualize the output. 
** [[./explore_rule_110.html][Explore Wolfram Rule 110]]
Markdown.\\

Here, I write some code to produce Rule 110, a Class 4 1-D cellular automata. I then enhance the gliders to make them easier to see. I explore how the output changes if I make the rule probabilistic (eg. 99.99% chance the rule will be followed. 
* Statistics
#+HTML: <a href="#top">Back to top</a>
** [[./1_law_large_numbers_central_limit_theorem.html][Coin toss series 1: The law of large numbers and the central limit theorem]]
Markdown.\\

I taught one of my high school summer students the basics of probability by simulating coin tosses in R. Here, we "discover" the law of large numbers and the central limit theorem using simulated coin tosses. 
** [[./2_runs_of_luck.html][Coin toss series 2: Runs of luck]]
Markdown.\\

Here, we build on the initial piece in the series by looking at the properties of runs of luck. If we flip a coin a million times, how often will we get 10 heads in a row? How many times do we need to flip a coin to get 20 heads in a row on average? Related to sports. How often, statistically, would you expect Steph Curry to make 10 three pointers in a row given his 3-point shot percentage? 
** [[./3_fair_vs_unfair_coins.html][Coin toss series 3: Fair versus unfair coins]]
Markdown.\\

Here, we examine the properties of unfair coins, where the odds of getting heads or tails does not equal 50%. Can we figure out whether a coin is a fair coin? 
** [[./4_random_walk.html][Coin toss series 4: Random walks]]
Markdown.\\

Here, we show that if we simulate flipping coins, but we keep a record of the number of heads and the number of tails, we end up doing a random walk. We visualize these walks (they look somewhat like stock market data), and ask questions like how often a random walker crosses zero.  
** [[./5_dice_roll.html][Coin toss series 5: Dice rolls]]
Markdown.\\

Here, we do an abstraction of the coin tosses we have been simulating, by coinsidering dice of three or more faces. We simulate these dice rolls and examine their properties. How often does a six sided dice land on the number 3? We can figure that out with simple math, but if you roll a dice 1000 times, and you do that again, and you do that again, what will be the standard deviation of the number of times the dice lands on 3? 
** [[./6_is_this_sequence_random.html][Coin toss series 6: Is this sequence random?]]
Markdown.\\

Here, we look at fair coin tosses, unfair coin tosses, and random walks, and explore the randomness of the sequences by doing convolutions on the sequences with kernel size 2.
* Health
#+HTML: <a href="#top">Back to top</a>
** [[./how_to_get_fit_long_term.html][How to get fit in 20 years]]
Article.\\

Over the years, I have seen people who want to get in shape develop fitness goals that are too much over too little time, which leads to burnout. Here, I provide the opposite perspective, which has worked for me in my adult life. Take your fitness goals and ask: if I had a year to achieve this rather than a month, how would I do it?
** [[./psychotherapy_and_fitness.html][Psychotherapy should be as normal as going to the gym]]
Article.\\

There is a renewed interest in Stoic philosophy as of late. It's a great set of tools that I have used for dealing with hardship. But it's 2000 years old. Where are the modern Stoics? They exist, but under a different name: psychotherapists. If psychotherapy was the successor to Stoicism, and there is so much interest in Stoicism, then shouldn't there be an equal amount of interest in clinical psychology and how it can help us? Shouldn't it be something we learn early, and make these tools part of our daily routine, as the Stoics do?
** [[./just_paint.org][Just paint]]
Article.\\

An anecdote from my aunt evolves into a motivational article (mainly written for myself). I describe the art and science of how to start a project and how to keep it going. I talk about how I build psychological momentum. I discuss the concept of Long Content, and how it relates to the neuroscience of dopamine optimization.
* Newsletter
#+HTML: <a href="#top">Back to top</a>
Think of these as both newsletters and time capsules. They are not exhaustive, but they do represent the bigger insights and ideas on my end from that time period.
** [[./2023_april.html][April 2023]]
** [[./2023_march.html][March 2023]]
* Other contributions
#+HTML: <a href="#top">Back to top</a>
**** Former computational biologist, now guest researcher, at the German Rheumatism Research Center in Berlin, Germany. I will always stay connected to my academic roots.
**** Developing software to interrogate and visualize the local similarities between original manifolds and lower dimensional embeddings. Important for anyone wanting to determine which of these methods is the right tool for the job.
**** Solved a long-standing data visualization problem for mass cytometry, and developed a Bioconductor package for it, with a visual description here, and this publication...
**** Set the best practices in my PhD thesis lab for learning bioinformatics as a classical biologist.
**** Helped develop a wet-lab implementation for a cutting-edge bioinformatics concept, which became part of a patent.
**** Led an international collaboration between my thesis lab (USA) and a laboratory in Uppsala, Sweden, whose biochemical foundations turned into [[https://pubmed.ncbi.nlm.nih.gov/28094900/][this publication]], and helped [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4767631/][this one]].
**** Mentored several high school students and undergraduates throughout my thesis work, teaching them biology, computer science, statistics, and importantly how to integrate these fields.
**** Built a website for my PhD program using HTML, JavaScript, and SQL, that helped first year students connect with current and previous members of a given research laboratory (I'd link it but you have to be a Stanford student to view it).

* Fun stuff
#+HTML: <a href="#top">Back to top</a>
** [[./gol_navigate.html][Conway's Game of Life Cellvivor]]
Game.\\

A game within Conway's Game of Life. You are a blue square that you can move (with arrows), and your goal is to make contact with a "goal" square, colored green, while avoiding all the squares in the Game of Life automata that come at you. Each level up leads to a denser game board. You get five seconds of invincibility (you're colored red) in the beginning of each level, that allows you to get out of the way of any Game of Life objects near you.
** [[./breakout.html][Breakout]]
Game.\\

A game that will always be of significance to me, because it was the assignment in my intro CS class that made me realize that I really enjoy coding. A simple implementation of breakout that runs on a single html page.
** [[./conways_gol.html][Conway's Game of Life]]
Web page.\\

I first came across Conway's Game of Life when I was 16. It completely changed the way I think about how the world works. Or, it helped me realize the way I inherently think about the world. One of those. I consider this the first major event that moved me into the world of computer science later in life. I was above to program this up for the first time in my second intro CS class (Stanford CS106B, C++).

Rules for the grid:\\
1. If one cell is alive, and it has 2 or 3 live neighbors, it stays alive.
2. If one cell is alive, and it has fewer than 2 live neighbors, it dies as if by starvation.
3. If one cell is alive, and it has greater than 3 live neighbors, it dies as if by overpopulation.
4. If one cell is dead, then it becomes alive if it has exactly 3 live neighbors, as if by reproduction.

I added a "rule probability" box, that sets the probability that a given rule will proceed for a given cell in the grid at a given iteration. I don't see this in standard game of life implementations, but biological life has a bit of randomness involved, so why not do the same for this?
Aside from that, I have added the ability to modify the rules for the grid. This includes the ability to determine how may layers out you look for nearest neighbors. Note that when you tinker with these settings, most of the automata you get will either be too orderly or too chaotic. The Game of Life rules are a delicate balance between the two.

I have also added the ability to modify the size of the grid.
** [[./mandelbrot_set.html][Mandelbrot Set]]
Web page.\\

I first came across this in one of my old math books, perhaps in middle school. I just thought of it as a strange cool looking thing at the time, but what I didn't appreciate until later was how simple it was to implement. This is a single html page, under 80 lines in total. Click on any point on the screen to zoom. Note that you do lose resolution if you zoom in long enough.
* Links and contact info
#+HTML: <a href="#top">Back to top</a>
*** [[./tyler_burns_resume.pdf][Resume]]
*** [[https://www.linkedin.com/in/tylerjburns/][LinkedIn]]
*** [[https://twitter.com/tjburns08][Twitter]]
*** [[https://github.com/tjburns08][GitHub]]
*** [[https://burnslsc.com/][Company Website]]





