#+TITLE: Tyler Burns's Website

This is the website of Tyler Burns. I am an American CEO and computational biologist who lives in Berlin, Germany. I am best known for my work on single-cell analysis, with respect to the many applications of K-Nearest Neighbors.

I run a company called [[https://burnslsc.com/][Burns Life Sciences Consulting, GmbH]], which allows me to do science on my terms, work on diverse projects with many organizations, and develop and sell products. The problem is most of my work is behind NDAs so I can't talk about it, so this website is a place where I can openly share my ideas free of bureaucracy. 

* Articles
** [[./just_paint.org][Just paint]]
An anecdote from my aunt. The general premise is that while quality is important in many settings, at the end of the day if you're going to paint, you have to paint. I remind myself of this daily in many different contexts.

** [[https://medium.com/@tjburns_72591/how-to-utilize-scientific-literature-trends-to-gain-intuition-about-a-topic-b5c554e3d280][How to utilize scientific literature trends to gain intuition around a topic]]
The scientific literature is overwhelming, and knowing how to utilize text mining and analytic tools can help you efficiently get what you want out of a literature search. Here, I utilize the PubMed API to find publication rates for particular topics. I show that among other things, single-cell sequencing began out-pacing mass cytometry in 2016. Insight like this helps you see how crowded a field is and especially identify trends.

** [[https://medium.com/coinmonks/how-to-identify-thought-leaders-and-visualize-their-influence-c01aa218090e][How to identify thought leaders and visualize their influence]]
Understanding how authors of a given field are connected can help you identify key individuals to pay attention to. Here is how I utilize the PubMed API to build co-author networks, which lead me to identify thought leaders in a given domain. In this article, focusing on mass cytometry, I identify two types of thought leaders: one exclusive to a particular sub-domain, and one who spans across multiple sub-domains. It is important to know both types when approaching a new topic.

** [[https://medium.com/@tjburns_72591/using-and-mining-pre-prints-to-stay-ahead-of-your-field-with-the-help-of-twitter-50d5bdc528de][Using and mining pre-prints to stay ahead of your field, with the help of Twitter]]
I explain why pre-prints are important to staying ahead of the technology and general paradigms in your field, with single-cell analysis as an example. I then show how I utilize the Twitter API to harvest and rank tweets from automated pre-print linking bots from bioRxiv to determine what pre-print articles are being talked about (and therefore what you should probably pay attention to).

** [[https://www.biorxiv.org/content/10.1101/337485v1][Continuous Visualization of Multiple Biological Conditions In Single-Cell Data]]
Abstract: In high-dimensional single cell data, comparing changes in functional markers between conditions is typically done across manual or algorithm-derived partitions based on population-defining markers. Visualizations of these partitions is commonly done on low-dimensional embeddings (eg. t-SNE), colored by per-partition changes. Here, we provide an analysis and visualization tool that performs these comparisons across overlapping k-nearest neighbor (KNN) groupings. This allows one to color low-dimensional embeddings by marker changes without hard boundaries imposed by partitioning. We devised an objective optimization of k based on minimizing functional marker KNN imputation error. Proof-of-concept work visualized the exact location of an IL-7 responsive subset in a B cell developmental trajectory on a t-SNE map independent of clustering. Per-condition cell frequency analysis revealed that KNN is sensitive to detecting artifacts due to marker shift, and therefore can also be valuable in a quality control pipeline. Overall, we found that KNN groupings lead to useful multiple condition visualizations and efficiently extract a large amount of information from mass cytometry data. Our software is publicly available through the Bioconductor package Sconify.
 
** [[https://pubmed.ncbi.nlm.nih.gov/28094900/][High Throughput Precision Measurement of Nuclear Localization in Subcellular Localization in Single Cells]]
Abstract: To quantify visual and spatial information in single cells with a throughput of thousands of cells per second, we developed Subcellular Localization Assay (SLA). This adaptation of Proximity Ligation Assay expands the capabilities of flow cytometry to include data relating to localization of proteins to and within organelles. We used SLA to detect the nuclear import of transcription factors across cell subsets in complex samples. We further measured intranuclear re-localization of target proteins across the cell cycle and upon DNA damage induction. SLA combines multiple single-cell methods to bring about a new dimension of inquiry and analysis in complex cell populations. © 2017 International Society for Advancement of Cytometry.

* Talks and posters
** "A visual interrogation of dimension reduction tools for single-cell analysis," German CyTOF User Forum; Berlin, Germany; January 2020.
In this talk, I measured the accurracy of dimension reduction tools (PCA, t-SNE, and UMAP) in terms of their nearest neighbor overlap. This is the k-nearest neighbors of a given cell in the original high dimension space, in comparison to the k-nearest neighbors of a given cell in the embedding. I show that the overlap here is much lower than my audience expected. I've given this talk many times since then, for my clients. 
** "A history of mass cytometry data analysis, and where the field is going," [[https://www.drfz.de/en/aktuelles/veranstaltungen/cytof-forum-2020/][German Rheumatism Research Center]]; Berlin, Germany; March 2019.
I talk about how CyTOF data analysis developed from its inception at the beginning of 2010 to now. In doing so, I provide a template for proper CyTOF data analysis in terms of how we got there. 
** “A comprehensive interrogation of the t-SNE algorithm,” German Rheumatism Research Center; Berlin, Germany; May 2018.
This talk was a response to a member of the research institue who was simply not convinced that t-SNE was providing the accurracy that the avearge CyTOF user thought. In this talk, I show that he was right. This being said, I provide recommendations for how to properly use t-SNE for CyTOF analysis. 
** “Determining which distance metrics are ideal within a mass cytometry data analysis pipeline.” [[https://isac-net.org/page/CYTO][CYTO Conference]]; Prague, Czech Republic; May 2018.
SPADE uses the L1 norm (Manhattan distance), X-shift uses cosine distance, and FlowSOM uses the L2 norm (Euclidean distance). Which distance metric should be used for which algorithm? I show that there are indeed differences when using different distance metrics for FlowSOM clustering, though none make or break the algorithm. More work needs to be done here, especially as the dimesnionality of our datasets increase. 
** “Nearest neighborhood comparisons across biological conditions in single cell data.” Invited Speaker, German CyTOF User Forum; Berlin, Germany; February 2018.
This is the talk version of my 2018 Sconify paper, that ended up being the final chapter of my PhD thesis. There are two aspects to this talk. The first is making visual comparisons of unstimulated and stimulated CyTOF data when looking at measurements of phosphoproteins. This was easily done on SPADE trees, but not t-SNE maps, until I started making k-nearest neighbor based comparisons. The second aspect of this talk is using the same nearest neighbor based comparisons to investigate batch effects in CyTOF data. I note that batch effects were only heavily discussed among CyTOF users starting near 2020 (in my circles), and this work goes back to 2016.

* Other things I've done
**** Former computational biologist, now guest researcher, at the German Rheumatism Research Center in Berlin, Germany. I will always stay connected to my academic roots.
**** Developing software to interrogate and visualize the local similarities between original manifolds and lower dimensional embeddings. Important for anyone wanting to determine which of these methods is the right tool for the job.
**** Solved a long-standing data visualization problem for mass cytometry, and developed a Bioconductor package for it, with a visual description here, and this publication..
**** Guest blog contributor for Cytobank, Inc. focusing on how to properly use t-SNE for mass cytometry analysis.
**** Set the best practices in my PhD thesis lab for learning bioinformatics as a classical biologist.
**** Helped develop a wet-lab implementation for a cutting-edge bioinformatics concept, which became part of a patent.
**** Led an international collaboration between my thesis lab (USA) and a laboratory in Uppsala, Sweden, whose biochemical foundations turned into this publication, and helped this one.
**** Mentored several high school students and undergraduates throughout my thesis work, teaching them biology, computer science, statistics, and importantly how to integrate these fields.
**** Built a website for my PhD program using HTML, JavaScript, and SQL, that helped first year students connect with current and previous members of a given research laboratory (I'd link it but you have to be a Stanford student to view it).

* Links
*** [[https://www.linkedin.com/in/tylerjburns/][LinkedIn]]
*** [[https://twitter.com/tjburns08][Twitter]]
*** [[https://github.com/tjburns08][GitHub]]
*** [[https://burnslsc.com/][Company Website]]


