
#+TITLE: Just paint
#+DATE: June 27, 2022 - June 29, 2022

[[./index.org][Home]]

I. My aunt and painting

My uncle and aunt travelled to India for a sabatical. They were there for a few months. My aunt, who is quite the artist, had an idea to "paint India" wherever she went. But when she was there in the moment, getting ready to paint, she would note that things weren't quite the way she wanted them to be. Maybe it wasn't the setting she had in mind. Or maybe the colors she had on the palette didn't quite match what she was seeing. So she wouldn't paint and wait for the next opportunity. And that one wouldn't be quite right either. 

Later on in the trip, having painted far less than she would have liked, she realized the conditions for painting didn't have to be perfect. What was more important for the goal of "painting India" was that she just paint. When she adopted this mentality, everything fell into place and she did what she set out to do.

I come from academia, where you don't publish until your work is as perfect as you can get it. And even then, the dreaded [[https://shitmyreviewerssay.tumblr.com/][Reviewer 3]] has some bone to pick with what you did. So the perfectionist mentality is still in me, slowing down if not stopping what I do. So I get in a similar mindset to my aunt's, where I keep second guessing myself when I'm in the early stages of a project.  

The end result is either I don't show what I'm working on because it's not to my liking, or I decide not to do something because I don't think I'll be good at it or produce something that is "good enough."

II. Mid life realizations

At the time of writing, I am 36 years old. I am one year older than my father lived to be. What does that feel like? Although statistically I'm expected to live [[https://en.wikipedia.org/wiki/Life_expectancy][several decades longer]], it feels like I'm living on borrowed time. What would happen if I died tomorrow? A lot of my thoughts and my work, potential contributions, would die with me. Things I didn't make public because of the academic mentality of hiding things until they're perfect.

Just about every idea we have builds off of the ideas of the past. So I think part of moving humanity forward is sharing what we've got, even if its not perfect. You really never know who it will influence, even if it's only one person who influences someone else, who influences someone else, who influences someone else, who ends climate change by solving cold fusion. It makes me really think about the higher order effects of every action we take. I know there is a lot of randomness in the world, but I at least at take it as a hypothesis that our actions can have profound higher-order influences. It will take a lifetime to test this. What do you have to lose if you think this way?

Just paint. 









