
#+TITLE: Just paint
#+DATE: June 27, 2022 - July 15, 2022

[[./index.org][Home]]

** My aunt and painting

My uncle and aunt travelled to India for a sabatical. They were there for a few months. My aunt, who is quite the artist, had an idea to "paint India" wherever she went. But when she was there in the moment, getting ready to paint, she would note that things weren't quite the way she wanted them to be. Maybe it wasn't the setting she had in mind. Or maybe the colors she had on the palette didn't quite match what she was seeing. So she wouldn't paint and wait for the next opportunity. And that one wouldn't be quite right either. 

Later on in the trip, having painted far less than she would have liked, she realized the conditions for painting didn't have to be perfect, and the resulting output doesn't have to be perfect. What was more important for the goal of "painting India" was that she just paint. When she adopted this mentality, everything fell into place and she did what she set out to do.

I come from academia, where you don't publish until your work is as perfect as you can get it. And even then, the dreaded [[https://shitmyreviewerssay.tumblr.com/][Reviewer 3]] has some bone to pick with what you did. So the perfectionist mentality is still in me, slowing down if not stopping what I do. So I get in a similar mindset to my aunt's, where I keep second guessing myself when I'm in the early stages of a project.  

The end result is up until recently either I wouldn't show what I'm working on because it's not to my liking, or I would decide not to do something because I didn't think I'll be good at it or produce something that is "good enough." As if Reviewer 3 is breathing down my shoulder at every waking moment.

There are two components to the concept of "just paint" that I am outlining here. The first is not being afraid to "just paint" even if the conditions are not perfect and you don't think your work is going to be perfect. The second component is not being afraid of showing your imperfect painting when you're done. The next section will talk about the latter point, showing imperfect work in the context of domains (like mine) where rigor is demanded of you.

** Psychological momentum

"Just paint" is the first step toward gaining psychological momentum. I'll loosely define that as the probability that I will do the next step of a task given that I do this step. Psychological momentum is critial to my work as a programmer, as it is to my aunt as a painter. If I want to tackle some problem, I have to get started. I have to make a little bit of progress. This makes it easier for me to make a little bit more progress, which makes it easier, and so forth. Before you know it, several hours have gone by. I was in the zone.

Cognitive scientists often call this flow state. It is often associated with games, as there is a well-defined task you have to complete with quantifiable metrics for performance and deliberate feedback at every step. The brain likes flow state. Anyone who has played an addictive game knows this. The one I'm thinking about is [[https://en.wikipedia.org/wiki/2048_(video_game)][2048]], which was release in 2014 the week before finals back at Stanford (and any school on the quarter system), much to the detriment of the undergrad population.

For my work, I like to think of this as momentum. Specifically, I like to think of it as getting a train up to speed. It takes a lot of energy and time, but once it's at cruising speed, it will be very difficult to stop. I only came across the term psychological momentum recently, in [[https://pubmed.ncbi.nlm.nih.gov/27630603/][this paper]]. I think it describes my style of work even better than flow state.

For me, starting the process of "just painting" is the hardest part. Often the problem I'm trying to solve is very complex, or not particularly well defined, something that is also known as a [[https://en.wikipedia.org/wiki/Wicked_problem][wicked problem]]. How do I solve these problems? In software engineering, one of the first things you learn is [[https://en.wikipedia.org/wiki/Decomposition_(computer_science)][problem decomposition]]. Importantly, for me in this regard, the goal in the early stages is not to solve the problem (although my approach pushes me in that direction). It is to get psychological momentum. It is to just paint. It is to get the train up to speed. It's a subtle difference in focus. How do I do that? If I can't quickly decompose the problem into some actionable piece (eg. it's a wicked problem), I just start working on a simpler but related problem.

I first saw this strategy used in 2010 by a friend of mine who was working in fasion design. Her job for the day was to draw out prototypes of dresses. She had a notebook with hundreds of them. The day we were both working together (on our respective projects) at a cafe, and she had a bit of a "drawing block" and couldn't get started. So she went on wikipedia and started reading about art and fasion in different time periods in history. She explained to me that she always does that when she's stuck. It's not her task but it is sufficiently related that it gets things started. It gives her enough psychological momentum to get the pencil to the paper. 

This strategy is beautifully described in this [[https://www.youtube.com/watch?v=neA0NJNUEfM][beautiful lecture]] from Prof Emeritus Robert G. Gallager on Claude Shannon's problem solving style. Again: solve a simpler but related problem. That's it. One example from my life: when I took CS106A at Stanford, one of the problem sets had us design Atari's Breakout. That was a hard problem for a complete beginner like me. A simpler problem was to get a single ball bouncing around on the game board. Still too much for me. Maybe I could just get a ball moving anywhere on the game board even if it ends up off screen. Nope, too much. Ok fine, no movement. Just a single ball anywhere at all on the game board. No movement. Nothing else. Just board and ball. Ok that worked. I did things like that for quite a while in the beginning. Anyone watching me would say that I could be a bit more methodical. But that came later. The absolute most important thing for me is getting psychological momentum. Once I have that, then the proper "best practices" of problem solving show up naturally. 

** Showing imperfect work but remaining rigorous

At the time of writing, I am 36 years old. I am one year older than my father lived to be. What does that feel like? Although statistically I'm expected to live [[https://en.wikipedia.org/wiki/Life_expectancy][several decades longer]], it feels like I'm living on borrowed time. What would happen if I died tomorrow? A lot of my thoughts and my work, potential contributions, would die with me. Things I didn't make public because of the academic mentality of hiding things until they're perfect.

But I'm working in medical research and bioinformatics. These are fields where you have to maintain a high level of rigor. How do you [[https://en.wikipedia.org/wiki/Dialectic][reconcile]] this with the idea of something not needing to be perfect to show it to the world? The strategy I'm taking, inspired by [[https://www.lesswrong.com/posts/Psr9tnQFuEXiuqGcR/how-to-write-quickly-while-maintaining-epistemic-rigor][this article]] by johnswentworth on LessWrong, is to continue being a perfectionist when it comes to finished products, but to share what I'm working on a bit more often. If it's not perfect, I'll talk about where I'm at in the project, what I've observed so far, how I interpret these observations in the present moment, and where I'm going with it.

We already do this in academia at lab meetings, internal departmental retreats, and conferences. I think the difference here for me is that I'm simply sharing my work publically a bit more often rather than signing up for a talk for some conference in two months. I'm no longer afraid of getting [[https://www.youtube.com/watch?v=6Pf8a1a6Ak0&t=31s][scooped]] (been there), because I am no longer in the academic "[[https://en.wikipedia.org/wiki/Publish_or_perish][publish or perish]]" incentive structure. Even if all my ideas are stolen and published elsewhere, I can still point to them on my website to show my clients how I'm going to add value to their organization. Different incentive structure.

** Long content: always revising

This section, and my general approach to producing and showing work, is inspired heavily by this piece by AI and tech writer Gwern on the concept of [[https://www.gwern.net/About#long-content][Long Content]]. In short, I consider everything I show to be constantly evolving. If you look at the date for this artcile and the others you'll see a date range. Chances are at least for a time, if you come back to this article or any other article on my website, you'll see it change. There is no law against this. We think of blogs, pubications, books, posts, as static documents. Snapshots in time. But what I'm thinking right now, at least in some contexts, is that it doesn't have to be that way. 

A lot of my ideas now, that lead to my company's profit and my continued growth, can be traced back to my [[./Burns.Dissertation.Final.pdf][PhD thesis]]. This being said, I often cringe at my old work. As a thought experiment, what would happen if I spent an hour a day for the rest of my life simply revising my PhD thesis as my ideas matured? What would my thesis look like at the end of my life? Not that I'm going to do that, but that is how I plan to treat anything I post.

I encourage you to ask yourself similar qustions. What would your work look like if you slowly revised it for the rest of your life, rather than considering it done forever and jumping to the next thing? That doesn't mean that J.K. Rowling should have stopped halfway through writing Harry Potter and the Sorcerer's Stone and just revised that for the rest of her life. I'm talking about instances where you see your work having a common thread. An idea that you developed years ago that seems to keep coming back again and again in your work. This is the instance where perhaps you should consider going back to the original documents with this idea and do the "long content" appraoch.

** Long content: dopamine optimization

Another potential benefit to this approach: dopamine optimization. To clarify, I'm talking about dopamine in the context of our motivation circuitry, not the so-called "dopamine hits" that you get when someone likes your social media post. Dopamine affects motivation to do a thing rather than reward from doing a thing. Quite a lot of work has been done here. I envourage you to listen to [[https://www.youtube.com/watch?v=QmOF0crdyRU][this podcast by Andrew Huberman]] where he sums up the recent research and take-home points around dopamine.

One of the key findings he explains is the idea that dopamine is effectively maximized when one seeks reward from the process rather than the outcome. For example, a runner who is training for a marathon would experience high levels of dopamine prior to the event, but then a dip below baseline after the event that would potentially manifest as [[https://www.runnersworld.com/runners-stories/a20804968/the-postrace-blues/][depression]]. On the other hand, a runner who simply enjoys running for its own sake would be less likely to experience this dip.

I have direct experience here. I go to the gym for its own sake, an it has led to me playing a much longer game: I've worked out consistently since 1999, and I am going to guess that my dopamine pathways are properly optimized here. The reward is in the act of working out itself, not the fitness goals. I haven't talked to any dopamine experts about this exact "long content" context yet, but the idea here is if you completely remove the idea of "finishing" your work, then you might be able to tap into this "seek reward from the process" heuristic and therefore have higher and/or more stable dopamine levels, leading to more general motivation to do what you do.

** Conclusion: your web of influence

Just about every idea we have builds off of the ideas of the past. So I think part of moving humanity forward is sharing what we've got, even if its not perfect. You really never know who it will influence, even if it's only one person who influences someone else, who influences someone else, who influences someone else, who ends climate change by solving cold fusion. It makes me really think about the higher order effects of every action we take. I know there is a lot of randomness in the world, but I at least at take it as a hypothesis that our actions can have profound higher-order influences. It will take a lifetime to test this. What do you have to lose if you think this way?

Just paint. 









