
#+TITLE: Just paint
#+DATE: June 27, 2022 - June 27, 2022

My uncle and aunt travelled to India for a sabatical. They were there for a few months. My aunt, who is quite the artist, had a grand idea to "paint India" wherever she went. But when she was there in the moment, getting ready to paint, she would note that things weren't quite the way she wanted them to be. Maybe it wasn't the setting she had in mind. Or maybe the colors she had on the palette didn't quite match what she was seeing. So she wouldn't paint and wait for the next opportunity. And that one wouldn't be quite right either. 

So later on in the trip she realized that the nitty gritty didn't matter as much as she thought it did and she needed to just paint. When she adopted this mentality, everything got better. The key was to just paint.

So I come from academia, where you don't publish until your work is as perfect as you can get it. And even then, the dreaded Reviewer 3 has some bone to pick with what you did. So the perfectionist mentality is still in me, slowing down if not stopping what I output.

The end result is I have thousands of pages of journal entries and notes to myself that have never seen the light of day because they're never quite what I want them to be. So when my aunt told me of her trip to India, and when she told me to do what she does now and "just paint," everything clicked.

You're going to be on this earth for 80 years or so, and then you're gone. Show people what you do. Just paint. 


