
#+TITLE: Just paint
#+DATE: June 27, 2022 - June 28, 2022


My uncle and aunt travelled to India for a sabatical. They were there for a few months. My aunt, who is quite the artist, had a grand idea to "paint India" wherever she went. But when she was there in the moment, getting ready to paint, she would note that things weren't quite the way she wanted them to be. Maybe it wasn't the setting she had in mind. Or maybe the colors she had on the palette didn't quite match what she was seeing. So she wouldn't paint and wait for the next opportunity. And that one wouldn't be quite right either. 

Later on in the trip she realized that the nitty gritty didn't matter as much as she thought it did and she needed to just paint. When she adopted this mentality, everything got better both in terms of productivity and satisfaction. The key was to just paint.

I come from academia, where you don't publish until your work is as perfect as you can get it. And even then, the dreaded [[https://shitmyreviewerssay.tumblr.com/][Reviewer 3]] has some bone to pick with what you did. So the perfectionist mentality is still in me, slowing down if not stopping what I output. 

The end result is either I don't show what I'm working on because it's not to my liking, or I decide not to do something because I don't think I'll be good at it or produce something that is to my liking. 

You're going to be on this earth for [[https://en.wikipedia.org/wiki/Life_expectancy][80 years or so]], and then you're gone. We are here, at least in part, to express ourselves. As Alan Watts likes to say, [[https://www.youtube.com/watch?v=nesFD_XcNz4][life is a musical piece]], and we are supposed to sing and dance while the music is being played. Just paint.










