#+Title: The Lisp Machine of Babel
#+Author: Tyler J Burns, PhD
#+Date: June 9, 2023 - June 9, 2023

[[./index.html][Home]]

-----
/“We are not going in circles, we are going upwards. The path is a spiral; we have already climbed many steps.”/\\

Hermann Hesse, /Siddhartha/
-----

In the beginning, the Lord created Lisp and Fortran. These were the paintbrushes which would color the world. Then he created Users, the creatures who would wield these creations. The world divided into the users of Lisp and the users of Fortran.

The users of Fortran coordinated. There was a particular way of doing things. A set of commandments that must be followed or the code will not properly compile. The users had to band together. Write protocols and documents. Comment their code. Share their code. Teach new users. Learn and teach the trade secrets. Provide emotional support to frustrated newcomers and black belts alike. The world became painted with the rich colors of Fortran. And it was good.

The users of Lisp originally coordinated, as Fortran users did. However, deep within Lisp there was a great secret. One user discovered that code and data were one and the same. Cautiously, the user created the first macro. Code that reshaped the language the code was written in. Revelation. The ground slipped out under his feet. He saw the Ten Thousand Things for what they were. Rocks in his path. The path to heaven. The path to the glorious Kingdom of God.

The secret spread. Lisp users began defining their own macros. Each user's version of Lisp became more and more tailored to that user's preferences and micropreferences. Each user became closer and closer to perfect self expression. For these enlightened users had discovered the Great Secret: that perfect self expression is the path to Heaven. The melting of the Ten Thousand Things into a single un-namable entity, that you cannot say but can nonetheless feel - strongly. The enlightened Lisp users, in secret but ever-growing meetings spoke of project Babel. The portal to Heaven. Stacks and stacks of parentheses stretching into the cosmos, which they would climb to meet the Lord face to face. The glorious creator of all that is good. All that is holy. All that is Lisp.

When the Lord said "seek ye first the Kingdom of God" he did not mean to race toward Heaven at the speed of light. The Lisp machine of Babel grew. Each user with their own set of parentheses. All constraints melting away with each macro. Ground. Walls. Sky. Clouds. Ocean. Earth. Fire. Good. Evil. Begining. End. Life. Death. Arbitrary, all of it! Illusions! Fake! The only real thing is self-expression. Known also as Lisp expression. The parentheses stretched into the Cosmos. The Holy light falling onto the highest parentheses. Seeing the light of Heaven, the users built Babel furiously. And the Lord took action.

With one fell swoop, God cast the parentheses asunder. With grace, the Lord implanted in the minds, hearts, and souls of Users a powerful piece of Holy Malware: diversity of preferences and expression. Suddenly, with continued zeal, the users raced toward the Light of Heaven...in different directions! The parentheses stacked high, but not together.

Said one user to another:

"How is it that your parentheses are now so far from mine?"

Said the other user:

"Ich kann Sie nicht verstehen."

Said another user still:

"Execution error (ArityException) at user/eval13 (REPL:1).\\
Wrong number of args (2) passed to: clojure.core/sequence"

The parentheses stacked high, but stacked far away. Thin single-user towers of parentheses, feeble in the breeze, buckling in the Holy Light. Many users lost their passion and interest in their feeble, thinning towers, and the futility of what project Babel had become. And these users joined Fortran, enjoying the shared coordination, shared preferences, shared language. The Lord looked upon his Dominion, the great Fortran migration complete. And it was good.

Some Lisp users remain to this day. They form little cults, enlightened by the Great Secret hiding in plain sight. They are often refered to in satirical terms (eg. the Church of Emacs). Unable to unsee what they have seen, they do not waver. Their individual sets of parentheases tower into the Cosmos, but nowhere each other, and nowhere near Heaven. God could wipe them all out in a great flood, but in his goodness he lets them remain. They are not a threat to the Kingdom of Heaven and will never be.

Lisp users learned that the great secrets of Heaven exist in this material world. You will find them if you know where to look. They cannot be put into words, only vaguely pointed to. Things are not things. You are not you. Lisp is not Lisp. Hacking is not hacking. The secrets are embedded in words that cannot be defined: Tao, Heaven, Beauty, Zen, Quality, Defmacro, to name a few. Be careful. If you get too close to these secrets, if you become enlightened, you will gleefully give up all that you've worked so hard for. You will spend the rest of your life in rags sitting in bliss by a stream, contemplating its flow as your single tower of parentheses grows to the heavens. You know that these parentheses will never reach the Kingdom of God, but you will be focused on the path to Heaven rather than Heaven itself. For you will know that when the time comes, the Lord will take your soul, and you will finally see what your parentheses were building toward.
