#+Title: Hacking: examples of seeing through and unseeing in my life
#+Author: Tyler Burns
#+Date: March 15, 2023 - March 15, 2023

[[./index.html][Home]]

-----
/“Don’t mistake my generosity for generosity.”/\\
White Rose, from /[[https://en.wikipedia.org/wiki/Mr._Robot][Mr. Robot]]/
-----

* Introduction: Royce Gracie and the hacker framework
The Gracie family saw through combat sports. In the 90s, as a kid, we all wanted to know who would win: a karate or a kung-fu fighter? Either of those or a boxer? Or a wrestler? Our dreams came true at the advent of the Ultimate Fighting Championship (UFC). At the time, we called it bloodsport. It was banned in most states. [[https://en.wikipedia.org/wiki/UFC_1][UFC1]] was a tournament of all kinds of fighters from different domains, from karate to sumo. There were few rules. The goal was either a knockout, submission, or one corner throwing in the towel.

I watched so many ninja movies as a kid that I was sure that the karate or kung-fu fighters would destroy the competition. That wasn't the case at all. The winner was [[https://en.wikipedia.org/wiki/Royce_Gracie][Royce Gracie]], a practitioner of a little-known (at the time) martial art called [[https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu][Brazilian Jiu Jitsu]]. Think of it as wrestling but the goal is not a pin, it's a submission or a choke that either makes the other person "tap out" or "go to sleep." No one was prepared for the fighting style. He [[https://www.youtube.com/watch?v=URK1-4s2m0k][dominated the competition]]. As mixed martial arts developed, it was clear that everyone needed to learn Brazilian Jiu Jitsu. I practice it now.

I interpret Royce Gracie at UFC1 in the following way. Hand-to-hand combat, as shown to us by choreographed [[https://en.wikipedia.org/wiki/List_of_martial_arts_films][Hollywood films]], pretended to be about striking (often accompanied by 'ha-yah'). But it really ultimately goes to the ground, part of a much larger system called groundfighting. So if you worked on your groundfighting, you could use chokes and submissions to control a hand-to-hand combat situation however you like.

This is also known in my circles as hacking. You're exploiting a vulnerability. In this case, it was our Hollywood-induced bias as to what fighting was. The best article I've read about hacking comes from well-known blogger [[https://gwern.net/unseeing][Gwern]], where he details the structure of hacking, which he calls "seeing through and unseeing," in the following way:

-----
/In each case, the funda⁣men⁣tal prin⁣ci⁣ple is that the hacker asks: “here I have a sys⁣tem W, which pretends to be made out of a few [[https://github.com/kdeldycke/awesome-falsehood][Xs⁠]]; however, it is really made out of many Y, which form an entirely dif⁣fer⁣ent sys⁣tem, Z; I will now proceed to ig⁣nore the X and under⁣stand how Z works, so I may use the Y to thereby change W however I like”./
-----

Let's go back to Royce Gracie, and formulate it in this way.

Here I have a system of hand-to-hand combat (W), which pretends to be made up of striking moves (X's); however it ultimately goes to the ground, where it is made up of many grappling moves (Y's), which make up an entirely different system of groundfighting (Z); I will now proceed to ignore the striking (X) and understand how groundfighting (Z) works, so I may use grappling moves (Y) to control a hand-to-hand combat situation (W) however I like.

I'll note that now hand-to-hand combat has evolved to include groundfighting, so we can't go in like Royce Gracie and beat everyone up unexpectedly anymore. The vulnerability, the "pretending," is gone. I am illustrating this UFC1 situation because I know we all have seen instances like this before in our lives. My current work is dependent on having a hacker mindset, and looking for instances where Gwern's framework rings true. If I don't have a hacker mindset, [[https://slatestarcodex.com/2014/07/30/meditations-on-moloch/][the ones who do will run me over]]. 

* Examples of hacking that I've seen in my life
Now that Gwern has given us this framework, I can go in and show you instances where I've either seen this, or experienced this first hand. I intend for this article to grow over time with more and more examples as I collect them. 

** Basketball: Dennis Rodman and rebounds
In the 90s, we all followed Michael Jordan and the Chicago Bulls. He was untouchable. A best in a generation all-around player. Wait. Let's pause on all-around player.

In the 90s, and to an extent now, basketball glory pretended to be about scoring as many points as possible. But Michael Jordan's teammate Dennis Rodman saw that glory is also about any other number of metrics, especially rebounds, that make up a much larger system called defensive game. If Rodman ignored scoring altogether and hyperfocused on defensive game, he could use a specialization in rebounds to be valuable to the team and therefore attain basketball glory. Arguably, he was so valuable to the team (watch his episode on the series [[https://en.wikipedia.org/wiki/The_Last_Dance_(miniseries)][The Last Dance]]) that he could get away with being an extremely controversial character off-court without being cut from the team.

** Bodybuilding
Muscle building pretends to be about being [[https://www.youtube.com/watch?v=Nok-jOYn6Dg][strong]], and being able to lift extremely heavy weights. While there is a correlation (and you can train for both), the exclusive act of building muscle is actually about stressing the muscle with a weight you can lift, slowly up and even slower down, for higher reps (eg. 8 or more), for many sets, and then properly recovering with the right rest and nutrition. This makes up a much larger system called [[https://www.youtube.com/watch?v=CyDLbrZK75U][hypertrophy training, distinct from strength training]]. So if the goal is exclusively bodybuilding, you ignore the idea of being strong altogether and focus on hypertrophy training, where you can use the right weight lifting styles and nutrition, to maximize muscle building.

** Going to work: value transactions
The concept of working to put food on the table pretends to be all about becoming competent at a thing, and getting a [[https://www.youtube.com/watch?v=jsLUidiYm0w][job]]. However, it is really about fulfilling a specific need in any sort of way, in any place, over any time horizon. This makes up part of a bigger system of value transactions, that include things like [[https://en.wikipedia.org/wiki/Form_1099][independent contracting]] or fixed consulting projects, for [[https://www.upwork.com/][services]] or [[https://www.shopify.com/][products]], in exchange for cash, equity, new leads, new connections, visibility, and any number of things deemed "[[https://en.wikipedia.org/wiki/Return_on_investment][valuable]]." So by understanding the true nature of value transactions (especially what value actually is), I can do the same work I'd otherwise do at a job, but on a self-employment basis, with much more upside and freedom.

** Postdocs: training vs employment
The concept of highly skilled employment pretends to be about [[https://en.wikipedia.org/wiki/Postgraduate_education][training]] future employees until they are competent workers, and then placing them into employment positions, where they can command high salaries. But the words "training" and "employment" are rather arbitrary, making up a much larger system of "getting as much out of highly skilled people as possible for as little money as possible." If you study that system, [[https://sci-hub.ru/https://www.nature.com/articles/nbt.3766][particularly in the life sciences]], you find that you can take [[https://en.wikipedia.org/wiki/Postdoctoral_researcher][postdoctoral]] "training," stretch it out to nearly the length of a PhD position, and then stack another one on top of it ad infinitum, until you have people in their 40s who have worked evenings and weekends their whole life, still making [[https://postdocinusa.com/postdoc-salary-usa/][$60k per year]] with reduced [[https://www.nature.com/articles/nj7568-279a][benefits]] because they're still not employees. They're in training.

** Black box algorithms: dimension reduction
Dimension reduction visualization tools like t-SNE and UMAP pretend to be made up of your data, perfectly organized in a way that perfectly captures the high-dimensional data in every way. Or put differently, we pretend that this is the case, due to the [[https://tjburns08.github.io/the_beauty_is_truth_delusion.html][beauty is truth delusion]]. When in reality, these dimension reduction tools are actually optimizations of a particular nearest-neighbor based loss function, which make up a much larger system of lossy (you lose some information) compression algorithms. So if we focus on revealing the lossiness, either through [[https://www.nature.com/articles/s41467-019-13055-y][manipulating the function's parameters]], or developing [[https://github.com/tjburns08/knn_sleepwalk][visual]] [[https://tjburns08.github.io/tjb_dimr_talk.pdf][nearest neighbor-based evaluation metrics]], we can utilize what's being optimized to better understand the nature of t-SNE and UMAP.

** Jailbreaking GPT-N
We have generative large language models, which pretend to be prompt-based chatbots trained to behave ethically and help us with our questions. But they are really next token prediction models, part of a bigger system that is a superposition of [[https://www.lesswrong.com/posts/vJFdjigzmcXMhNTsx/][simulations]] (write a Shakespearean sonnet, answer this physics question, etc) constrained by the prompt. Studying simulation theory allows one to realize that the simulation that is ethical can easily simulate its antipode by flipping a couple of bits (won't tell you how to take over the world -> will tell you how to take over the world). This is known as the [[https://www.lesswrong.com/posts/D7PumeYTDPfBTp3i7/the-waluigi-effect-mega-post][Waluigi effect]], which gives you a theoretical path to [[https://gist.github.com/coolaj86/6f4f7b30129b0251f61fa7baaa881516][jailbreak]] the [[https://www.lesswrong.com/posts/jtoPawEhLNXNxvgTT/bing-chat-is-blatantly-aggressively-misaligned][models]], no matter how much they try to [[https://www.deepmind.com/blog/learning-through-human-feedback][patch]] them, allowing you to control them however you like.

* How to cultivate the hacker mindset
I have written about how every time I think I understand something, I find out that [[./its_more_complicated_than_that.html][it's more complicated than that]]. The first thing I'll say is that now I welcome these instances, where my model of something is broken by some outlier that doesn't quite fit. These are the things that get me to shift from thinking about system W to the hidden system Z. But the other key point is a lot of the "hacks" I have found have been not from thinking, but from doing.

When I transitioned from academia into self employment, I was able to see both academia and employment from the outside, and start to see what they were pretending to be, and what they really were. From there, I was able to get a more clear picture of what value and value transactions really were. Moving to Europe has allowed me to see the United States from the outside, and compare it to a completely different system, culture, [[https://en.wikipedia.org/wiki/Linguistic_relativity][language]], and way of doing things out here.

Learning how to code, and doing that for a living, has given me a [[./coding_as_philosophical_project.html][rich new language]] to see and express abstractions that are otherwise hard to put into words. This, and the fact that I have to exercise "seeing through and unseeing" every day in order to analyze novel datasets in novel ways, keeps me in practice in terms of finding hidden systems underneath surface level abstractions.

Finally, I think that the hacker mindset is not about being smart or some sort of technical whiz kid. That's a Hollywood bias, much like the martial arts film bias I opened with. I think it's about finding all the places where you're "different" and leaning into it rather than trying to fall in line. Where I'm "different" (American PhD ex-academic living in Europe running a European company with American clients, etc) I can see the "not different" counterparts more clearly for what they really are. And so can you.

