#+Title: Buddhism is to mindfulness, as Christianity is to...
#+Author: Tyler Burns
#+Date: January 8, 2025 - January 8, 2025

[[./index.html][Home]]

-----
/Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things./

Phillipians 4:8, The Bible, [[https://www.biblegateway.com/passage/?search=Philippians%204%3A8&version=NIV][New International Version]]
-----

I will preface by saying that I am not a practicing Christian, through I grew up in a Christian family, and so I can speak to the religion. In general, given that society has done a good job steelmanning Buddhism and taking practices like mindfulness directly out of the religion for secular use in the west, I wanted to do a similar thing for Christianity. But first, a story.

So far as I understand, many boys have a phase in their childhood where they view their father as somewhat of a Superman. The strongest, smartest, kindest, bestest man in the whole wide world. I myself very much went through that phase when I was a small child, with my father. I remember thinking of him as a literal Clark Kent, hanging on to his every word and every move.

And that is when he died.

What this did to my young brain is keep me in the "Dad is Superman" phase, indefinitely. I am still in that phase today, in my late 30s, actually older than my father ever got to. This infinite loop pushed me to work harder. I had to get smart like my Dad and strong like my Dad, and so forth. But the "Dad" in my head was not the great but imperfect human being that my father was (by that I mean no one is perfect). The "Dad" in my head was an impossible Jungian archetype that I had constructed over years and years. Whatever good virtue or characteristic, crank it to 11, and I convinced my young self that my Dad was exactly like that. And so I pushed harder to become more like this impossible vision of ultimate good that was my father.

When I became older than my father, there was a minute where this started to get toxic. I realized what was going on. I realized that I was essentially worshipping an impossible ideal rather than my actual father. That comparison, the infinite delta between imperfect me and this perfect ideal was a bit tough on my mental health, especially because I was transitioning from "the man I am becoming," my poential, to "the man I have become." And while I am proud of and thankful for what I have achieved, I did not become Superman.

But then after a few more years, I realized that basically the Christian religion (the one I can speak to...I suspect other religions are like this too) is at least in part an exercise of imagining the absolute most perfect human being possible, and trying to move in that direction. The common phrase "what would Jesus do" is basically this.

And at that point I realized that the "father worshipping" algorithm that had been running in my head my whole life was not much different than what Christians do day to day. And so I stopped shying away from it. It's not that I was trying to be like my father. I was trying to be like the most ultimate ideal of human I could possibly imagine, and my father had done me enough good when he was alive that he could serve as a seed, from which I could build this ideal vision.

And just as we have taken mindfulness out of Buddhism, I propose the following perfectly secular exercise from Christianity: imagine the greatest possible human being. Perfect kindness, perfect competence, perfect virtue, whatever you can think of. Hold that image in your head. This is comparable to religious contemplation. What would that person do in your situation? What steps can you take to become more like that ideal person? Who in the real world exemplifies what facets of this ideal person? What does the opposite of this ideal person look like, and how do you make sure that you don't go that route? In what ways are you going that negative route and how can you reverse the course?

For what it's worth, this is the exercise I have been doing unconsciously my entire life since I lost my father. And it's only recently that I have realized what I was doing, and have generalized it, and it therefore continues to benefit me. At the time of writing [2025-01-08 Wed] there is a lot of talk about meditation and mindfulness, but very little about this. If you're into these secularized religious/spiritual practices, try this one on for size. It has been a huge positive force in my life, and maybe it will be for you, too.
