#+Title: Psychotherapy should be as normal as going to the gym
#+Author: Tyler Burns
#+Date: February 7 - February 7

[[./index.html][Home]]

-----
/“Difficulties strengthen the mind, as labor does the body.”/\\

Lucius Annaeus Seneca
-----
* Psychotherapy is modern stoicism
In the past few years, there has been a renewed interest in Stoic philosophy. If you don't know what this is, it's a set of philosophical practices for dealing with hard times, coming largely from ancient Rome roughly 2000 years ago. It has been popularized again in part by people like [[https://www.youtube.com/@DailyStoic][Ryan Holiday]], who does a great job distilling and explaining the principles of the Stoics. The original Stoic philosophers include people the likes of Roman Emperor Marcus Aurelius, who practiced abnormal levels of self-restraint to focus on his responsibility to rule the empire, to Epictetus, an abused slave who was able to endure it through Stoicism and see eye-to-eye with Marcus Aurelius. To illustrate the breadth of current interest in Stoic philosophy, Ryan Holiday's talks and books have influenced audiences ranging from professional sports to the US military. His book The Obstacle is the Way has sold over one million copies. I myself have been interested in Stoicism for the past several years, and it has indeed helped me get through hard times.

But we have to note that Ryan Holiday's teachings are grounded in philosophers who are 2000 years old. A lot has happened since then. Who has updated the stoic code base in the past 2000 years, in light of all the innovation that has happened across the world everywhere else? You wouldn't simply read these books, and not add to the knowledge base that is Stoicism for 2000 years. If you were interested in physics, you wouldn't read Newton and stop there. But that's how modern Stoicism seems. If Stoicism is Newtonian physics, then what is the equivalent of relativity and quantum mechanics? The answer is that there have been plenty of updates to Stoicism, but it goes by a new name in the modern world: psychotherapy.

* We learn about physical health early in life. Why not mental health?
If psychotherapy is philosophically grounded in Stoicism, and there is tons of interest in Stoicism right now, then shouldn't there be tons of interest in psychotherapy? Would Ryan Holiday do well by teaching the world basic psychotherapy practices, perhaps by having psychotherapists of different sorts as guests on his podcast, where he could derive a dialectical synthesis of what they say and what Marcus Aurelius said 2000 years ago (I would really enjoy this)?

More interestingly, should we all be learning and/or doing psychotherapy early in life? Plenty of people out there, including myself, have been through psychotherapy. How it went for me was I waited until things got pretty bad and then I went. There, I learned a set of tools that I otherwise totally wouldn't have known from any other source I had encountered up until then. Some people never go, and preventable things get worse and worse. Bad mental health can do a number on someone's life. What would happen if we all learned and practiced the basics of psychotherapy as kids or teenagers? What if it were part of the school curriculum, just as physical education is?

Imagine if it was custom to not go to the gym or learn how to eat healthy until you were 100 pounds overweight, with a well-oiled "junk food to mouth" reflex? Then you have a breakdown and your loved ones tell you that you need to...go to the gym, eat right, and see a personal trainer. Imagine that the gym was called unfit-therapy or something like that. Imagine that there was a stigma associated with doing cardio and weight training, to the point where people would say "yeah, I've been having some trouble with my physical health but I don't think I need unfit-therapy. I'm fine." The world would be a much more unhealthy place. Yet many of us are mentally unhealthy, to the point where many people agree that we're in the middle of a mental health crisis. 

Now imagine that as kids you learned basic mental health concepts. Imagine that kids learned the different strategies for dealing with pain, loss, expressing one's feelings, habit formation, finding purpose, and conflict management, among other things, at the level of modern clinical psychology. Now granted, we did this a little bit in elementary school and again in high school health class (maybe one or two weeks out of the five week class), but that was more of a teacher by teacher and situation by situation basis. So far as I understand, this was not a job requirement but I had some great teachers.

* Psychotherapy as Stoic resilience training
What I propose is that psychotherapy gets normalized enough to encompass a greater spectrum of mental health needs. In other words, you don't wait until you're clinically depressed to go. In fitness, where I have decent experience, you have the gym and you have personal trainers. For more serious and/or tailored issues, you have physical therapists. I see psychotherapists as the physical therapists of the mental health world. But what seems to be missing is that which is analogous to personal trainers, physical education teachers, and basic knowledge of exercises (what is the mental health equivalent of push-ups?). As an ode to Stoicism, we could call it something like Stoic resilience training. My hormone-fueled egotistical teenage self would probably be happy with having a Stoic resilience trainer who would make me a tougher man, something that would probably have prevented a handful of problems I had in my 20s.

Now I'm not a psychotherapist, but I was a certified personal trainer for a while and I can speak about the fitness industry by analogy. As such, I don't have any steadfast solutions for what to do next, but I do have a few questions.
- How can we take the huge body of knowledge that is modern psychotherapy and distill it to the masses in a practical manner, just as Ryan Holiday does with Stoicism?
- How can we remove the stigma of psychotherapy in light of the huge interest in Stoicism? Is it enough to re-brand psychotherapy as modern Stoicism?
- What would the equivalent of the gym and personal trainers look like for mental health, if we assume that psychotherapists are the equivalent of the physical therapist?


