#+Title: Purpose-driven versus purpose-less
#+Author: Tyler Burns
#+Date: December 18, 2022 - December 18, 2022

[[./index.html][Home]]

* Introduction

At some point in my life, I learned that I need to set goals and be oriented by goals. The Christians in my life told methat I need to find my God-given purpose and pursue that. Then Eastern philosphy taught me that wanting and chasing anything will lead to suffering. Then I read James Clear's Atomic Habits, and I learned that building habits that slowly move us toward our goals is a good approach. To an extent, different activities in my life are oriented toward goals and higher purpose, and habits independent of goals or purpose.

I'll talk about activites in my life that are purpose-driven and purpose-less and build a synthesis of these two buckets in the end. Both perspectives are valid and the extent of the use of each perspective will depend on the activity and the situation, but I think for me, purpose-driven activities have given me an emotional dependence on positive outcome that is more of an impediment than not these days. To de-bug this has been helpful in my day to day life. 

* Driven by purpose

Here, I show three examples from my life of having some larger goal or purpose that I'm chasing. On a positive note, each of these larger goals perhaps pushed me harder than I would have pushed had I not had them. On the other hand, I've been let down in terms of how I thought it would feel to achieve the goals associated with them.

** My PhD
I spent a huge chunk of my life pursuing a PhD, which in many ways was a sacrifice of my 20s. It started with the prep work in undergrad, then a lab tech position to sharpen my skills for a few years before grad school, and then six years in grad school. What was it like the day I defended my thesis and received my degree? It was nice, but it was also a bit of a let down.

Don't get me wrong, I was happy to have received the degree and I wouldn't change anything if I could go back and start over, but I thought it would feel like scoring a goal in soccer, but 10 years of scoring goals packed into a single moment. It didn't feel like that all. It felt surprisingly empty.

What didn't feel empty was the day-to-day pursuits of intellectual curiosity. That was not going to stop after grad school. Perhaps that is why it felt so empty. The things I did to get my PhD would not change now that I had it. 

Although I felt a bit empty after receiving my PhD, no point during my pursuit of the PhD did I feel empty. It got me out of bed in the morning. There was something huge that I was chasing every for my entire 20s. There were always milestones, between getting into grad school, passing my quals, lab meetings, presenting at conferences, thesis committee meetings, and finally my thesis defense. These are huge motivating factors. 

** My company
Toward the end of graduate school, I started freelancing. Given the way capitalism is set up, I fell right into the cycle of having goals and milestones at every step. How did all of this feel like?

Going from freelancer to running a company? Just a lot more work and bureaucracy now. Making my first $100k in a year? Relief that I'm no longer living on the paycheck, but now some bigger financial goal crowding in. At every step, I'm just the smallest poorest member of the next group.

All of this is literally the opposite of Eastern religious practices. I fall into the trap of wanting the next thing and being unsatisfied with what I have. And lo and behold, this creates suffering. But if I stop wanting stuff and I become fine with what I have, my competition will flatten me.

It is through this competition that I get better. I have to innovate. I have to learn the latest tools. I have to improve my marketing and sales. I have to understand how many and value works. I have to have a good rational mental model of how my company interacts with the market. Any errors in any of these things decreases profit at best, and bankrupts me at worst. 

** The cure for cancer
What about the bigger issues, like purpose in life? As a kid, I thought that I would one day cure cancer, as I've lost a few family members to the disease starting early in my life. I wouldn't wish the pain my family went through on anyone, but on the other hand, it was as if God handed me my purpose in life on a silver platter. 

I learned down the line that cancer is very complicated, and maybe if I'm lucky I could contribute a little bit to some sort of treatment of some sort of cancer somewhere. Then of course I learned down the line that there are all kinds of other existential problems our society is facing that could bring an end to cancer patients and non-cancer patients alike.

I'm still driven by curing cancer, but I also know that if this was my only goal and I was emotionally dependent on this outcome, then I would be disappointed at the end of my life. On the other hand, having this huge goal of curing cancer early in life, even if it was unrealistic, was a huge motivator for the sacrifice involved in becoming a scientist. It was curing cancer that I had in mind during the late nights in high school and college, or the weekends I was studying when I could have been socializing or relaxing. 

* Not driven by purpose

Let's look critically at areas in my life that do not involve chasing huge goals and following a bigger purpose. On one hand, perhaps because there were no large goals associated with each of these activities, I am not as good as I could be in each of these activities. On the other hand, because these activities are not dependent on a big purpose and goals, and this might contribute to the joy I derive from them, and the observation that I still have passion for each of these pursuits. 

** Music

I played the bass from the age of 12 onwards, and I play jazz piano now. Music has been a big part of my life. I was in various concert bands, jazz bands, rock bands, and jazz combos.

Now I've always had goals around getting better at my instrument, and learning various songs. But my practice was never driven by big recitals, concerts, becoming a famous rockstar, or any of that. I did have my public performances and all of that, but they were always secondary to the simple act of enjoying the playing of music.

One could perhaps make the argument that I could have become much better than I am now had I been pushed a bit harder, had I had stringent and much bigger goals, and what have you. But that opens up the can of worms that is "should've could've would've." The empirical observation I can make right now is that I am 36 and I still enjoy playing music. This is to be contrasted with all the people out there who became virtuoso pianists as children and then never touched a piano again because they were sick of their parents chaining them to the piano bench.

** Fitness

I started lifting weights around the time I was 13. At the time, it was mainly things like push-ups and using light weights to get used to the movements. The weights got heavier later.

I have been working out consistently since then. That is greater than two decades of consistent working out. I enjoy each workout and I don't feel right on the days where I don't work out.

In high school, I had things like pull-up contests that I would train for. But I was never on a powerlifting team (I was always too busy studying) or running marathons or any of that.

I do have sports and fitness goals that keep me oriented and keep me improving. But if all sports and fitness competitions mysteriously disappeared one day, I wouldn't lose the motivation to work out. Though I might be training for specific things here and there, I am not training for some external purpose. I train for its own sake. I like the way it feels after the workout (as it is often painful in the moment).

This is to be contrasted with programs like P90X or the Instanity Workout, where you go in as a beginner and do workouts that are on average more intense than what I do for the purpose of losing a large amount of weight in a short time. These workouts were popular for a while, but I don't yet know anyone who enjoyed these videos enough to continue doing the workouts for a decade. 

** Computer science

A lot of my day-to-day work involves coding. There is usually some sort of bigger objective that I'm going after. In going after that objective, I get myself into a [[./tao_of_problem_solving.html][flow state]] and everything seems to fall into place.

I have my goals, and I'm always deepening my craft, but I'm not doing it for the sake of making it to the top of Kaggle or to be etched in time as the top bioinformatician in the land. If that happens, then great. But at the end of the sake, I am doing it because I enjoy it.

In contrast to the other two activities, I have gotten quite skilled at computer science. This could be because computer science is very much a learn-by-doing activity. You solve problems and get immediate feedback: the code ran or it didn't. Your colleagues understand the code or they don't. You can learn and improve by tinkering. In my experince, music and fitness require supervision in order to improve. If you write your code wrong, it doesn't work. If you do a heavy deadlift wrong, your back doesn't work for the rest of your life. 

* Conclusion

Let's examine the costs and benefits of being purpose versus not purpose directed using the activities above.

**** Purpose-directed
Benefits:
- I was able to push harder than I otherwise would.
- It feels nice in the moment to be chasing a big puspose.
- There is a societal narrative (especially in Christianity) around finding your purpose.

Costs:
- There were many let-downs along the way.
- When the goal goes away, the motivation goes away.
- I get in the trap of needing to chase something all the time.
- The focus is on the outcome, which is something you can't control. 

**** Not purpose-directed
Benefits:
- Long game is easier: each of the aforementioned activities have been maintained consistently for upwards of decades.
- The focus is on the moment, which is something that is within your control. 
- Each of these activities are associated with the highly satisfying flow state.

Costs:
- I am good at each of these activities, but could perhaps be better.
- I'm not always oriented and focused, which may make it harder to improve.
- I may not be pushing as hard as I could be. 

**** Synthesis

I wrote this article with the original intent of arguing that we should move more toward doing activities for their own sake. What I conclude now is that this is that case for me right now with my activities at this phase in my life. For everyone else, it will depend on the person, the activity, the situation, and many other things.

This is a continuous dialectic, not an argument for either side. The point is both sides need to be kept in mind at all times.

Perhaps one way to have your cake and eat it too is to have goals that you're chasing, but to be emotionally indiferent to the outcome. If I want to cure cancer, then I can lay out the daily habits necessary to move me in that direction, modify them in accordance to feedback, but then be emotionally indifferent to whether or not anything I do makes any contribution to cancer research whatsoever.  




