#+Title: Flowing your way into good health
#+Author: Tyler Burns
#+Date: May 21, 2023 - May 21, 2023

[[./index.html][Home]]

I.

Starting in my teens, I have placed a huge weight on maintaining good health. My current day-to-day life revolves around this. As I progress into middle age, maintaining good health is becoming increasingly important, as there are fewer things I can get away with these days (eg. eating dessert). My friends in my age group as also pursuing healthier lifestyles, which I think is a great thing. I am often asked for advice, and I can talk about my journey over the last few decades, since my first workout in February of 1999.

What I've realized is that everyone has a different starting point and different motivating factors. Everyone has a different day-to-day life, and a different set of stressors they have to deal with. Some people can motivate themselves to go running. Others do better when they're running in a group, or have some other social form of accountability. Some people don't like weight lifting, but love tennis. Everyone is different. And everyone changes.

If you want to read about how to get into shape and how to achieve some fitness related goal, there is plenty of material online about this. It's well beyond the scope of this post. Here, I would like to provide a /yang/ to the /yin/ that is goal-oriented behavior. I'm doing this because I don't think there is enough health and fitness related intrinsic motivation. Getting your dopamine from the process rather than the outcome.

Rather than turning this into an exhaustive literature review on all things that are related to process-directed motivation, I am going to simply write about my perspective. It is rooted in, and perhaps a synthesis of, Alfred Whitehead's process philosophy, Taoism, and to an extent, James Clear's Atomic Habits.

II.

From listening to marathon and ultramarathon runners, one of the pieces of advice they give in terms of running one of these things is to sign up for the race. Then your brain does an "oh shit" and you snap into the mode of doing everything you can such that you'll show up to the race and run it. However, there is a big failure mode here: [[https://www.trailrunnermag.com/training/trail-tips-training/understanding-the-post-race-blues/][post-race depression]]. You're building up to the race, and then it happens. And now what? Do you sign up for another race?

The problems I have with this way of doing things is that your motivation becomes dependent on you signing up for the next thing. At the time of writing [2023-09-03 Sun], I have not run a full marathon, let alone an ultramarathon. But recently I ran a half marathon (plus a mile), by myself, in the forest, for funsies. I didn't tell anyone I was going to do it. I didn't sign up for a race. I just did it. Perhaps I'll add a mile to my long run next week.

How did this come about? My usual long run is 5 miles. But one day a few months ago I decided to go to 7 miles. Why not? And then I decided to go to 9 miles. Why not? And so on. At some point, I saw the half marathon as a milestone (literally) and I decided, relatively post-hoc, to make that a "goal" even though I was flowing toward it and would hit it whether or not it was a goal. Then I looked up the best practices in terms of training schedules, etc.

I can proudly report that I don't have any sort of post race depression. This wasn't hanging over me for so many months, motivating me to get up in the morning. None of that. I enjoy running. So I just ran a bit longer every time. I bought some better running shoes and did the necessary stretches and pre-hab. And that was it.

As a result, running 16 miles one or two weeks from now, and then 18 miles after that is not out of the question. Because I simply don't care. I don't have my eyes on any prize. If I hit 26.2 miles at some point, great. I already have some momentum, so I'll flow in that direction and see how far I get.

III.

Notice my wording. Flowing in a direction. This is how a lot of my life feels like. This is how a lot of my motivation is. I work from home. I am self-employed. Thus, my work is based entirely on my internal cycles and that's it. When I feel the impulse to work, which comes over me like a wave, I ride it until its compltion, which is usually somewhere between 1.5 hours and 4 hours (the latter being the limit of what Cal Newport calls [[https://www.amazon.com/Deep-Work-Focused-Success-Distracted/dp/1455586692][deep work]]).

I have written about the [[./tao_of_problem_solving.html][flow state]] before in the context of solving coding-related problems. In the aforementioned article, I talked about Taoism and an ideal of a lifelong flow state. One that extends beyond simply solving problems in my domain. I have been thinking critically about this, as tools like ChatGPT take a lot of the flow state out of my work. Furthermore, a lot of my work now is advising, rather than coding. This was something I was resisting for a long time, and I realize now that what I was resisting was having the flow state wrestled away from me. But as this article suggests, I have been a bit more in tune with myself and have found the concept of flow domainating quite a bit more of my life than just coding, suggesting that perhaps I'm onto something here.

To understand flow, you can look into the [[https://en.wikipedia.org/wiki/Flow_(psychology)][psychology of it]]. In short: you do something that is challenging to the point where its just beyond your skill set to do the thing. That puts you in a so-called flow state.[[./finite_infinite_life_games.html][ Video games]] do a good job at this, with the mechanics of either having progressively harder levels and finite lives, or extremely hard levels and infinite lives.

However, if you look at Taoism, which cognitive scientist [[https://www.youtube.com/watch?v=droqRDXbpGc][John Vervaeke]] calls the religion of the flow state, you can see that there is more to it than just some challenge-versus-skill-set thing. We get in flow states all the time when we're in conversations with friends. This is when the time flies by. When you're having fun. Is that a perfectly placed challenge that matches your skill set? Not really.

Or what about the creative instinct. Music producer legend [[https://www.youtube.com/watch?v=ycOBZZeVeAc][Rick Rubin]], who I would argue is a modern day Taoist, talks about this a lot. The idea that sometimes you just have the impulse to write something, [[./just_paint.html][paint]] something, to create something, and if you don't act on it, the impulse goes away. What is that? For me, it's a wave that comes over me, as I've said before. You either ride the wave, or it passes you buy.

A lot of this stuff is non-verbal. In other words, it's things you can't put into words. As I type this, the irony is not lost on me. But in the last few years, I've been doubling down on the stuff of thought that doesn't involve words. Or even pictures for that matter. The feelings, vibes, symbols, metaphor, and stuff of that nature that's simply hard to describe.

To understand this, let's look at the Tao Te Ching, one of Taoism's fundamental books. We'll go through it slowly. I'm using the translation from [[https://taoism.net/tao-te-ching-online-translation/][here]], but note that there are many.

/The Tao that can be spoken is not the eternal Tao/\\
/The name that can be named is not the eternal name/\\

The thing I'm trying to get at, as it applies to motivation for health and fitness, cannot be gotten at directly. No goal setting, weight watching, measuring, flexing in the mirror, or anything else will directly cover it. These things will cover parts of it, but there is a much bigger thing that goes right back into the idea of getting dopamine from the process of doing the workouts, and not the goal you set or the race you run. From a scientific standpoint, this is the admission of ignorance. The admission that whatever it is, it's [[./its_more_complicated_than_that.html][more complicated than that]]. There's more to it than that.

/The nameless is the origin of Heaven and Earth/\\
/The named is the mother of myriad things/\\

And to try to name what this thing is, is futile. To double down on the nameless, the things that cannot be placed into words, is what's going to help you understand your motivations, and therefore learn how to flow into things rather than run toward a goal.

/Thus, constantly without desire, one observes its essence/\\
/Constantly with desire, one observes its manifestations/\\

And now we're going against so much of what is said in the current meme-plex. Go on LinkedIn, and you'll hear people talking about how you have to want it, and have your eyes on the prize or whatever. But Taoism and Buddhism both talk about ridding yourself of desire. What happens when that happens? I would argue you're buffering yourself against all of the instances of "post-goal depression" that you'd otherwise get from having some goal you're chasing.

/These two emerge together but differ in name/\\
/The unity is said to be the mystery/\\
/Mystery of mysteries, the door to all wonders/\\

And here we get introduced to the idea of yin and yang. The idea that things have their opposites, and there is unity in having them both. I'm not arguing that the flow state is something we should all just switch to and never set a goal again. But I am arguing that we should pay attention to this a bit more. In making a dialectic (unity) with the usual goal-directed behavior that we're more familar with, we will be able to have a motivation that is deeply rooted in the wisdom of knowing who we are and where we are going.

IV.

Now let's go a bit deeper into the /myriad things/ that the Tao Te Ching was talking about above. Remember, we're moving away from things and more in the direction of that which cannot be put into words. There is something here that is very relevant to health and fitness. Starting with Chatpter 2 of the Tao Te Ching:

/When the world knows beauty as beauty, ugliness arises/\\
/When it knows good as good, evil arises/\\

This is profound. The internet beauty standard, which is pretty much impossible at this point (without AI filters or whatever), makes us all feel ugly. Ageing will make us even uglier if we're clinging onto beauty as opposed to growing into a sage. As philosopher Daniel Schmachtenberger [[https://www.youtube.com/watch?v=-McfN9r8DzI][likes to say]], if the world is going crazy, and you're going crazy relative to the world, then are you really going crazy? So if you feel ugly in the face of a culture that's gone off the rails with an increasingly impossible beauty standard, are you the problem or is society that problem? In other words, if you feel ugly, it's not your fault.

/Thus being and non-being produce each other/\\
/Difficult and easy bring about each other/\\
/Long and short reveal each other/\\
/High and low support each other/\\
/Music and voice harmonize each other/\\
/Front and back follow each other/\\

This is yin and yang at its best. Don't worry about contradiction. Embrace it. If this article inspires you to pay more attention to your internal flow, you can do this alongside goal-directed behavior (including signing up for the marathon). It's fine. The flow and the goal will support each other. The purpose of this article is to point you to the flow, as it's harder to talk about than the goal.

/Therefore the sages:/\\
/Manage the work of detached actions/\\
/Conduct the teaching of no words/\\
/They work with myriad things but do not control/\\
/They create but do not possess/\\
/They act but do not presume/\\

This is common writing in the Tao Te Ching. Therefore the sage does X by doing not X. Don't let that previous sentence diminish the writing. Each of these sentences, which seem to be contradictions, point to higher truths. You have to read it very slowly. Keep it in the back of your mind. Go out into the world and do stuff. Come back days or years later and read it again.

I see things like this in my life all the time. I worked on my running stride and I took off a solid minute per mile off my pace, by simply being more efficient. I /increased/ my performance by /decreasing/ my effort. This is very common in sports, when the advice is to "loosen up."

And importantly:

/They succeed but do not dwell on success/\\
/It is because they do not dwell on success/\\
/That it never goes away/\\

This part is the essence of what I'm trying to convey here. Can one set a goal and not dwell on it. This is similar to James Clear's Atomic Habits. You use a goal to point you in the right direction. But then you forget about the goal and just focus on the habits that will get you to the goal. But the reason I'm spending so much time going through the Tao Te Ching in this article is because I think the concept of flow is more profound than just setting habits and following them. Yes, you have to have discipline, and yes, there will be days where you don't want to do the thing and you have to push through, but I would argue that you can find your flow on those days too.

V.

I wanted to talk briefly about trainers and mentors. Once you've developed intrinsic motivation and you don't have to be chasing the next goal anymore to achieve success, how do you pass this knowledge on. Obviously, this is difficult to put into words. But there is one passage from the Tao Te Ching, chatper 17, that does it very well.

Because this article is about health and fitness (though its grown into a bit more than that), I'll talk about my experience as a trainer. My best client is still physically active and very healthy. I spoke to her once about ten years after I had trained her. The advice I had given her at the end is to simply live a physically active lifestyle. Find things you enjoy that are also healthy and do those things. Not everyone is going to enjoy running or lifting weights as much as me. There are people in my life who enjoy ballet 1000% more than I do. So they do ballet, and I don't.

The key is to get them to a point where they feel like they're doing it themselves. Then you can slowly step away and they will continue the good habits on their own. Note that this is against near-term financial incentives of re-signing. But I was doing training as a side job at the time, so I could operate however I wanted. Ok, let's see what the Tao Te Ching says that is relatable to this:

/The highest rulers, people do not know they have them/\\
/The next level, people love them and praise them/\\
/The next level, people fear them/\\
/The next level, people despise them/\\

We've all had the micromanager breathing down our necks. It's not fun at all. My PhD thesis advisor was a mentor by osmosis. He wasn't around very much because he was a hot shot, who always had to be at a place giving a talk and that kind of thing (/people do not know they have them/). As one of the physician scientists in the lab put it: "because he's out there doing the things he's doing, I have the funding and resources to do what I'm doing."

When he was around, he taught me all kinds of things about how to drive innovation in the sciences, oftentimes indirectly. He didn't have a 5-point plan for "how to think like me," but by talking with him and being around him enough, you could start to develop a "what would Garry Nolan do" mental model that still guides me today.

/If the rulers' trust is insufficient/\\
/Have no trust in them/\\
/Proceeding calmly, valuing their words/\\
/Task accomplished, matter settled/\\
/The people all say, "We did it naturally"/\\

That last part is what I'm trying to get at here. "We did it naturally" can symbolize intrinsic motivation leading to achievement, and the intrinsic motivation was given by the trainer, or teacher, or mentor. As in my example with my thesis advisor, it's hard to put into words what he did and how he did it, but he was able to mentor without being a direct mentor in the classical sense. I feel like I did it naturally, but Garry was there instilling the right thought patterns and habits the whole time.

As I like to think it was with my aforementioned client. I hope that may way of doing things got to her by some sort of osmosis. I did a lot of talking, but I also walked the walk. She'd see me there working out before or after our sessions, writing into a similar fitness notebook that I had made for her.

Can you make your students not need you anymore, to the point where perhaps they feel like they're doing it themselves even though you're helping in indirect ways that they'll only notice later?

IV.

So we've covered a bit of ground. This article first started out talking about fitness. Then it turned into a discussion of motivation itself. Which moves us into the flow state and Taoism, the religion of the flow state.

The concept of flow makes up a big part of my life. It's much bigger than Atomic Habits, Deep Work, or any of the other business or self improvement books that point in this direction. This is because a lot of this cannot be put into words, try as I might. This being said, there are a couple of key concepts I wanted to recap here.

The first is understanding your natural cycles. How do you do this? By not being employed. Or by working from home. Or by going on a very long vacation or sabbatical. For me, learning my natural cycles came from being self employed and working from home. I'm still waiting on the day that I can go on a really long vacation, despite living in Europe, the continent of very long vacations. From the natural cycles come the times and situations in which your motivation to do a thing (it depends on the thing) will wax and wane. You'll know when to work and when to rest, without forcing things so much.

The second is paying attention not to the goal, but what direction you're naturally going. Are there any goals that are downstream that you could run into with a few tweaks? For me, it was that half marathon. At the gym, there are various things I work toward all the time. At work, sometimes a business contact becomes a client naturally because it's simply the right time. Yes, there is a Tao of sales (which I'm qualified to speak of because I've survived as a one-person business for five years), but that's for a different time. Again, if you do it like this, then you won't need to have your eyes on the prize in order to succeed.

The third is embracing contradiction. Should I focus on the goals? Should I forget the goals and do this flow thing talked about here? You have to do both. What does that mean? There's going to be a bunch of subtle connections between the polar opposites that lead to a higher, richer truth. In Taoism, this is yin and yang. In western philosophy, this is the Hegelian dialectic. In other words, this idea has shown up independently in more than one place.

All things being said, I hope this article gives you a new perspective around how to approach health and fitness, and other things that require motivation in general. It has worked for me since I started lifting weights in 1999. I have been working out consistently since then. Importantly, this article is not something I reasoned my way to, leading me to change my behavior in this direction or any of that. Rather, it's me trying to take something that's been in my head for decades and getting it onto paper, because I don't see this perspective on the internet yet and I think it should be there.
