#+Title: The pursuit of health
#+Author: Tyler Burns
#+Date: May 21, 2023 - May 21, 2023

Starting in my teens, I have placed a huge weight on maintaining good health. My current day-to-day life revolves around this. As I progress into middle age, maintaining good health is becoming increasingly important, as there are fewer things I can get away with these days (eg. eating dessert). My friends in my age group as also pursuing healthier lifestyles, which I think is a great thing. I am often asked for advice, and I can talk about my journey over the last few decades, since my first workout in February of 1999.

What I've realized is that everyone has a different starting point and different motivating factors. Everyone has a different day-to-day life, and a different set of stressors they have to deal with. Some people can motivate themselves to go running. Others do better when they're running in a group, or have some other social form of accountability. Some people don't like weight lifting, but love tennis. Everyone is differnt. And everyone changes.

To all of these points, I think I can speak to more people if I speak in aphorism rather than your standard eight bullet point comprehensive fitness plan or whatever. There are universal truths that underlie everyone's unique journey to good health, and I'd rather try to get at those than to create some sort of cookie cutter approach to good health.

So here you go. I am trying to pack as much wisdom per word as I possibly can. One of the key concepts to understand as you read these: as much as we like to put things into words, there are simply things that are hard to put into words. There are plenty of health and fitness books out there that help us put stuff into words. But a lot of "wisdom" exists as things that we cannot quite verbalize. But we know it when we see it.

-----

The dawn breaks, and the world awakens. Some go running now. Some go running later. What matters is that you run.

The purpose that can be named is not the eternal purpose. The goals that can be defined are not the ultimate goals. Write down your values. Set your goals. But know that they will be incomplete.

Health is the silent dialogue between you and your body. To pursue health is to pursue knowing yourself.

Bench press, a phrase laden with meaning. Yet its echoes resonate differently in each person. To some, good feelings, and to some, bad. Same for swimming. Same for ballet.

Seek not to exhaust yourself in your exertions, but to ignite a flame that burns steadily, eager for tomorrow's kindling.

Health, an unchanging truth amid life's transient tides. Through every crest and trough of our journey, the pursuit of health remains. Through good health and bad, you can still pursue it just the same.

In motivation and drive, we find the seeds of progress. Cultivate them with the gentle patience of the gardener. Through this remember, motivation and drive themselves are seeds of progress.

Document your journey, both in numbers and in sentiments. Every whisper of progress, every sigh of struggle, every pump in the biceps, lends color to your canvas. Your future self will be rewarded with good health, and the corpus that is your journey.

Momentum, the unseen wind at your back. Each step you take fans this breeze into a gust. The 1002nd workout will be easier to start than the 2nd.

To know yourself is to embrace the river of change that flows through you. Test its currents, chart its course, and expect its meanderings.

As the sands of time slip through our fingers, the pursuit of health continues as a drum beat, a rhythm as vital at the dawn of life as at its twilight.

Nurture your being as you would a cherished companion. A romantic partner or a grandparent. Stretch, eat, explore with the tenderness you'd bestow upon them. In each step, set down the imprint of your best self.

Results are whispers on the wind, not just the echoes of numbers. They are the silent symphony of feelings that unfurl within you. Record these just as you would record the numbers.

There is no master key to unlock all doors of sport. Instead, find the melody that stirs your soul, be it in the dance of the ballet or the rhythm of judo.

In consistency, not intensity, we find the path to a healthy and active tomorrow. Each day's effort is but a stepping stone on this path.

Seek the wisdom of others, for hidden truths may lie beyond your horizon. A fresh pair of eyes may uncover unseen vistas. Be independent, but do not go it alone.

If today the mountain seems too steep, focus on the stone beneath your foot. Place one foot in front of the other, forget about the mountain, and let the journey unfold.

Motivation ebbs and flows, for the beginner and the fitness sage alike. For life is a tempest, and to hit the snooze button is but human.

Diets and workout plans, like fashion, come and go. Don't chase the trends. Find your style.

Health is a process, not an end state. To pursue health it to pursue a continuous state of pursuit. The way is the way.
