#+Title: The pursuit of health
#+Author: Tyler Burns
#+Date: May 21, 2023 - May 21, 2023

[[./index.html][Home]]

Starting in my teens, I have placed a huge weight on maintaining good health. My current day-to-day life revolves around this. As I progress into middle age, maintaining good health is becoming increasingly important, as there are fewer things I can get away with these days (eg. eating dessert). My friends in my age group as also pursuing healthier lifestyles, which I think is a great thing. I am often asked for advice, and I can talk about my journey over the last few decades, since my first workout in February of 1999.

What I've realized is that everyone has a different starting point and different motivating factors. Everyone has a different day-to-day life, and a different set of stressors they have to deal with. Some people can motivate themselves to go running. Others do better when they're running in a group, or have some other social form of accountability. Some people don't like weight lifting, but love tennis. Everyone is differnt. And everyone changes.

To all of these points, I think I can speak to more people if I speak in aphorism rather than your standard eight bullet point comprehensive fitness plan or whatever. There are universal truths that underlie everyone's unique journey to good health, and I'd rather try to get at those than to create some sort of cookie cutter approach to good health.

I am trying to pack as much wisdom per word in here as I possibly can. One of the key concepts to understand as you read these: as much as we like to put things into words, there are simply things that are hard to put into words. There are plenty of health and fitness books out there that help us put stuff into words. Great. Read those. But a lot of health "wisdom" exists as things that we cannot quite verbalize. I hope to get at some of that here.

Some of you will see that this looks very similar to the /Tao Te Ching/ if Lao Tzu worked out. That is because that book resonates very much with the way I've done things over past decades. Perhaps health and wellness are ripe for a Taoist reformation.

-----

The purpose that can be named is not the eternal purpose. The goals that can be defined are not the ultimate goals.

Write down your values. Set your goals. But know that they will be incomplete.

Some goals cannot be set. To grasp for them, they recede. But in the mind, when quiet long enough, their call can be felt. Honor the presence of these goals, just as you honor the goals that are written down.

-----

The dawn breaks, and the world awakens. Some go running now. Some go running later. What matters is that you run.

Bench press, a phrase laden with meaning. Yet its echoes resonate differently in each person. To some, good feelings, and to some, bad. Same for swimming. Same for ballet.

Health is the silent dialogue between you and your body. To pursue health is to pursue knowing yourself.

To know yourself is to embrace the river of change that flows through you. Test its currents, chart its course, and expect its meanderings.

Motivation ebbs and flows, for the beginner and the fitness sage alike. For life is a tempest, and to hit the snooze button is but human.

Diets and workout plans, like fashion, come and go. Don't chase the trends. Find your style.

There is no master key to unlock all doors of sport. Instead, find the melody that stirs your soul, be it in the dance of ballet or the rhythm of judo.

Health is about the body, but also the [[./psychotherapy_and_fitness.html][mind and spirit]]. If you overvalue the body and neglect everything else, you will have a six pack and be miserable.

Some things will naturally "glimmer" to you more than others. In some phases of life, the bench press will glimmer. In others, the yoga mat. In others still, the hiking trail. Notice what glimmers. Let that guide you.

-----

Seek not to exhaust yourself in your exertions, but to ignite a flame that burns steadily, [[./how_to_get_fit_long_term.html][eager for tomorrow's kindling]].

Health, an unchanging truth amid life's transient tides. Through every crest and trough of our journey, the pursuit of health remains. Through good health and bad, you can still pursue it just the same.

In motivation and drive, we find the seeds of progress. Cultivate them with the gentle patience of the gardener. Through this remember, motivation and drive themselves are seeds of progress.

Momentum, the unseen wind at your back. Each step you take fans this breeze into a gust. The 1002nd workout will be easier to start than the 2nd.

If today the mountain seems too steep, [[./tao_of_problem_solving.html][focus on the stone beneath your foot]]. Place one foot in front of the other, forget about the mountain, and let the journey unfold.

To stray from a comfortable path, simply place one foot on untrodden soil. And then another.

Health is a process, not an end state. To pursue health it to pursue a continuous state of pursuit. [[./purpose_driven_vs_purposeless.html][The way is the way]].

-----

In motivation and drive, we find the seeds of progress. Cultivate them with the gentle patience of the gardener. Through this remember, motivation and drive themselves are seeds of progress.

Results are whispers on the wind, not just the echoes of numbers. They are the silent symphony of feelings that unfurl within you. Record these just as you would record the numbers.

Document your journey, both in numbers and in sentiments. Every whisper of progress, every sigh of struggle, every pump in the biceps, lends color to your canvas. Your future self will be rewarded with good health, and the corpus that is your journey.

Memory is elusive. The you of today is not the you of yesterday. Respect your memories, but honor the inked testament of your journey.

-----

Beauty filters will make you feel ugly. Even if you are beautiful.

Beauty magazines will make you feel ugly. Even if you are beautiful.

Beauty standards will make you feel ugly. Even if you are beautiful.

Beauty filters, beauty magazines, and beauty standards are not beauty. They are illusions. They are ephemeral. Remember this.
