#+Title: The pursuit of health
#+Author: Tyler Burns
#+Date: May 21, 2023 - May 21, 2023

[[./index.html][Home]]

Starting in my teens, I have placed a huge weight on maintaining good health. My current day-to-day life revolves around this. As I progress into middle age, maintaining good health is becoming increasingly important, as there are fewer things I can get away with these days (eg. eating dessert). My friends in my age group as also pursuing healthier lifestyles, which I think is a great thing. I am often asked for advice, and I can talk about my journey over the last few decades, since my first workout in February of 1999.

What I've realized is that everyone has a different starting point and different motivating factors. Everyone has a different day-to-day life, and a different set of stressors they have to deal with. Some people can motivate themselves to go running. Others do better when they're running in a group, or have some other social form of accountability. Some people don't like weight lifting, but love tennis. Everyone is differnt. And everyone changes.

To all of these points, I think I can speak to more people if I speak in aphorism rather than your standard eight bullet point comprehensive fitness plan or whatever. There are universal truths that underlie everyone's unique journey to good health, and I'd rather try to get at those than to create some sort of cookie cutter approach to good health.

I am trying to pack as much wisdom per word in here as I possibly can. One of the key concepts to understand as you read these: as much as we like to put things into words, there are simply things that are hard to put into words. There are plenty of health and fitness books out there that help us put stuff into words. Great. Read those. But a lot of health "wisdom" exists as things that we cannot quite verbalize. I hope to get at some of that here.

Some of you will see that this looks very similar to the /Tao Te Ching/ if Lao Tzu worked out. That is because that book resonates very much with the way I've done things over past decades. Perhaps health and wellness are ripe for a Taoist reformation.

-----

(1)

The path of health that can be named is not the eternal path. The goals that can be defined are not the ultimate goals.

Write down your values. Set your goals. But know that they will be incomplete.

The undefinable goals are the essence of good health. Defining is the origin of the ten thousand exercises.

Some goals cannot be set. To grasp for them, they recede. But in the mind, when quiet long enough, their call can be felt. Honor the presence of these goals, just as you honor the goals that are written down.

Free from desire of these goals, the mysteries of good health reveal themselves. Full of desire, all you see is gains.

Yet the mysteries and the gains spring from the same source. That source is strength. The gateway to understanding.

Activity and rest create each other. Physical strength and flexibility support each other. Sprinting and Zone 2 cardio depend on each other. Warm-up and cool-down follow each other.

Therefore the healthy person trains hard without straining. And teaches without preaching. Workouts arise and she lets them come. Trends and fad diets appear and she lets them go. She has health but does not attach to it. When her workout is done, she lets it go. That is why her good health lasts forever.

-----

(1) Interlude

We have these ideas in our head as to what good health is, and how to get there. Yet, these are all incomplete. If I really think about what good health is for me, I can break it down in to things like physical, mental, social, spiritual, and so on. I can list goals that correspond to each bucket. I've done this. What happens is I have this list of 100 or more goals, and I feel both overwhelmed at its size and unsatisfied at its incompleteness. In reading the Tao Te Ching, I realize that things like the ultimate health goal state is really hard to put into words. But I can feel it, and I can feel when I'm on or off path. So I'm focusing on that now.

-----

(2)

The dawn breaks, and the world awakens. Some go running now. Some go running later. What matters is that you run.

Bench press, a phrase laden with meaning. Yet its echoes resonate differently in each person. To some, good feelings, and to some, bad. Same for swimming. Same for ballet.

Health is the silent dialogue between you and your body. To pursue health is to pursue knowing yourself.

To know yourself is to embrace the river of change that flows through you. Test its currents, chart its course, and expect its meanderings.

Motivation ebbs and flows, for the beginner and the fitness sage alike. For life is a tempest, and to hit the snooze button is but human.

Diets and workout plans, like fashion, come and go. Don't chase the trends. Find your style.

There is no master key to unlock all doors of sport. Instead, find the melody that stirs your soul, be it in the dance of ballet or the rhythm of judo.

Health is about the body, but also the [[./psychotherapy_and_fitness.html][mind and spirit]]. If you overvalue the body and neglect everything else, you will have a six pack and be miserable.

Some things will naturally "glimmer" to you more than others. In some phases of life, the bench press will glimmer. In others, the yoga mat. In others still, the hiking trail. Notice what glimmers. Let that guide you.

-----

(2) Interlude.

My path is different than your path. My path ten years ago is different than my path now, and it will likely be different than my path ten years from now. I used to be an evening person. Now I'm a morning person. I used to be motivated by looking good, now I'm motivated by feeling good. Altogether, I've stopped trying to find an absolute protocol for perfect health that will work for me and everyone else forever, and I've just started focusing on the process.

Everyone will have a different process that works for them. You often see analogies to a river in Eastern philosophy. That's what health is. You're not going down the river with some destination downstream. You are the river.

-----

(3)

The path to good health is infinite and eternal. Why is it eternal? It is never born, thus it can never die. Why is it infinite? It is present in all beings. Thus the path to good health it not to be desired. You are simply meant to be on that path.

Seek not to exhaust yourself in your exertions, but to ignite a flame that burns steadily, [[./how_to_get_fit_long_term.html][eager for tomorrow's kindling]].

Health, an unchanging truth amid life's transient tides. Through every crest and trough of our journey, the pursuit of health remains. Through good health and bad, you can still pursue it just the same.

In motivation and drive, we find the seeds of progress. Cultivate them with the gentle patience of the gardener. Through this remember, motivation and drive themselves are seeds of progress.

Momentum, the unseen wind at your back. Each step you take fans this breeze into a gust. The 1002nd workout will be easier to start than the 2nd.

If today the mountain seems too steep, [[./tao_of_problem_solving.html][focus on the stone beneath your foot]]. Place one foot in front of the other, forget about the mountain, and let the journey unfold.

To stray from a comfortable path, simply place one foot on untrodden soil. And then another. The path to health may take you away from comfort form time to time.

Health is a process, not an end state. To pursue health it to pursue a continuous state of pursuit. [[./purpose_driven_vs_purposeless.html][The way is the way]].

-----

(3) Interlude

Like anyone, I face resistence when I need to do a hard thing. Or a new thing. A lot of this has been addressed by simply moving in the direction of what I need to do, one step at a time. There's a saying in Taoism that I heard from Alan Watts that, when translated to Western terms, goes: "you should never let the Devil know what you're up to." That's what this is. If I need to go to the gym, I walk over to the shoe rack. I put one she on. Then the next. Then I grab the keys. In no way am I thinking about the gym. I'm just doing the next thing. And then I'm at the gym, wondering how I got here. Do this enough, and you'll get some mometum. It will get easier.

-----

(4)

Look back, and your past workouts can't be seen. Listen, and your past efforts can't be heard.
Reach, and the sweat from yesterday can't be grasped. But written down, you can go back.

Every workout becomes a form, an image without an image, subtle, beyond all conception. The journal entries etch its shape.

Express yourself completely every exercise. But then keep quiet and express yourself completely on paper. If you want to stay on the path of health, do your workout, record it, and let go.

Results are whispers on the wind, not just the echoes of numbers. They are the silent symphony of feelings that unfurl within you. Record these just as you would record the numbers.

Document your journey, both in numbers and in sentiments. Every whisper of progress, every sigh of struggle, every pump in the biceps, lends color to your canvas. Your future self will be rewarded with good health, and the corpus that is your journey.

Memory is elusive. The you of today is not the you of yesterday. Respect your memories, but honor the inked testament of your journey.

-----

(4) Interlude

One of the behavioral loops that keeps me going in my health journey is that I do a hard thing, like a weight training session or a distance run. Then I record it. Both the numbers and how it felt. For whatever reason, this act motivates me to do the next thing. I've recorded every workout for over two decades now. It's a pleasure to be able to go back and see what I was up to in the second week of April, 2005.

-----

(5)

If you overesteem beauty magazines, beauty filters, and beauty standards, even the most beautiful people feel ugly.

Beauty filters, beauty magazines, and beauty standards are not beauty. They are illusions. They are ephemeral.

The healthy person leads, by emptying people's minds of misconceptions, by giving people vitality by weaking their attachment to these standards, and toughening their resolve.

She helps people lose everything they think they know about health, the misleading standards they desire, the fad diets they follow, in those who think they know.

For a lot of the modern media pretends to be the path to health. But it is far from it. Understand modern media, and you will understand what not to do.

-----

(5) Interlude

In college and grad school, I was always one of the fittest people in my college gym. This gave me a little chip on my shoulder. Then one day, I went to a small boutique gym for bodybuilders and figure/fitness competitors, with a friend of mine who was competing. There were guys there who had biceps bigger than my thighs. If not my face.

The internet is full of people like this, better than me in every way that I want to be good, but now there are social media filters that make you prettier than you were. It's a really nice way to know what parts of your face or wherever else are not in conformation with the internet beauty standard. I think if social media was in its current state when I was 18, it would sink me. None of this is health. It pretends to be health, but it is merely a generator function for body dysmorphia.
