#+Title: Question bank
#+Author: Tyler Burns
#+Date: May 25, 2024 - May 31, 2024

[[./index.html][Home]]

-----
/You're only as good as your last question./

My uncle Nigel, professor at the University of Michigan Ross School of Business. Said to me once in conversation years ago when I was neck deep in my graduate training.
-----

#+TOC: headlines 2

The following are questions, or groups of questions, that I have found helpful over the years. Especially for the questions related to personal agency, meaning, and motivation, you often have to let them simmer for a few days...or decades. I still revisit a lot of these questions. They speak differently in different contexts. Another way to word this: a lot of these are questions you "sit with" for a long time rather than answer as if they were essay questions for a college application. Sometimes, the answers materialize as words. Sometimes, they are feelings. Either way, take it all in.

I have organized the list below by specific people and specific questions associated with them. The questions that are between line separators are theirs. Questions that are mine are explicitly stated to be so. Commentary after the question is assumed to be my own unless otherwise stated.

* Pre-made collections of questions

** [[https://civilizationemerging.com/dharma-inquiry/][Daniel Schmachtenberger's Dharma Inquiry]]
#+HTML: <a href="#top">Back to top</a>
Absolutely brilliant set of questions around the concept of Dharma, which as Daniel defines it:

/Dharma, the way I hold it, roughly means: the path of right action; the path of greatest integrity; the path (of choices) that don’t create suffering and optimally helps heal it; the path that leads towards increasing wholeness, consciousness, health, and quality of life for all./

Here are the questions associated with this, quoted directly from the website linked above (none of these are mine). Super important is the repeating asking of "why."
-----
Capacities
- If my financial needs were already met for the rest of my life, what would I do?
- If I had the wealth of Bill Gates or Warren Buffet, what would I do with my life and resources?
- If I was going to go back to school, what would I study?
- If I could download skills matrix style, what would the top few most desired be?
- If I was a lot more confident/ less fearful, what would I do and how would I be differently?
- If I was meaningfully smarter than I currently am?
- If I had much better discipline?
- If I was better with people (more understanding, charismatic, empathetic, patient, etc.)?
- If I had better emotional regulation?
- If my main character deficits were resolved?
- If I had the right team and people supporting me?
- If my life started over with a clean slate (no previous commitments, baggage, etc.)?

Then ask “why” to your answers to each of these questions, until coming to something that feels fundamental.

Values
- Who are you most inspired by (that you personally know or figures from history)? What about them inspires you?
- Who do you respect the most? What about them?
- What virtues would you most want to increase in yourself? Why those ones?
- What types of behavior and people bother you the most?
- What issues in the world upset you the most?
- What do you see as most deeply wrong with or off in the world?
- What do you find the most beauty in? What are you most moved by?
- Who would you be the most proud to have been looking back at your life?
- What news stories about the world would you be most positively moved to see?
- What would you spend your time working on if you could succeed but no one would ever know that you did it?
- What few qualities would you most want to increase in everyone if you could?
- What would you sacrifice personal benefit for?
- What is more important to you than your own life?
- What is sacred to you? What does sacred mean?
- What are you devoted to? What does devotion mean?
- What is the basis of meaningfulness?
- What are you loyal to? What does loyalty mean? What would be an adequate reason to violate a loyalty?
- What do you feel shame or guilt about?
- If all your personal desires were already met, what would you then desire or care about?

Then ask “why” to your answers to each of these questions, until coming to something that feels fundamental.

Propensities
- What am I naturally good at? What seems to come easy to me? (Looking at strengths and aptitudes more than specific skills.)
- What types of activities do I feel replenished by?
- What am I willing to do even if it taxes me?
- What do I enjoy doing for its own sake, independent of producing results or getting acknowledgement?
- What is my attention repeatedly called to? What can I not not pay attention to?
- What am I intrinsically fascinated by? Passionate about?
- Where have I felt the most pride/satisfaction related to something I did?
- When have I felt most fully alive?
- What have been the greatest difficulties/pains in my life?
-----

And of course, we also have to include the questions that are associated with the antipode to Dharma, which are below:

-----
- Where am I being reactive rather than creative?
- Where are my goals the result of compensations to old wounds? (Proving that I’m enough, proving something to parents or a parental archetype projected on the world, seeking validation externally, proving we aren’t like our parents, etc.)
- Where am I still running the programs of my childhood (early models of success, of who I am, of what I’m capable of, of what’s meaningful…)
- What of the things I did last month will I remember and feel good about on my deathbed? Which will I wish I had done differently? How do I factor that into planning my next month?
- Where is fear influencing my choices?
- Where are there incongruences in my self, between my values and my actions…between some desires and other desires…between my habits and the expression of my highest vision…?
- Where is my sense of limited capacity constraining what I focus on?
- Where am I acting out of reaction, habit, or unconsciousness?
- Where do I feel trapped by past choices (loyalties, commitments, debts, investments, etc.)?
- Where are lack of self worth or self trust keeping me from showing up in greater service to what I care about?
- Where is credit seeking or image management influencing how I’m choosing?
- What do I do that I wouldn’t want to be fully honest about?
- What parts of my life would not engender the respect of those whom I respect the most?
- Where is my success occurring at the expense of others?
- Where does my life feel imbalanced?
- What do I do because I’m good at it but don’t really like it or care about it deeply?
-----

** [[https://tim.blog/wp-content/uploads/2020/01/17-Questions-That-Changed-My-Life.pdf][Tim Ferriss 4 hour workweek]]
#+HTML: <a href="#top">Back to top</a>
As Tim puts it here, it's about "testing the impossible." I remember the sheer optimism I felt after reading 4HWW for the first time. The world rapidly changing, but without all the existential dread that we have now. Anyway, the questions are still important. Perhaps even moreso to win in a society that is increasingly pessimistic.

- What if I did the opposite for 48 hours?
- What do I spend a silly amount of money on? How might I scratch my own itch? Tim's example is that he was spending money on supplements, and so he created a supplement company.
- What would I do/have/be if I had $10 million? What's my real target montly income?
- What are the worst things that could happen? Could I get back here?
- If I could only work 2 hours a week on the business, what would I do? This is a "80/20 principle" prompter
- What if I let them make decisions up to $100? $500? $1000?
- What is the least crowded channel?
- What if I couldn't pitch my product directly?
- What if I craeted my own real-world MBA?
- Do I need to make it back the way I lost it?
- What if I could only subtract to solve problems?
- What might I put in place to allow me to go off the grid for 4 to 8 weeks, with no phone or email?
- Am I hunting antelope or field mice? This is in terms of whether I'm going after something big or something trivially small?
- Could it be that everything is fine and complete as is? This question is relevant especially in a culture that hacks things like FOMO to get us to buy stuff we don't need with money we don't have.
- What would this look like if it were easy? I ask myself this a lot.
- How can I throw money at the problem? How can I "waste" money to improve the quality of my life?
- No hurry, no pause (more of a statement than a question but still included here). I can say that being independent (eg. not working for someone) puts me in this state more often than not. It's a marathon, not a sprint, as my uncle likes to say.

** [[https://www.curatedquestions.com/tim-ferriss-tribe-of-mentors][Tim Ferriss tribe of mentors]]
#+HTML: <a href="#top">Back to top</a>
These are more interview questions than self-questions. But you can see that they are also good questions to ask yourself.

- What is the book (or books) that you have given most as a gift, and why? Or what are one to three books that have greatly influenced your life?
- What purchase of $100 or less has most positively impacted your life in the last six months (or in recent memory)?
- How has failure, or apparent failures, set you up for later success? Do you have a "favorite failure" of yours?
- If you could have a gigantic bilboard anywhere with anything on it - metaphorically speaking, getting a message out to millions or billions - what would it say and why? It could be a few words or a paragraph.
- What is one of the best and most important investments you have ever made? Could be time, time, energy, etc.
- What is an unusual habit or absurd thing that you love?
- In the past five years, what new belief, behavior, or habit has most improved your life?
- What advice would you give to a smart, driven college student about to enter the real world? What advice should they ignore?
- What are bad recommendations you hear in your profession or area of expertise?
- In the past five years, what have you become better at saying no to (distractions, invitations, etc)? What new realizations and/or approaches have helped? Any other tips?
- When you feel overwhelmed or unfocused, or have lost your focus temporarily, what do you do? What questions do you ask yourself?

* Lists of questions in different domains
#+HTML: <a href="#top">Back to top</a>
The links are to Wikipedia lists of unsolved problems for the given domain. Way too many questions to copy over and list here, so I'll list the ones that are on my mind from each section. My commentary is indicated, and my questions relevant to the given topic are listed below a line separator.

** [[https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_biology][Biology]]
- Exactly how, where and when did life on Earth originate? How does life arise from the nonliving?
- Exactly how and when did viruses originate?
- Why does biological ageing occur? Is it inevitable?
-----
- Does life exist on other planets (our anywhere outside of Earth)? These could be anything from microbes to intelligent life. Are the dark spots on Venus microbes? Is non-carbon based life possible (eg. on Titan)? Are there places to find life that we are blatently missing due to our built-in assumptions (eg. life arising from cellular automata-like computation deep inside a gas giant). These questions are not on the list.
- Did life start on Earth or did it come from elsewhere, as per the [[https://en.wikipedia.org/wiki/Panspermia][panspermia hypothesis]]. Elsewhere could be as simple as starting on Venus or Mars and being carried over to Earth.
- What did the so-called primordial soup look like? What exactly does proto-life look like? What are the intermediate steps between chemical reactions in the open versus being contain in a cell, versus being contained in a self replicating cell?
- When did viruses emerge? Do viruses (or self-replicating RNA) pre-date life?
- Can life develop and exist outside of so-called habitable zones?
** [[https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_neuroscience][Neuroscience]]
- What is free will? Is it an illusion? Is there a part of the brain that gives us a sense of free will? (related to but not on the list).
- How can consciousness be defined? What is its function? Can it exist after death?
-----
- Is the activity of the brain computable? In other words, could we build a computer that emulated a whole brain, neuron by neuron?
- To what extent do quantum effects matter for cognition? There has been research on this, but I've also heard the argument that invoking quantum is a way to mysticy human cognition and make it more "special" than it actually is.
** [[https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_physics][Physics]]
- The diameter of the observable universe is about 93 billion light-years, but what is the size of the whole universe? Is the universe infinite?
- Why does time have a direction?
- The values of the fundamental physical constants are in a narrow range necessary to support carbon-based life. Is this because there are an infinite number of other universes with different constants (many worlds interpretation of quantum mechanics), or are our universe's constants the result of chance, or some other factor or process?
------
- Can the surface of a black hole perform the computation necessary to produce/simulate a universe? Where in the physical universe is complex computation happening (eg. very large scale cellular automata) that we otherwise might not appreciate right now?
- Is the universe infinite? If this is the case, then if we look far enough forward we will see the back of our heads. Related: does the universe have curvature?
- Is faster-than-light travel, or teleportation, or anything that gets us past the universe's speed limit possible? So much of science fiction relies on this.
- Is the many worlds interpretation of quantum mechanics true? How can we test this? Would there be way to interact with parallel universes? Another common [[https://en.wikipedia.org/wiki/Everything_Everywhere_All_at_Once][science fiction trope]].
** [[https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics][Math]]
- What is the Turing completeness status of all unique elementary cellular automata?
-----
- Is there a way we can find out whether a cellular automata is Turing complete without literally building a Turing machine? Are there shortcuts? Is this something AI could help us with? How do we score cellular automata in terms of their complexity? Perhaps there is a spectrum that is more complete than the binary Turing complete or not Turing complete?
** Computing
- Can we develop human level or superhuman intelligence by means of scaling alone? If we keep feeding training examples into a LLM (or something multi-modal) and the architecture was a transformer with minimal bells and whistles, could we get to AGI? This is related to the [[https://gwern.net/scaling-hypothesis][scaling hypotheis]].
- Is it possible to align AGI with humanity? There are many who think the answer is no, and either AI will kill us directly, or AI intersecting with profit motives and our inner demons will kill us.

* Other
#+HTML: <a href="#top">Back to top</a>
I provide attributions and commentary accordingly after the question. They are in no particular order (yet). If there are no attributions, then the question comes from me (or more likely I think I came up with it, but I heard it somewhere).

- What is something that you believe to be true, that if you told people, they would not only disagree with you, but think you are totally crazy? From Peter Thiel. The context here is that if you have a definite answer to this question, there's a chance that you could turn this into a pretty good startup that "disrupts an industry" to use the optimistic lingo of the late 2010s.
- How can you achieve your ten year plan in six months? From Peter Thiel. I like to flip this one too and ask how you would achieve your six month plan in 10 years. Related to an article I wrote called "[[https://tjburns08.github.io/how_to_get_fit_long_term.html][how to get fit in 20 years]]," whereby the context of losing weight and getting in shape often should be slow-tracked rather than the trap of "lose 30 pounds in 30 days" or whatever.
- What would I do if it were impossible for me to fail?
- What would I do if I knew I was going to fail? From Seth Godin, who flips the script on the more commonly asked question about what one would do if failure were impossible. It flips the focus from the outcome to the process? This resonates with me quite a bit.
- What is your felt sense on the topic? Attributable in part to Daniel Schmachtenberger, but also Focusing by Eugene Gendlin? Felt sense can be a vibe check, or it can be a physical sensation, like a pit in the stomach. These feelings are important at least in figuring out where you brain sits on a subject, and should be interrogated accordingly.
- Is this a finite or an infinite game? If its a finite game, how can we move it in the direction of an infinite game? From James Carse. For context, a finite game is a game in which the goal is to win, and an infinite game is a game in which the goal is to play the game again tomorrow. Working out is an infinite game. Pick-up basketball with regulars at a park has both finite and infinite elements to that. You want to win, but you also want your friends to want to play basketball again with you next time you show up, so you have to play nice.
- Where are people gaming the game? Also related to James Carse, but its something I've been asking recently. An example of a game that has been gamed is professional bodybuilding, which basically has anabolic steroid use as an entry requirement (not to strawman the rest of the sport).
- How can I solve a simpler but related problem? How can I simplify the problem? How can I generalize the problem? Related to Chaude Shannon, and [[https://www.youtube.com/watch?v=neA0NJNUEfM][this MIT lecture]] about his problem solving process. Often, you do this loop where you simplify and generalize and reformulate over and over until you get to something fundamental. Like perhaps a theory of information. If you don't listen to this lecture that I linked, note that this is different than you think. It's not the Einstein quote about making things as simple as possible but no simpler. It's actually about not being afraid to simplify beyond that, even if it takes you away from the problem you're solving.
- What kind of problem is it that I'm solving? (eg. a math problem, an optimization problem, etc). This might help cue up the right mental models.
- What is the inverse of the problem? From Charlie Munger's habit of inverting the problem. How could I totally mess this up? How could I make things maximally worse? How could I ensure that I would lose in the fewest possible steps? Alex Hormozi uses this a lot as well. I find it to be very effective.
- What are the biggest ideas in your field? Related to Charlie Munger, and his process of collecting so-called [[https://fs.blog/charlie-munger-mental-toolbox/][mental models]]. It's a question you ask an expert in something that you're not an expert in. I'd say its increasingly important as things get increasingly interdisciplinary (eg. talk to any cancer biologist about how many fields merge together for that one).
- What action could you do today that would make every other thing today irrelevant or trivial? Related to Tim Ferriss and I think Cal Newport. Think of it as the thing that would take down the other things like dominos.
- What are the most important things to get done this week (as opposed to shorter time scales). Cal Newport. You can move this out to month and year and even farther out. It at least gets your head in the right place. Related to the question of whether you're hunting antelope or field mice, by Tim Ferriss.
- What are the steelmanned versions of each of the perspectives around the topic/problem? What is the dialectic of each of these perspecives? Daniel Schmachtenberger's sensemaking process, which is increasingly important in a world of ingroup/outgroup polarization.
- Version 1: thing. Verion 2: different thing. Version 3: thing from version 1. Balaji Srinivasen. Not a question but more of a mental model for organizing a particular topic. Eg. Version 1: learning via conversations with experts. Version 2: learning via books and lectures. Version 3: learning via conversations with expert AI models.
- How can I do the thing without spending a penny? Jacob Lund Fisker. Related to his exercise of not spending a penny for X months. You start thinking in terms of growing your own food, learning new skills, and all of that, even if you do this as a thought experiment.
- For a given action, what are all the things that I am doing (you never do one thing, as per systems thinking)? Jacob Lund Fisker. For example, riding my bike to the gym as opposed to driving is also cardio, and "getting out into the world" and learning about necessary bike maintenance and repair, which could turn into a side gig, and so on. Lots of benefits there as opposed to driving to the gym in order to sit for 1 hour on an exercise bike.
- What is actually on your mind? Even if its toally politically incorrect and absurd? Indirectly related to Louis CK, whose humor often revolves around him saying things that a lot of people think about but don't outright say. This is not a question to get you to talk a certain way (especially in these times), but one to at least get you to be real with your thoughts and feelings, even if they remain private.
- What would X do? What would X say about this. A generalization of what would Jesus do. But also related to Charlie Munger's mental models. What would a chemist say about this? An economist? Joscha Bach? Whoever your intellectual heroes are. Family members and friends you trust and respect. And so on.
- What wisdom can I pull out of this person/thing/event? For example, my mom taught me how to be tough, in ways that often go beyond words I could put here.
- What are the levers here that I can pull? How could I max them out? An example: if a certain type of outreach is getting me clients, maybe I can just do more of that.
- What are the incentives behind this? Related to Charlie Munger "show me the incentive and I'll show you the outcome."
- What cognitive biases could be impacting this topic/problem? Related to Kahneman and Taversky, and also Eliezer Yudkowsky and the rationality movement? There are quite a [[https://en.wikipedia.org/wiki/Cognitive_bias][number of them]].
- Why do you THINK this is the case? Eliezer Yudkowsky on [[https://www.lesswrong.com/posts/Mc6QcrsbH5NRXbCRX/dissolving-the-question][dissolving the question]].
- Where are the leaky abstractions here? What are they pretending to be? What are they really? This is Gwern's article on the [[https://gwern.net/unseeing][hacker mindset]], as "seeing through and unseeing."
- Why? Can't forget the importance of chaining these together. Just don't fall into the trap of answering with words every time. This is similar to what is known as the "[[https://en.wikipedia.org/wiki/Five_whys][five whys]]" in business. But the devil in the details is knowing what specific "why" question to ask at least point. Why is not a line of inquiry. It is a tree of potential why branches that pretends to be a line in that you only really traverse one path when you do five whys.
- What are the relevant things here? This sounds like a trivial question, but as per John Vervaeke and his concept of [[https://www.youtube.com/watch?v=H-opRmx6C9c][relevance realization]], there is a whole lot of "what is relevant" that happens sub-verbally. So this is actually getting you to pick up on the things that your brain finds to be relevant at any given time.
- What are the virtues that I am working on? What are the virtues that matter to me? This is [[https://fs.blog/the-thirteen-virtues/][Ben Franklin]].
- What does my Jungian shadow want? Related to Carl Jung. The Jungian shadow is your so-called dark side.
- Am I oriented toward the greatest possible good? If not, how can I adjust my life such that I am? This is Jordan Peterson in terms of the specific wording (disclaimer: I don't necessarily agree with his political views), and it is a common religious theme. Daniel Schmachtenberger has similar questions around "who do you serve, and is that the higest possible thing you can serve."
- What makes you laugh? What makes you cry? Especially things that make you laugh and cry when no one else is doing so (which can be embarrassing)? What makes you laugh so hard that you're on the ground rolling around? What's the hardest you've laughed in recent memory? Same questions go for crying? Are there particular themes here?
- What fictional characters or situations in fiction do you most relate to and why?
- What would your 85 year old self tell you? Alex Hormozi asks this question. Related to the Solomon effect: everyone can give good advice, but its harder to give that advice to yourself.
- What Jungian archetypes (aka characters from fiction or wherever else) are guiding you day to day?
- What programs that gave you success earlier in life are no longer appropriate at this phase in life? From a conversation with a (very wise) collague named Chandra during a business trip.
- If aliens came to the planet and they were going to kill 99% of the population, and they were deciding whether or not they were going to kill you, what would be the case you state for them to keep you alive? This is a grad school interview question that Garry Nolan likes to ask.
- In the given situation, what are the things that you can change, and what are the things that you cannot? This is Epictetus, essentially from the start of the Enchiridion, though it is a theme throughout, and a common pillar of stoicism at large.
- If you knew you were going to die in six months, how would you spend the remaining time on this Earth? I'm pretty sure most people ask this question at some point. Maybe one of the "endgames" in life is to get to a point where you wouldn't change a thing.
- If you could start and run a project that would continue for 1000 years after you were dead, by competent people (and/or robots), what would that project be? Related to the Long Now.
- What do you see as the third attractor? What does it look like? What needs to be done to move us in that general direction? This is from Daniel Schmachtenberger, and the metacrisis.
- What kind of music really gets you going and why? What songs are you really into right now? Some times I find that there's some deeper meaning here.
- If you were suddenly on your deathbed, what would be your regrets? What would you be proud of?
- What good can come out of this? Related to how Jocko Willink says "good..." whenever something bad happens.
- What are the nth order effects, positive and negative, for the action that I am going to take? Lots of people ask this, but the ones that stand out in my corner of the world is Charlie Munger, and Jacob Lund Fisker. A pillar of systems thinking.
- What is the relationship between X and Y? Purposely a broad question. This comes from Whitehead, David Bohm, Forrest Landry...thinkers who focus less on the "nodes" and more on the "edges." Related to systems thinking.
- What are the attractors your actions (or the actions of whoever) are moving you towards? This is complex systems theory, but spoken by Daniel Schmachtenberger, in terms of where society is heading. The attractor of order (eg. police state, AI surveillance), and chaos (eg. anarchy of so-called failed states), and the third attractor, which is not really well defined except in terms of what it is not, and it is not the first two.
- What is/was this particular thing (part of me, habit, thought pattern, feeling) serving? From psychotherapist Dr. James Hollis.
- What is wanting to find expression through you? From psychotherapist Dr. James Hollis.
- (when faced with a decision) Does this path enlarge me, or diminish me? From psychotherapist Dr. James Hollis.
- If I was found to be naturally really bad at X (eg. a skill I'm trying to learn, marriage, etc), how would I do things differently? This question is one of the reasons I got good at computer science. I originally thought I was naturally bad at this type of discipline, so I treated myself as if I was really bad at it, which led me to devote extra time to it, review the fundamentals more often, etc.
- It's five years from now and X failed (where X is some sort of endeavor). Why did it fail? This is called pre-mortem, and I first came across it from Tim Ferriss. You can also do this with habits and everyday life as opposed to goals/endeavors. Eg. It's five years from now and I gained 100lb of fat, or I'm in a midlife crisis, and so on. Why? The pattern here is these types of questions are good ways to stimulate constructive self criticism around whatever you're doing right now.
- For a given future thing, what is it that you fear most? If that thing you fear happens, what is one thing you could do that would make the situation a little better? This is the concept of [[https://tim.blog/2017/05/15/fear-setting/][fear setting]], from Tim Ferriss.
- What are the limits of the model? Can you use the model to reveal its own limits? This is often said by Daniel Schmachtenberger, with reference to Gödel's Incompleteness Theorems, as well as the first line of the Tao Te Ching (The Tao that can be told is not the eternal Tao). Every model has its limits, and it is important to know what those limits are when you use the model. This can range from a literal model in data analysis (eg. the limits of tools like UMAP, something [[./the_beauty_is_truth_delusion.html][I've talked a lot about]]), to lenses through which you see the world (eg. relating everything to [[./coding_as_philosophical_project.html][computation by analogy]], as people like Joscha Bach masterfully do).
- What is it about me (the things I can control) that has led to or catalyzed this outcome? From Dr. James Hollis, but can also be thought of as a generalization of pre-mortem.
- What is inevitable? This is a question that my former thesis advisor Garry Nolan asks.
- How do we taxonomize it? This is a question from Daniel Schmachtenberger. When he is discussing a problem in whatever domain, ultimately whatever is found needs to become a taxonomy. This is related to the MECE trees that consulting firms like McKinsey make. Which is also related to problem decomposition, which you learn how to do in your first computer science class. The outcome is the same. You've taken what you've got and put it into a tree form. Yes, it might be better represented as a mind map, but for some reason, the brain is better at thinking in taxonomies than mind maps (without the aid of pen and paper).
