#+Title: There's some signal there
#+Author: Tyler Burns
#+Date: August 6, 2024 - August 6, 2024

-----
/Passersby may stop for music and good food,/\\
/But a description of the Tao/\\
/Seems without substance or flavor./\\
/It cannot be seen, it cannot be heard,/\\
/And yet it cannot be exhausted./\\

Lao Tzu, /[[https://terebess.hu/english/tao/gia.html#Kap35][Tao Te Ching]]/, Gia-Fu Feng and Jane English translation\\
-----

The title of this essay is an expression that I use in casual conversation all the time, but I have still not written down or seen it written down anywhere. So that means it's time to get this into public record.

One night when I was around 16 years old, I was going down internet rabbit holes. At some point, I came across [[https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life][Conway's Game of Life]]. This is a so-called cellular automata, where simple rules played out on a grid can give rise to emergent complex patterns. Furthermore, this particular cellular automata was Turing complete, which means that anything any computer could do could be implemented in Conway's Game of Life (eg. by turning the emergent complex patterns into [[./logic_gates.html][logic gates]] and so forth). I am not sure why I was so drawn to it, and I did not have the computer science background to fully understand what I was looking at.

But I knew there was some signal there, so I kept it in my back pocket.

I ended up majoring in biology in undergrad, and going the route of biology PhD. This would entail me spending long hours in a [[./how_to_solve_problems.html][research laboratory]] conducting experiments. However, the biology datasets were getting bigger at the start of grad school, so I took a genomics class to get a feel for how to analyze things that went beyond what excel could do. There, I encountered computer programming, which I knew next to nothing about. The bioinformatics instructor showed us a computer program (in perl) that would do something fairly simple. He showed us the code and then he ran it. And I got the same feeling that I had that one night when I was 16 looking at Conway's Game of Life.

Despite this class being very stressful (too much too fast), there was some signal there, so I kept it in my back pocket.

A few years later, after I had some momentum going for my project, I decided to take [[https://www.youtube.com/watch?v=KkMDCCdjyW8&list=PL84A56BC7F4A1F852][CS106A]], the intro computer science class with the undergrads, at the age of 28. By the time I got to the third problem set, designing Atari Breakout using a java graphics library, I knew that even though there was no direct connection to my wet lab work, I had to keep going. I didn't know if this would do anything for my thesis (it did), and I still wondered if I was even smart enough for this line of work.

But there was some signal there, so I kept going, evenings and weekends, taking class after class.

It was around this time that I learned about this thing called "consulting." It was basically a catch-all word for any sort of non-employment work where the consultant was an expert at something that the client was either not an expert in or didn't have time to do the thing. One of my former TAs was working as a management consultant, and I talked to him about it. My aunt was a consultant, so I talked to her about it. There were a few people in my thesis lab who were doing consulting here and there for biotech companies interested in some of the tech coming out of the lab. So I did a few projects with the Stanford Healthcare Consulting Group, to get my feet wet.

I wasn't sure if I wanted to be a consultant after grad school, but there was some signal there, so I kept these ideas and experiences in my back pocket.

Toward the end of grad school, the so-called cost of living crisis was really starting to show itself, and I was running out of money. And from all my experiences up to this point, and from a pivotal conversation I had with my uncle (a professor) and my aunt (the aforementioned consultant), when the opportunity came up to do bioinformatics consulting for a company that had come out of my thesis lab, I jumped on it.

Between the experience as a healthcare consultant, and the trajectory from Conway's Game of Life to CS classes with the undergrads, there was signal there that was too strong to ignore.

This led to a chain of events, that led me to run a life sciences consulting company out of Berlin, Germany. I'm not a gajillionaire, but I have crafted the lifestyle that I want (call it time wealth), and I am doing meaningful work for myself on my terms. Yes of course there was a bit of luck involved, but a lot of where I am right now I can attribute to keeping stock of where I am able to see signal amidst all of the noise, and trusting that every bit of signal I pick up will matter eventually.

What do I define as signal? This is something that feels right at a deep level, even if I can't fully articulate why just yet. When I say deep, I'm not talking about the signal I see when I come across an ice cream shop on a hot summer day. I'm talking about the kind of signal that sits with you for years if not decades before you fully realize what it is. The kind of signal that comes when you read a passage or poem or hear a song that toally resonates with you and you don't know why.

So then what do you do with this?

I would say that whenever you come across something that feels profoundly right, something that feels like it is part of [[./purpose_driven_vs_purposeless][the way]] forward, but you can't quite articulate why, simply take note of it. Say "there's some signal there" and put it in your back pocket, and then wait a year or ten. You'll know what that is eventually, and you'll be happy you were paying attention.
