#+Title: The virtue of depth
#+Author: Tyler Burns
#+Date: April 7, 2023 - April 7, 2023

[[./index.html][Home]]

* Introduction
When I was in grad school, I focused on the same narrow little thing on the timescale of years. Every day I would obsess about all things technical and scientific related to that narrow little thing. I had a [[https://pubmed.ncbi.nlm.nih.gov/28094900/][wet-lab project]] that was like this, and a [[https://www.biorxiv.org/content/10.1101/337485v1][dry-lab project]] that was like this. When I left graduate school, I left the country and I started working on a self employed basis and eventually started a company. Now my day to day involves typical real-world things. Taxes, immigration bureaucracy, family responsibilities, finances, market research, and keeping track of the four horsemen (war, pandemic, famine, death).

A lot of this involves [[./scrolling_problem.html][scrolling]] through lots of feeds with lots of information across lots of modalities (text, picture, video), often inflammatory. Aside from the work I spend trying to [[./how_i_curate_content.org][organize my information intake]], there is something that was lost upon entering the real world. In my longing for it, I can properly describe it, so I need to get it on paper. What I lack now that I had in grad school was depth.


* What is depth
What is depth? The example that comes to mind, though fictional, comes from the book Musashi by Eiji Yoshikawa. Miyamoto Musashi is a Japanese swordsman who lived around the year 1600. He was known for his skill, as tested by apparently winning 61 duels. I can't find the exact passage (I only have the audiobook), but he goes to a tea ceremony, and in observing the ways of the teamaster, he realized that she had trained with the same lifetime devotion, also for several decades, in the art of tea rather than the art of the sword. In that regard, there was a mutual respect for the depth of each respective practitioner.

Ok, so what is depth? Is it training or practicing for a long time? Is it experience? Is it knowing a lot about something? Is is being able to apply knowledge and talent to achieve some particular goal? Is it wisdom? Is it being able to do something unconsciously and gracefully because you've done it enough times? I think the answer is yes.

Let's look at what depth is not. That's an easier question, because I think there is a lack of depth at the societal level, so it's not hard to find it. The opposite of depth is being pulled in a million different and unrelated directions. It's skimming part of an article and trying to impute the contents of the article for half a second, and then going to the next article in your feed. It's high-level overviews of a topic. It's ChatGPT summaries of a book. It's getting some email pretending to be urgent that derails what you were intending to work on today. It's having too much stuff in your inbox. It's office politics. It's anything that you want to "get done" rather than do.

Ok, now we can flip it again, and ask what depth is in the light of what it's not. Depth is doing one thing or a bunch of things united under one theme. It's reading the article through, slowly, and thinking about it, and talking about it to others. It's a deep-dive into a topic. It's reading an actual book. It's not checking your emails at all. It's craftsmanship, rather than productivity. It's things that you probably don't have time to do. In the light of Musashi, it's something that you could ascribe a belt rank to.

Let's linger on that last point. I'm currently training Brazilian Jiu Jitsu. When I go into the dojo, the intent is not to get some set of things done and then go home. The intent is to deepen my skills through deliberate practice (which is practice with feedback). Over and over. For as long as possible. The belt rank goes up after you've done enough deliberate practice that you can do a particular set of things and grok a particular set of concepts that tie these things together.

But again, adult life is adult life. Starting in high school, you're pulled a million directions. You can't just shut everything out for the sake of depth. This is why I'm placing depth as an ideal to strive for, even if its impossible. I am calling depth a virtue, and an important one for the modern world.

* Depth as minimalism
I can't talk about depth without talking about [[https://en.wikipedia.org/wiki/Cal_Newport][Cal Newport]]. He has written many books that dance around this topic. In sum, he encourages blocking out chunks of the calendar for what he calls "deep work" or focused work that deepens your craft. He talks about deliberate practice being vital to whatever you do. He talks about digital minimalism. He advocates not being on social media. In his podcasts, he's building toward a bigger concept he calls "deep life" which to the best of my understanding is an ideal around the sum of all of these things.

But in my discussions, I hear the same comments. Some people can't quit social media. I depend on it for marketing, which leads to food on the table. I can't quit email. I can't stop checking the news and the scientific literature. All these things either pay the bills or give me an informational advantage.

* Depth as narrowness
So then how do you achieve the virtue of depth when the modern world is doing everything it can to wrestle that away from you? That's a good question. I think the place to start is with a related [[https://www.lesswrong.com/posts/yDfxTj9TKYsYiWH5o/the-virtue-of-narrowness][virtue of narrowness]]. This has somewhat of a negative connotation, but hear me out. If you've already done as much of the Cal Newport timeblocking and digital minimalism as you possibly can, is there a way you can take the multitude of things on your plate, and somehow unite them into a particular theme or framing?

Consider the case of [[https://en.wikipedia.org/wiki/Jacob_Lund_Fisker][Jacob Lund Fisker]]. He is a full-on generalist, who advocates being a generalist rather than a specialist. Whatever it is that you'd otherwise call someone to do (repairs, plumbing), he does himself. He grows his own fruits and vegetables in the growing season. He does his own finances. He solves his problems without spending a dime. But I would argue that he nonetheless practices the virtue of depth. Why? It's because all the things he does are united by a particular theme: frugality. His goal is to spend as little money as humanely possible, whatever it takes, and he has brought his annual expenses down to around $7000. So while his skill set is very broad, his goal is very narrow. While he might have superficial understanding of indoor plumbing in relation to a trained plumber, he has black belt depth in the craft of frugality.

What does Jacob Lund Fisker teach us? You can take all the things you do, and unite them under a very narrow theme, which you work to deepen. It's subtle, but perhaps this will at least get rid of the feeling that you're being pulled in a million different ways. Perhaps what matters is the feeling of going deeper with each new experience, in some framing, any framing. When Jacob encounters a new thing, be it a topic in conversation or a piece of news, (I'm guessing) he simply asks himself if this can solve any problems related to saving more money. If yes, great. If not, then focus on something else.

What if you're not interested in frugality? What if you're not focused on anything in particular? Enter Venkatesh Rao, author of the popular mind-expanding blog [[https://www.ribbonfarm.com/][Ribbonfarm]]. In a [[https://youtu.be/ZlhzwLGq2Gw][podcast]], one thing he said that I found interesting was this idea of narrowly optimizing for something completely arbitrary. The example he gave was when he was looking for a house, he and his wife decided that they wanted a nice view of the stars so they could use their telescope. That's it. Of course, there were other things that are important, but in first place, of dire importance, was this narrow arbitrary goal, which helped them focus and get through the process. He advocates for everyone doing this, and he says its is one of his biggest pieces of advice. To just choose something completely random in your life, make it of utmost importance, and optimize toward that.

Perhaps this simply makes you more playful and loosens things up. Perhaps this is one way to artificially impose narrowness and therefore depth in your life. Perhaps this simply helps you make decisions. Either way, I think it highlights the path to the virtue of depth through narrowness.

* Conclusion
I think we all want depth in our life. I think it's tied to meaning. I think the question "what is the meaning of life" can also be framed as "is there some theme I can use to tie together this chaotic mess that we call life?" Life is complicated, and most of us can't just shut off anymore and slowly read a book, or go for a walk in nature, or any of that. When we do have time off, the attention-seeking algorithms in internet-connected devices in our pockets beckon us.

This is why depth needs to be a virtue. We won't always have it, but we can strive for it. If we don't strive for it, society will push us away from it, and back into the infinite scroll and whatever else. What I can tell you is that from my depth-centric work in graduate school, and the work and skills that I consider "crafts" (music, martial arts, sports, computer science), I get lots of satisfaction from knowing that at the end of the day I am deeper than I was when I started. I get lots of satisfaction knowing that I went deep with something. Anything. On the contrary, when I feel like I've just been skipping over the surface of this and that, I feel terrible. I think we should all ask ourselves, whatever it is, how can we go deeper and not wider." It might be literally cutting tons of things away and narrowly going after one thing, or it might be a simple re-framing a-la Jacob Lund Fisker, where you narrowly go after one theme. Either way, whatever it is you're up to, I hope you can go deep.




