#+Title: Zelda, the hero instinct, and narratives
#+Author: Tyler Burns
#+Date: June 19, 2023 - June 21, 2023

[[./index.html][Home]]

I.

In the past few days, I have been watching a [[https://www.youtube.com/watch?v=Z6hjG6MCcZ8][full playthrough]] of the classic game [[https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_A_Link_to_the_Past][Zelda: A Link]] to the Past on SNES. It is a game that for many reasons I never played as a kid (I went the Sega and PS1 route), but I know is packed with nostalgia for others. As a result of having no nostalgia upon watching the gameplay, I can do an unbiased analysis of the game itself. What I like about analyzing old (8 or 16 bit era) games is that the first principles of the game are laid bare, as there is no reliance on being bamboozled with amazing life-like graphics and physics to make the game "good."

The game starts off with an immediate quest for our hero, Link, to rescue the captured princess Zelda. So with a start, you get out of the house, run to the dungeon through rain and thunder, and find the princess. So the standard hero trope. But then, you find yourself on a much larger quest, to rescue not one, but seven damsels in distress from dungeons guarded by evil dungeon masters, in a parallel "dark world" similar to the one in [[https://en.wikipedia.org/wiki/Stranger_Things][Stranger Things]]. Of course, you, Link, are the only hope.

On top of this, it's open world gameplay, something that is more common today. There is the main quest and side quests. There are people you can talk to, who have meaningful tidbits of information that can allow you to do meaningful things and find meaningful secrets. There are secret rooms, caves, and passageways that make you feel good when you find, similar to the secret doors in Wolfenstein 3D. Often, you have to transport between the real world and the dark world to get the next thing done. It's easy to get totally absorbed in the game, both as a player, and a viewer. It's easy to get into the [[./tao_of_problem_solving.html][flow state]].

One way to think of this game or this type of game is that in comparison to real life, everything is meaningful. The conversations matter, the surroundings matter (gotta find those secret passageways), the side quests matter, the main quest matters, and within the main quest, you are the hero. You are the only hope. On top of that, everything is enchanting. New dungeons, new creatures, new biomes, two parallel worlds, books that translate ancient languages, a wise man descended from seven great wise men guiding you, magic exists, and there is an evil wizard using a lot of it.

So not only do you have challenging gameplay that requires exploration, and developing skills to navigate, fight, and solve interesting puzzles (in the dungeons, for the next door to open, for example), but you also have these layers of meaning and enchantment serving as a backbone. The former is what triggers a [[https://en.wikipedia.org/wiki/Flow_(psychology)][classic flow state]], and oftentimes that by itself is sufficient to make a great game (think [[https://www.ribbonfarm.com/2023/03/30/tessellations-for-the-end-of-history/][Tetris]]), but the latter grounds that flow state so it always feels like you're flowing to a particular destination. It's what one might call "sense of purpose." Overall, this game is made up of fun, challenging activities grounded in a strong sense of purpose and enchanting things yet to be discovered.

II.

What does all of this sound like to you? Well for me, it sounds very much like childhood in general. You play a lot more than you work. There is a lot of fun to be had. There is a strong sense of purpose: to grow bigger and stronger and smarter and to do good things (at least this is how I was raised). And everything is enchanting. There are all kinds of weird, crazy, fascinating, exciting new things every day. Not that I felt like a hero rescuing damsels in distress from evil doers, but it sure felt like a palpable future. I'll note here that the original Zelda game for NES was [[https://www.youtube.com/watch?v=uXg4klwhtiU][motivated by the outdoor adventures]] one of the creators went on as a kid where he grew up on the outskirts of Kyoto, one of which included actually finding and exploring a cave, a common trope in these games.

Ok, now lets jump to adult life and compare it to Zelda. Is there exploration? Somewhat. We get to travel sometimes, but most things are mapped out and we can figure out where we are and what's around with our smartphone. What about enchantment? Not so much. Especially for a guy who has a PhD in biology. It's there, but I have to [[https://en.wikipedia.org/wiki/Sponge_spicule][look harder]] and [[https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_biology][ask better questions]]. But even then, it's not always the same level of intense fascination. What about quests to rescue damsels in distress? Not really. I am married, but my wife is very tough and I don't find myself rescuing her all the time. My family in general is pretty self sufficient. The modern world makes it so. While I do help my family when I can, they would not be severely crippled if I died. The fate of the world does not depend on my heroic existence. A lot of people get PhDs in biosciences because they think they're going to [[./purpose_driven_vs_purposeless.html][cure cancer or whatever else]]. Turns out that curing any disease is very complicated and requires more than just one person. Just look at COVID. Did one hero emerge and save us all? No. There was a worldwide group effort to develop vaccines that some say were good and some say were evil.

At the psychological level, why is Zelda such a good game? Somehow, its triggering a bunch of aspects of the brain that we evolved over millions of years. At some level, it must have been advantageous to find "vignettes" in our life where we could be the hero and explore the world and defeat the villain, and be [[https://en.wikipedia.org/wiki/Novelty_seeking][enchanted by novelty]] (rather than terrified). I would guess that this is a pre-[[https://en.wikipedia.org/wiki/Dunbar%27s_number][Dunbar]] (back when we were hunter-gatherer tribes of 200 or so) evolution that stays with us today as neural legacy code. In the hunter-gatherer world, we knew a lot less. Of course, I don't have a time machine that can take me back, but from what it seems from what we know about present-day hunter-gatherers, we can say a few things. We were guided a lot more by mythology, which was enchanting stories mixed in with wisdom from our revered tribe elders (they had their place, in comparison with our fascination with Rogaine and Botox). There was indeed evil in the world: [[https://www.youtube.com/watch?v=-HrfbV16-FQ][lions and tigers and bears]], and of course, whatever tribe we were warring with. Survival was a lot harder. And there were heros that probably emerged from all of this.

One place you see the emergence of heroes today: war. I listen to [[https://www.youtube.com/watch?v=inX2pRALbGA][podcasts]] where people who fought in Iraq and Afghanistan, talk about their time there. They emphasize that it was somewhere between not fun and terrifying, but they have lots of acts of heroism that happened that are, by my standards, epic. Similar stories emerge from those retelling what their grandparents went thorugh in the two World Wars and Vietnam (something you can find on discussion forums like Reddit). In short, I respect and thank our soldiers. Another example: during the Fukushima reactor meltdown, there were [[https://en.wikipedia.org/wiki/Fukushima_50][people]] who sacrificed themselves to stay at or go into the reactor to do things to prevent the meltdown from getting much worse. These people went in to the reactor, did what they had to do, and many of whom died upon their return or a number of years later. Heroes.

We might think of our fascination with heroes and their journies as a computer program that evolved in our brain, that we feel as a hero instinct. If we didn't have this, then it would be a lot harder for ordinary people to take the reins during hard times and do extraordinary things that benefit the group. The group that has at least a few members with a strong hero instinct will make it through hard times in comparison to a group that does not have anyone with the hero instinct. But the interesting thing is that if we consider how popular the Marvel movies, Star Wars, Harry Potter, and Zelda are, it seems that a huge chunk of the population has some sort of hero instinct. Many of us really vibe with these things. It might be that the strength of that instinct determines whether they're willing to take on the risk of pain and death to do the heroic thing when the time calls for it.

People like psychologist [[https://en.wikipedia.org/wiki/Carl_Jung][Carl Jung]] studied this quite a bit. If you've ever heard the term "Jungian archetype," this is the hero or god/goddess that personifies some virtue or set of virtues. The Greek and Norse gods, the Marvel characters, Luke Skywalker, Frodo Baggins, Link, and so on. They guide what we strive for, just as the virtues programmed into our brain and our culture guides us. They are one and the same.

The hero instinct ideally leads to what's known as the [[https://en.wikipedia.org/wiki/Hero%27s_journey][hero's journey]], something studied and fleshed out by writer Joseph Campbell, who was influenced by Carl Jung. Think of this as the archetypal story arc that the heroes embed themselves in. You're in your comfort zone, then there's a call to adventure, which brings you to experience things that resemble the depths of hell, you persevere, you transform, and you return home as a completely new person, and a hero. In short, playing games like Zelda might be thought of as triggering this hero instinct and the desire for the hero's journey, which in turn might be thought of as some pre-programmed set of virtues and their personifications that tell us what to do next (to do the heroic thing rather than sitting passively, even though it's going to hurt).

So then what does this mean for the modern world, where [[https://www.youtube.com/watch?v=WVEP0zAK-xQ&t=268s][every major problem]] (eg. climate change) requires a massive group effort rather than an individual hero? Where good and evil are not so well defined? Where enchantment is much harder to come by? Where exploration is not the same, given that we have satellite images and street-view images of most places? Where we can watch [[https://www.youtube.com/watch?v=cOScCHtNWYM][travel vlogs on YouTube]] to see what its like wherever. Where globalism has killed a lot of the cultural differences in the world? Or perhaps put differently, what kinds of instincts would we have evolved if we were an interconnected, global-supply-chain superorganism that we are now, but for millions of years? Would there be more of a "massive global teamwork" instinct (as opposed to the sports team sized teamwork instinct that is of course very palpable)? It's not as sexy as the hero instinct that Zelda exemplifies. Because we appear to have evolved the latter, not the former.

I have found that the hero instinct sometimes gets in the way now. I watch Marvel movies (which is like 50% of all movies that come out these days...and it's worth pondering why this is the case), and then feel empty inside because my adult life is not nearly as enchanting and heroic as these stories. When COVID showed up, it became clear that there was not going to be a lone hero. The hero instinct approach died pretty quickly. And of course, in the real world, one man's hero is another man's villain (more on that later). That's politics in a nutshell.

The Taoists like to talk about [[https://www.youtube.com/watch?v=cJMwBwFj5nQ][water]] and the wisdom it carries. In the case of being part of a quest or side-quest or whatever else, I think of my time in grad school where I used to go surfing on the weekends. When you're on the board, you're in the ocean waiting for the next set of waves to come. On a bad day, either you wipe out all the time or no good waves come. On a good day, you catch a good handful. You position yourself where you're most likely to catch the wave, and you let nature do its thing. But importantly, you can spend hours out there waiting, and seconds actually on a wave. So maybe Zelda is the epitome of what its like to be on a wave in life, and a lot of adult life is just spent on your board, bobbing up and down in the ocean, just trying to position yourself properly, and letting things happen from there.

What this means is we have to get over the fact that we're not always going to be on a wave. In fact, it will be little tidbits here and there, if that. So we have to be cool with and enjoy the time we spend bobbing up and down in the water, on the surfboard, enjoying the scenery. Some of my best memories from when I used to surf were the things that happened when I wasn't on a wave. I saw a handful of dolphins, sea otters popping up near me, beautiful sunsets, among many other things, while on that board. In those moments, I wasn't pining for that next wave to come. Some of the Eastern traditions (Taoism, Buddhism) put a lot of emphasis on this: enjoying the moment whether or not you're doing something cool, or whether you're in hard times. That's what focusing on the breath does. One quote I heard from a Zen master was something like "If you can't enjoy your cup of coffee in the morning, then I have nothing to teach you."

[[https://www.youtube.com/watch?v=-wIt_WsJGfw][Sam Harris]] (something of a rational mystic) talks about boredom in terms of not paying enough attention. When you're playing Zelda, you don't have to pay very much attention. It's more like attention pays you, and you just sit there as you ride the layers of meaning and enchantment the game experience has. When I meditate (and I'm not talking about the Lotus position and Om, I'm talking about focusing on the breath whether I'm sitting or walking or whatever else), normal stimuli start to become enhanced. I can in fact enjoy my morning cup of coffee without [[./scrolling_problem.html][scrolling]] through social media at the same time. In short, I think the layers of meaning and enchantment and exploration that makes Zelda such a great game can be found in your morning cup of coffee, and I think the opportunity to be a hero (even for something small, for a brief moment) can be found in the humdrum activities of adult life, if you're paying enough attention.

III.

I like working with startups and small to mid-sized companies much more than I like working with larger companies, at least in the role of a consultant. The smaller companies tell me the whole story of what's going on. Sometimes, I'm interfacing with multiple departments. I get to wear multiple hats. In the larger companies, I get put into a tiny little box. In more extreme cases, even the data itself will be obfuscated from me. Now imagine how this would translate to a game like Zelda. The smaller companies represent all of the gameplay dynamics, the map, the quest and/or side quest, the greater storyline, talking to all the villagers, keeping track of what you have to do next, and in short, the full gaming experience that makes a game like Zelda so good. The lager companies represent the gameplay independent of the story. Imagine this as going through the dungeons, solving the puzzles, defeating the enemies, and nothing else. Just going into the next room, and the next room, and that's it. This is sufficient to trigger a flow state, for sure. But this isn't the layers of meaning that make games like Zelda so good.

I [[https://rseng.github.io/devstories/2023/tyler-burns-part-1/][learned computational biology]] after I was already a wet-lab biologist, at the age of 28. What I like about doing computational biology projects now is the capacity for having these potential Zelda-like layers of meaning when I do any project (provided I am allowed to know the information, because the company is sufficiently small). From the standpoint of the consultant, this makes every project so much more fun, and so much more interesting. From the standpoint of the client, I am able to give value that comes from all of me, not just the part of me who is good at analyzing whatever data type the project involves. I think as I get older and more experienced, I crave projects that feel more like Zelda than projects that feel like Tetris (solving puzzles and that's it). The flow state is fantastic, and it's something I live for, but I want it amid the backdrop of the bigger picture. Why we're doing the project itself, what the value is we're providing to the customers, and ideally how we're trying to shift a paradigm.

Having the complete Zelda experience in the workplace is actually shaping up to be quite the challenge in this season of my life. If I were in the standard corporate track, now is about the time I would be transitioning from doing bioinformatics to leading teams of bioinformaticians. While I have gotten very positive feedback in times where I have to lead and mentor people (ask my thesis lab), the act of management doesn't seem to trigger the flow state that I crave. So it's like following the quest the game and getting to make high-level decisions (eg. we're going to get this item before we go to that dungeon), but not actually getting to play the game. On the other hand, if I keep playing the game, a lot of my value at the decision making level, given my experience, will go to waste.

I've had a bioinformatics company for a few years now, which I have run by myself. This year I [[https://www.presidiolabs.org/][teamed up]] with a long-time friend and former colleague from Stanford, and we are going to start scaling soon. I think this might be a nice middle ground for me. I'll be leading a small working group of bioinformaticians, and I'll get to make high-level decisions, but I'll still be in the weeds at least a little bit due to the size of the company. The best way to put it is I want to be able to direct the Zelda quest, but I don't want to give up the video game controller entirely and become detatched from that. At least not yet.

Realistically, if we fast forward 20 years, will I still be coding as much as I am right now? That's a good question. What I've noticed is that at least in the second half of my 30s, I am writing a lot more. A lot of my coding is literate programming ([[./scrna_seq_piepline_pbmc_3k.html][example]]), and then there are articles like these that I find myself writing. So one thing that might happen is that my "flow state," my Zelda gameplay, will transition from primarily coding to primarily writing. Maybe I'll write a book, or maybe I'll write business reports, or literate programming tutorials. I think my time is better spent doing these kinds of things than learning the latest packages, libraries, and frameworks, for things that I already understand quite well conceptually. Maybe what I consider to be holding the video game control will change. It wasn't coding until I was 28. Before that, it was pipettes and reading papers, and that by itself was actually quite fulfilling.

Zelda seems to represent some ideal, some hero instinct, that we all very much crave and like in our own lives. You can see this ideal in archetypal myths of good versus evil, re-told over and over again, with modern formats like the popular Marvel movies. What makes Zelda interesting is that you get the interactive flow state on top of the archetypal myth, representing a participatory ideal in terms of a project or a season in life. There is an obvious failure mode in terms of being too idealistic, which will make you disappointed when your life isn't as interesting or more messy or more tragic than a Zelda game. This is where the antipode, things like Taoism and Buddhism, come in. The idea that you shouldn't spend too much time wanting things or ideals. You're only going to be disappointed. You're only going to suffer. And how through meditation, you might be able to find the Zelda-like vignettes in the subtleties of your everyday life. But all in all, Zelda does a very good job articulating at least how I want my projects to be. This is the kind of work that I enjoy, where you have the flow state of controlling the character but also the high-level decision making that comes from the bigger-picture understanding of the quest and the storyline.

IV.

Let's look again at the narrative layer of Zelda. We have a hero's journey away from home. Link is the good guy, who needs to rescue Princess Zelda, among six other damsels in distress, from the evil Ganon. Now let's look critically at the real world. It's messy. There are lots of narratives being told at the same time, casting the same person as good and evil depending on which memetic tribe you belong to. It might even be that a good person gets re-cast as evil at a later time.

We can look at this and conclude that we should completely do away with narratives altogether. As soon as we cast someone as good or evil, we're narrowing our view, and it's going to lead us to make bad decisions down the line. That kind of thing. I went through a phase where I was like this. But the problem was that narratives kept showing up anyway, and sometimes they were beneficial.

A lot of my younger years was fueled by a hero's journey of sorts, where I was avenging my father's death by studying cancer biology, in order to cure the very disease that took him from me and my family. That got me very far and gave me a foundation from which I have made some good contributions to humanity. There's a counter-narrative to that, though. The one where a vulnerable soul like myself was exploited by the overworking and underpaying academic machine, that filled my 20s with evening and weekend work, and had I stayed to do postdocs and beyond, would deny me tenure and kick me out on the streets at the age of 45 with no savings and no real-world skills.

Which narrative is right? Well, we can banish both narratives because narratives are imperfect. But that's somewhat like trying to banish a [[https://en.wikipedia.org/wiki/Earworm][song that is stuck in my head]]. It's going to keep coming back. So how do you get a song that's stuck in your head out of your head? You either let it play itself out, or you double down on the song and listen to it over and over again. So by analogy, the other option is that I welcome the narratives as the pour out of my subconscious, and [[./dialectic.html][tell myself all of them]]. They say that for every joke, there is a grain of truth. Perhaps this is the case for narratives.

I think there is a bit of a liberating component to this. If we think of narratives as a garden, if someone mad at me says that I suck, then I can just think of them angrily pointing to the cherry tomatoes over in the corner. Yes, those are nice, but did you see the basil that I've got over there? Same goes for when I ask if I had a good or a bad childhood. Kinda both. Was I a good or a bad brother and son. Kinda both. Did the academic system do me good or do me wrong? Kinda both. A relevant symbol that I hold dear to me is the yin and yang of Taoism. These high-level statements contain truth, but their antipodes contain truth too. And that's ok. People like writer and psychiatrist [[https://www.youtube.com/watch?v=N4AFdNxLmb4][Ian McGilchrist]] are reviving this idea for the modern world.

So in the Zelda game of the real world, there are a superposition of narratives happening at any given time, all of which contain some amount of truth, some casting Link as the good guy and some casting Link as the bad guy. If you're Ganon, then of course Link is evil. So in other words, someone somewhere on this planet probably thinks you're are the epitome of pure evil. And again, that's ok. Because it's not about finding the right narrative and sticking to that. It's about finding all of the relevant narratives and being able to embody all of them. I'm not wise by any means, but this might be part of what wisdom is about. Maybe this kind of thinking will also bring a bit of Zelda-like enchantment back into the world too. When you look at objects and relationships and patterns through the lens of several narratives rather than one, you come face to face with the infinite inexhaustible depth of all things. Which is pretty enchanting, if you ask me.
